
// Generated by Cadence Encounter(R) RTL Compiler RC14.28 - v14.20-s067_1

// Verification Directory fv/pipe_mul_top 

module csa_tree_add_469_129_group_97(in_0, in_1, in_2, in_3, in_4,
     in_5, in_6, in_7, in_8, in_9, in_10, in_11, in_12, in_13, in_14,
     in_15, out_0);
  input [3:0] in_0, in_1, in_2, in_3, in_4, in_5, in_6, in_7, in_8,
       in_9, in_10, in_11, in_12, in_13, in_14, in_15;
  output [7:0] out_0;
  wire [3:0] in_0, in_1, in_2, in_3, in_4, in_5, in_6, in_7, in_8,
       in_9, in_10, in_11, in_12, in_13, in_14, in_15;
  wire [7:0] out_0;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_80;
  wire n_81, n_82, n_83, n_84, n_85, n_86, n_87, n_88;
  wire n_89, n_90, n_91, n_92, n_93, n_94, n_95, n_96;
  wire n_97, n_98, n_100, n_101, n_102, n_103, n_104, n_105;
  wire n_106, n_107, n_108, n_110, n_111, n_112, n_114, n_116;
  FAX1 g1474(.A (n_94), .B (n_106), .C (n_116), .YC (out_0[7]), .YS
       (out_0[6]));
  FAX1 g1475(.A (n_107), .B (n_110), .C (n_114), .YC (n_116), .YS
       (out_0[5]));
  FAX1 g1476(.A (n_104), .B (n_111), .C (n_112), .YC (n_114), .YS
       (out_0[4]));
  FAX1 g1477(.A (n_101), .B (n_105), .C (n_108), .YC (n_112), .YS
       (out_0[3]));
  FAX1 g1478(.A (n_93), .B (n_100), .C (n_103), .YC (n_110), .YS
       (n_111));
  FAX1 g1479(.A (n_89), .B (n_98), .C (n_97), .YC (n_108), .YS
       (out_0[2]));
  FAX1 g1480(.A (n_92), .B (n_95), .C (n_102), .YC (n_106), .YS
       (n_107));
  FAX1 g1481(.A (n_88), .B (n_87), .C (n_96), .YC (n_104), .YS (n_105));
  FAX1 g1482(.A (n_90), .B (n_85), .C (n_86), .YC (n_102), .YS (n_103));
  FAX1 g1483(.A (n_77), .B (n_82), .C (n_91), .YC (n_100), .YS (n_101));
  FAX1 g1484(.A (n_75), .B (n_81), .C (n_78), .YC (n_98), .YS
       (out_0[1]));
  FAX1 g1485(.A (n_74), .B (n_83), .C (n_80), .YC (n_96), .YS (n_97));
  FAX1 g1486(.A (n_68), .B (n_66), .C (n_84), .YC (n_94), .YS (n_95));
  FAX1 g1487(.A (n_69), .B (n_67), .C (n_76), .YC (n_92), .YS (n_93));
  FAX1 g1488(.A (n_61), .B (n_64), .C (n_62), .YC (n_90), .YS (n_91));
  FAX1 g1489(.A (n_71), .B (n_65), .C (n_73), .YC (n_88), .YS (n_89));
  FAX1 g1490(.A (n_49), .B (n_53), .C (n_72), .YC (n_86), .YS (n_87));
  FAX1 g1491(.A (n_60), .B (n_48), .C (n_52), .YC (n_84), .YS (n_85));
  FAX1 g1492(.A (n_50), .B (n_63), .C (n_58), .YC (n_82), .YS (n_83));
  FAX1 g1493(.A (n_51), .B (n_54), .C (n_59), .YC (n_80), .YS (n_81));
  FAX1 g1494(.A (n_15), .B (n_31), .C (n_55), .YC (n_78), .YS
       (out_0[0]));
  FAX1 g1495(.A (n_46), .B (n_33), .C (n_70), .YC (n_76), .YS (n_77));
  FAX1 g1496(.A (n_27), .B (n_30), .C (n_57), .YC (n_74), .YS (n_75));
  FAX1 g1497(.A (n_26), .B (n_47), .C (n_56), .YC (n_72), .YS (n_73));
  FAX1 g1498(.A (n_7), .B (n_38), .C (n_22), .YC (n_70), .YS (n_71));
  FAX1 g1499(.A (n_4), .B (n_28), .C (n_24), .YC (n_68), .YS (n_69));
  FAX1 g1500(.A (n_44), .B (n_16), .C (n_32), .YC (n_66), .YS (n_67));
  FAX1 g1501(.A (n_35), .B (n_43), .C (n_9), .YC (n_64), .YS (n_65));
  FAX1 g1502(.A (n_40), .B (n_36), .C (n_19), .YC (n_62), .YS (n_63));
  FAX1 g1503(.A (n_5), .B (n_34), .C (n_42), .YC (n_60), .YS (n_61));
  FAX1 g1504(.A (n_23), .B (n_41), .C (n_37), .YC (n_58), .YS (n_59));
  FAX1 g1505(.A (n_1), .B (n_14), .C (n_10), .YC (n_56), .YS (n_57));
  FAX1 g1506(.A (n_21), .B (n_11), .C (n_13), .YC (n_54), .YS (n_55));
  FAX1 g1507(.A (n_45), .B (n_25), .C (n_17), .YC (n_52), .YS (n_53));
  FAX1 g1508(.A (n_20), .B (n_12), .C (n_39), .YC (n_50), .YS (n_51));
  FAX1 g1509(.A (n_18), .B (n_8), .C (n_29), .YC (n_48), .YS (n_49));
  FAX1 g1510(.A (in_13[2]), .B (in_14[2]), .C (n_0), .YC (n_46), .YS
       (n_47));
  FAX1 g1511(.A (in_4[3]), .B (in_8[3]), .C (in_9[3]), .YC (n_44), .YS
       (n_45));
  FAX1 g1512(.A (in_4[2]), .B (in_8[2]), .C (in_9[2]), .YC (n_42), .YS
       (n_43));
  FAX1 g1513(.A (in_11[1]), .B (in_12[1]), .C (in_14[1]), .YC (n_40),
       .YS (n_41));
  FAX1 g1514(.A (in_3[1]), .B (in_7[1]), .C (in_15[1]), .YC (n_38), .YS
       (n_39));
  FAX1 g1515(.A (in_4[1]), .B (in_8[1]), .C (in_9[1]), .YC (n_36), .YS
       (n_37));
  FAX1 g1516(.A (in_3[2]), .B (in_7[2]), .C (in_15[2]), .YC (n_34), .YS
       (n_35));
  FAX1 g1517(.A (in_13[3]), .B (in_14[3]), .C (n_6), .YC (n_32), .YS
       (n_33));
  FAX1 g1518(.A (in_5[0]), .B (in_6[0]), .C (n_3), .YC (n_30), .YS
       (n_31));
  FAX1 g1519(.A (in_3[3]), .B (in_7[3]), .C (in_15[3]), .YC (n_28), .YS
       (n_29));
  FAX1 g1520(.A (in_6[1]), .B (in_13[1]), .C (n_2), .YC (n_26), .YS
       (n_27));
  FAX1 g1521(.A (in_2[3]), .B (in_5[3]), .C (in_10[3]), .YC (n_24), .YS
       (n_25));
  FAX1 g1522(.A (in_2[1]), .B (in_5[1]), .C (in_10[1]), .YC (n_22), .YS
       (n_23));
  FAX1 g1523(.A (in_3[0]), .B (in_11[0]), .C (in_12[0]), .YC (n_20),
       .YS (n_21));
  FAX1 g1524(.A (in_2[2]), .B (in_5[2]), .C (in_10[2]), .YC (n_18), .YS
       (n_19));
  FAX1 g1525(.A (in_6[3]), .B (in_11[3]), .C (in_12[3]), .YC (n_16),
       .YS (n_17));
  FAX1 g1526(.A (in_2[0]), .B (in_4[0]), .C (in_8[0]), .YC (n_14), .YS
       (n_15));
  FAX1 g1527(.A (in_7[0]), .B (in_9[0]), .C (in_10[0]), .YC (n_12), .YS
       (n_13));
  FAX1 g1528(.A (in_1[0]), .B (in_13[0]), .C (in_14[0]), .YC (n_10),
       .YS (n_11));
  FAX1 g1529(.A (in_6[2]), .B (in_11[2]), .C (in_12[2]), .YC (n_8), .YS
       (n_9));
  HAX1 g1530(.A (in_1[2]), .B (in_0[2]), .YC (n_6), .YS (n_7));
  HAX1 g1531(.A (in_1[3]), .B (in_0[3]), .YC (n_4), .YS (n_5));
  HAX1 g1532(.A (in_15[0]), .B (in_0[0]), .YC (n_2), .YS (n_3));
  HAX1 g1533(.A (in_1[1]), .B (in_0[1]), .YC (n_0), .YS (n_1));
endmodule

module counter_WIDTH4_1(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [3:0] out;
  output overflow;
  wire clk, en, rst;
  wire [3:0] out;
  wire overflow;
  wire n_0, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_11, n_12, n_14, n_15, n_16, n_17, n_26, n_27;
  DFFSR \out_reg[3] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_27), .Q
       (n_17));
  DFFSR \out_reg[2] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_12), .Q
       (n_16));
  INVX1 g66(.A (n_11), .Y (n_12));
  MUX2X1 g67(.A (n_9), .B (out[2]), .S (en), .Y (n_11));
  DFFSR \out_reg[1] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_7), .Q
       (n_15));
  HAX1 g70(.A (out[2]), .B (n_4), .YC (n_8), .YS (n_9));
  INVX1 g71(.A (n_6), .Y (n_7));
  MUX2X1 g72(.A (n_5), .B (out[1]), .S (en), .Y (n_6));
  DFFSR \out_reg[0] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_14));
  HAX1 g74(.A (out[1]), .B (out[0]), .YC (n_4), .YS (n_5));
  INVX1 g79(.A (rst), .Y (n_3));
  BUFX2 drc_bufs95(.A (n_17), .Y (out[3]));
  BUFX2 drc_bufs96(.A (n_14), .Y (out[0]));
  BUFX2 drc_bufs97(.A (n_15), .Y (out[1]));
  BUFX2 drc_bufs98(.A (n_16), .Y (out[2]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
  XOR2X1 g103(.A (n_26), .B (out[3]), .Y (n_27));
  AND2X1 g3(.A (n_8), .B (en), .Y (n_26));
endmodule

module counter_WIDTH4_2(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [3:0] out;
  output overflow;
  wire clk, en, rst;
  wire [3:0] out;
  wire overflow;
  wire n_0, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_11, n_12, n_14, n_15, n_16, n_17, n_26, n_27;
  DFFSR \out_reg[3] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_27), .Q
       (n_17));
  DFFSR \out_reg[2] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_12), .Q
       (n_16));
  INVX1 g66(.A (n_11), .Y (n_12));
  MUX2X1 g67(.A (n_9), .B (out[2]), .S (en), .Y (n_11));
  DFFSR \out_reg[1] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_7), .Q
       (n_15));
  HAX1 g70(.A (out[2]), .B (n_4), .YC (n_8), .YS (n_9));
  INVX1 g71(.A (n_6), .Y (n_7));
  MUX2X1 g72(.A (n_5), .B (out[1]), .S (en), .Y (n_6));
  DFFSR \out_reg[0] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_14));
  HAX1 g74(.A (out[1]), .B (out[0]), .YC (n_4), .YS (n_5));
  INVX1 g79(.A (rst), .Y (n_3));
  BUFX2 drc_bufs95(.A (n_17), .Y (out[3]));
  BUFX2 drc_bufs96(.A (n_14), .Y (out[0]));
  BUFX2 drc_bufs97(.A (n_15), .Y (out[1]));
  BUFX2 drc_bufs98(.A (n_16), .Y (out[2]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
  XOR2X1 g103(.A (n_26), .B (out[3]), .Y (n_27));
  AND2X1 g3(.A (n_8), .B (en), .Y (n_26));
endmodule

module counter_WIDTH4_11(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [3:0] out;
  output overflow;
  wire clk, en, rst;
  wire [3:0] out;
  wire overflow;
  wire n_0, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_11, n_12, n_14, n_15, n_16, n_17, n_26, n_27;
  DFFSR \out_reg[3] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_27), .Q
       (n_17));
  DFFSR \out_reg[2] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_12), .Q
       (n_16));
  INVX1 g66(.A (n_11), .Y (n_12));
  MUX2X1 g67(.A (n_9), .B (out[2]), .S (en), .Y (n_11));
  DFFSR \out_reg[1] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_7), .Q
       (n_15));
  HAX1 g70(.A (out[2]), .B (n_4), .YC (n_8), .YS (n_9));
  INVX1 g71(.A (n_6), .Y (n_7));
  MUX2X1 g72(.A (n_5), .B (out[1]), .S (en), .Y (n_6));
  DFFSR \out_reg[0] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_14));
  HAX1 g74(.A (out[1]), .B (out[0]), .YC (n_4), .YS (n_5));
  INVX1 g79(.A (rst), .Y (n_3));
  BUFX2 drc_bufs95(.A (n_17), .Y (out[3]));
  BUFX2 drc_bufs96(.A (n_14), .Y (out[0]));
  BUFX2 drc_bufs97(.A (n_15), .Y (out[1]));
  BUFX2 drc_bufs98(.A (n_16), .Y (out[2]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
  XOR2X1 g103(.A (n_26), .B (out[3]), .Y (n_27));
  AND2X1 g3(.A (n_8), .B (en), .Y (n_26));
endmodule

module counter_WIDTH4_12(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [3:0] out;
  output overflow;
  wire clk, en, rst;
  wire [3:0] out;
  wire overflow;
  wire n_0, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_11, n_12, n_14, n_15, n_16, n_17, n_26, n_27;
  DFFSR \out_reg[3] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_27), .Q
       (n_17));
  DFFSR \out_reg[2] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_12), .Q
       (n_16));
  INVX1 g66(.A (n_11), .Y (n_12));
  MUX2X1 g67(.A (n_9), .B (out[2]), .S (en), .Y (n_11));
  DFFSR \out_reg[1] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_7), .Q
       (n_15));
  HAX1 g70(.A (out[2]), .B (n_4), .YC (n_8), .YS (n_9));
  INVX1 g71(.A (n_6), .Y (n_7));
  MUX2X1 g72(.A (n_5), .B (out[1]), .S (en), .Y (n_6));
  DFFSR \out_reg[0] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_14));
  HAX1 g74(.A (out[1]), .B (out[0]), .YC (n_4), .YS (n_5));
  INVX1 g79(.A (rst), .Y (n_3));
  BUFX2 drc_bufs95(.A (n_17), .Y (out[3]));
  BUFX2 drc_bufs96(.A (n_14), .Y (out[0]));
  BUFX2 drc_bufs97(.A (n_15), .Y (out[1]));
  BUFX2 drc_bufs98(.A (n_16), .Y (out[2]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
  XOR2X1 g103(.A (n_26), .B (out[3]), .Y (n_27));
  AND2X1 g3(.A (n_8), .B (en), .Y (n_26));
endmodule

module counter_WIDTH4_13(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [3:0] out;
  output overflow;
  wire clk, en, rst;
  wire [3:0] out;
  wire overflow;
  wire n_0, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_11, n_12, n_14, n_15, n_16, n_17, n_26, n_27;
  DFFSR \out_reg[3] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_27), .Q
       (n_17));
  DFFSR \out_reg[2] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_12), .Q
       (n_16));
  INVX1 g66(.A (n_11), .Y (n_12));
  MUX2X1 g67(.A (n_9), .B (out[2]), .S (en), .Y (n_11));
  DFFSR \out_reg[1] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_7), .Q
       (n_15));
  HAX1 g70(.A (out[2]), .B (n_4), .YC (n_8), .YS (n_9));
  INVX1 g71(.A (n_6), .Y (n_7));
  MUX2X1 g72(.A (n_5), .B (out[1]), .S (en), .Y (n_6));
  DFFSR \out_reg[0] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_14));
  HAX1 g74(.A (out[1]), .B (out[0]), .YC (n_4), .YS (n_5));
  INVX1 g79(.A (rst), .Y (n_3));
  BUFX2 drc_bufs95(.A (n_17), .Y (out[3]));
  BUFX2 drc_bufs96(.A (n_14), .Y (out[0]));
  BUFX2 drc_bufs97(.A (n_15), .Y (out[1]));
  BUFX2 drc_bufs98(.A (n_16), .Y (out[2]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
  XOR2X1 g103(.A (n_26), .B (out[3]), .Y (n_27));
  AND2X1 g3(.A (n_8), .B (en), .Y (n_26));
endmodule

module counter_WIDTH4_14(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [3:0] out;
  output overflow;
  wire clk, en, rst;
  wire [3:0] out;
  wire overflow;
  wire n_0, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_11, n_12, n_14, n_15, n_16, n_17, n_26, n_27;
  DFFSR \out_reg[3] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_27), .Q
       (n_17));
  DFFSR \out_reg[2] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_12), .Q
       (n_16));
  INVX1 g66(.A (n_11), .Y (n_12));
  MUX2X1 g67(.A (n_9), .B (out[2]), .S (en), .Y (n_11));
  DFFSR \out_reg[1] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_7), .Q
       (n_15));
  HAX1 g70(.A (out[2]), .B (n_4), .YC (n_8), .YS (n_9));
  INVX1 g71(.A (n_6), .Y (n_7));
  MUX2X1 g72(.A (n_5), .B (out[1]), .S (en), .Y (n_6));
  DFFSR \out_reg[0] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_14));
  HAX1 g74(.A (out[1]), .B (out[0]), .YC (n_4), .YS (n_5));
  INVX1 g79(.A (rst), .Y (n_3));
  BUFX2 drc_bufs95(.A (n_17), .Y (out[3]));
  BUFX2 drc_bufs96(.A (n_14), .Y (out[0]));
  BUFX2 drc_bufs97(.A (n_15), .Y (out[1]));
  BUFX2 drc_bufs98(.A (n_16), .Y (out[2]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
  XOR2X1 g103(.A (n_26), .B (out[3]), .Y (n_27));
  AND2X1 g3(.A (n_8), .B (en), .Y (n_26));
endmodule

module counter_WIDTH4_15(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [3:0] out;
  output overflow;
  wire clk, en, rst;
  wire [3:0] out;
  wire overflow;
  wire n_0, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_11, n_12, n_14, n_15, n_16, n_17, n_26, n_27;
  DFFSR \out_reg[3] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_27), .Q
       (n_17));
  DFFSR \out_reg[2] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_12), .Q
       (n_16));
  INVX1 g66(.A (n_11), .Y (n_12));
  MUX2X1 g67(.A (n_9), .B (out[2]), .S (en), .Y (n_11));
  DFFSR \out_reg[1] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_7), .Q
       (n_15));
  HAX1 g70(.A (out[2]), .B (n_4), .YC (n_8), .YS (n_9));
  INVX1 g71(.A (n_6), .Y (n_7));
  MUX2X1 g72(.A (n_5), .B (out[1]), .S (en), .Y (n_6));
  DFFSR \out_reg[0] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_14));
  HAX1 g74(.A (out[1]), .B (out[0]), .YC (n_4), .YS (n_5));
  INVX1 g79(.A (rst), .Y (n_3));
  BUFX2 drc_bufs95(.A (n_17), .Y (out[3]));
  BUFX2 drc_bufs96(.A (n_14), .Y (out[0]));
  BUFX2 drc_bufs97(.A (n_15), .Y (out[1]));
  BUFX2 drc_bufs98(.A (n_16), .Y (out[2]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
  XOR2X1 g103(.A (n_26), .B (out[3]), .Y (n_27));
  AND2X1 g3(.A (n_8), .B (en), .Y (n_26));
endmodule

module counter_WIDTH4_16(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [3:0] out;
  output overflow;
  wire clk, en, rst;
  wire [3:0] out;
  wire overflow;
  wire n_0, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_11, n_12, n_14, n_15, n_16, n_17, n_26, n_27;
  DFFSR \out_reg[3] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_27), .Q
       (n_17));
  DFFSR \out_reg[2] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_12), .Q
       (n_16));
  INVX1 g66(.A (n_11), .Y (n_12));
  MUX2X1 g67(.A (n_9), .B (out[2]), .S (en), .Y (n_11));
  DFFSR \out_reg[1] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_7), .Q
       (n_15));
  HAX1 g70(.A (out[2]), .B (n_4), .YC (n_8), .YS (n_9));
  INVX1 g71(.A (n_6), .Y (n_7));
  MUX2X1 g72(.A (n_5), .B (out[1]), .S (en), .Y (n_6));
  DFFSR \out_reg[0] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_14));
  HAX1 g74(.A (out[1]), .B (out[0]), .YC (n_4), .YS (n_5));
  INVX1 g79(.A (rst), .Y (n_3));
  BUFX2 drc_bufs95(.A (n_17), .Y (out[3]));
  BUFX2 drc_bufs96(.A (n_14), .Y (out[0]));
  BUFX2 drc_bufs97(.A (n_15), .Y (out[1]));
  BUFX2 drc_bufs98(.A (n_16), .Y (out[2]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
  XOR2X1 g103(.A (n_26), .B (out[3]), .Y (n_27));
  AND2X1 g3(.A (n_8), .B (en), .Y (n_26));
endmodule

module counter_WIDTH4_3(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [3:0] out;
  output overflow;
  wire clk, en, rst;
  wire [3:0] out;
  wire overflow;
  wire n_0, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_11, n_12, n_14, n_15, n_16, n_17, n_26, n_27;
  DFFSR \out_reg[3] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_27), .Q
       (n_17));
  DFFSR \out_reg[2] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_12), .Q
       (n_16));
  INVX1 g66(.A (n_11), .Y (n_12));
  MUX2X1 g67(.A (n_9), .B (out[2]), .S (en), .Y (n_11));
  DFFSR \out_reg[1] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_7), .Q
       (n_15));
  HAX1 g70(.A (out[2]), .B (n_4), .YC (n_8), .YS (n_9));
  INVX1 g71(.A (n_6), .Y (n_7));
  MUX2X1 g72(.A (n_5), .B (out[1]), .S (en), .Y (n_6));
  DFFSR \out_reg[0] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_14));
  HAX1 g74(.A (out[1]), .B (out[0]), .YC (n_4), .YS (n_5));
  INVX1 g79(.A (rst), .Y (n_3));
  BUFX2 drc_bufs95(.A (n_17), .Y (out[3]));
  BUFX2 drc_bufs96(.A (n_14), .Y (out[0]));
  BUFX2 drc_bufs97(.A (n_15), .Y (out[1]));
  BUFX2 drc_bufs98(.A (n_16), .Y (out[2]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
  XOR2X1 g103(.A (n_26), .B (out[3]), .Y (n_27));
  AND2X1 g3(.A (n_8), .B (en), .Y (n_26));
endmodule

module counter_WIDTH4_4(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [3:0] out;
  output overflow;
  wire clk, en, rst;
  wire [3:0] out;
  wire overflow;
  wire n_0, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_11, n_12, n_14, n_15, n_16, n_17, n_26, n_27;
  DFFSR \out_reg[3] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_27), .Q
       (n_17));
  DFFSR \out_reg[2] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_12), .Q
       (n_16));
  INVX1 g66(.A (n_11), .Y (n_12));
  MUX2X1 g67(.A (n_9), .B (out[2]), .S (en), .Y (n_11));
  DFFSR \out_reg[1] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_7), .Q
       (n_15));
  HAX1 g70(.A (out[2]), .B (n_4), .YC (n_8), .YS (n_9));
  INVX1 g71(.A (n_6), .Y (n_7));
  MUX2X1 g72(.A (n_5), .B (out[1]), .S (en), .Y (n_6));
  DFFSR \out_reg[0] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_14));
  HAX1 g74(.A (out[1]), .B (out[0]), .YC (n_4), .YS (n_5));
  INVX1 g79(.A (rst), .Y (n_3));
  BUFX2 drc_bufs95(.A (n_17), .Y (out[3]));
  BUFX2 drc_bufs96(.A (n_14), .Y (out[0]));
  BUFX2 drc_bufs97(.A (n_15), .Y (out[1]));
  BUFX2 drc_bufs98(.A (n_16), .Y (out[2]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
  XOR2X1 g103(.A (n_26), .B (out[3]), .Y (n_27));
  AND2X1 g3(.A (n_8), .B (en), .Y (n_26));
endmodule

module counter_WIDTH4_5(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [3:0] out;
  output overflow;
  wire clk, en, rst;
  wire [3:0] out;
  wire overflow;
  wire n_0, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_11, n_12, n_14, n_15, n_16, n_17, n_26, n_27;
  DFFSR \out_reg[3] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_27), .Q
       (n_17));
  DFFSR \out_reg[2] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_12), .Q
       (n_16));
  INVX1 g66(.A (n_11), .Y (n_12));
  MUX2X1 g67(.A (n_9), .B (out[2]), .S (en), .Y (n_11));
  DFFSR \out_reg[1] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_7), .Q
       (n_15));
  HAX1 g70(.A (out[2]), .B (n_4), .YC (n_8), .YS (n_9));
  INVX1 g71(.A (n_6), .Y (n_7));
  MUX2X1 g72(.A (n_5), .B (out[1]), .S (en), .Y (n_6));
  DFFSR \out_reg[0] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_14));
  HAX1 g74(.A (out[1]), .B (out[0]), .YC (n_4), .YS (n_5));
  INVX1 g79(.A (rst), .Y (n_3));
  BUFX2 drc_bufs95(.A (n_17), .Y (out[3]));
  BUFX2 drc_bufs96(.A (n_14), .Y (out[0]));
  BUFX2 drc_bufs97(.A (n_15), .Y (out[1]));
  BUFX2 drc_bufs98(.A (n_16), .Y (out[2]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
  XOR2X1 g103(.A (n_26), .B (out[3]), .Y (n_27));
  AND2X1 g3(.A (n_8), .B (en), .Y (n_26));
endmodule

module counter_WIDTH4_6(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [3:0] out;
  output overflow;
  wire clk, en, rst;
  wire [3:0] out;
  wire overflow;
  wire n_0, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_11, n_12, n_14, n_15, n_16, n_17, n_26, n_27;
  DFFSR \out_reg[3] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_27), .Q
       (n_17));
  DFFSR \out_reg[2] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_12), .Q
       (n_16));
  INVX1 g66(.A (n_11), .Y (n_12));
  MUX2X1 g67(.A (n_9), .B (out[2]), .S (en), .Y (n_11));
  DFFSR \out_reg[1] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_7), .Q
       (n_15));
  HAX1 g70(.A (out[2]), .B (n_4), .YC (n_8), .YS (n_9));
  INVX1 g71(.A (n_6), .Y (n_7));
  MUX2X1 g72(.A (n_5), .B (out[1]), .S (en), .Y (n_6));
  DFFSR \out_reg[0] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_14));
  HAX1 g74(.A (out[1]), .B (out[0]), .YC (n_4), .YS (n_5));
  INVX1 g79(.A (rst), .Y (n_3));
  BUFX2 drc_bufs95(.A (n_17), .Y (out[3]));
  BUFX2 drc_bufs96(.A (n_14), .Y (out[0]));
  BUFX2 drc_bufs97(.A (n_15), .Y (out[1]));
  BUFX2 drc_bufs98(.A (n_16), .Y (out[2]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
  XOR2X1 g103(.A (n_26), .B (out[3]), .Y (n_27));
  AND2X1 g3(.A (n_8), .B (en), .Y (n_26));
endmodule

module counter_WIDTH4_7(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [3:0] out;
  output overflow;
  wire clk, en, rst;
  wire [3:0] out;
  wire overflow;
  wire n_0, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_11, n_12, n_14, n_15, n_16, n_17, n_26, n_27;
  DFFSR \out_reg[3] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_27), .Q
       (n_17));
  DFFSR \out_reg[2] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_12), .Q
       (n_16));
  INVX1 g66(.A (n_11), .Y (n_12));
  MUX2X1 g67(.A (n_9), .B (out[2]), .S (en), .Y (n_11));
  DFFSR \out_reg[1] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_7), .Q
       (n_15));
  HAX1 g70(.A (out[2]), .B (n_4), .YC (n_8), .YS (n_9));
  INVX1 g71(.A (n_6), .Y (n_7));
  MUX2X1 g72(.A (n_5), .B (out[1]), .S (en), .Y (n_6));
  DFFSR \out_reg[0] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_14));
  HAX1 g74(.A (out[1]), .B (out[0]), .YC (n_4), .YS (n_5));
  INVX1 g79(.A (rst), .Y (n_3));
  BUFX2 drc_bufs95(.A (n_17), .Y (out[3]));
  BUFX2 drc_bufs96(.A (n_14), .Y (out[0]));
  BUFX2 drc_bufs97(.A (n_15), .Y (out[1]));
  BUFX2 drc_bufs98(.A (n_16), .Y (out[2]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
  XOR2X1 g103(.A (n_26), .B (out[3]), .Y (n_27));
  AND2X1 g3(.A (n_8), .B (en), .Y (n_26));
endmodule

module counter_WIDTH4_8(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [3:0] out;
  output overflow;
  wire clk, en, rst;
  wire [3:0] out;
  wire overflow;
  wire n_0, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_11, n_12, n_14, n_15, n_16, n_17, n_26, n_27;
  DFFSR \out_reg[3] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_27), .Q
       (n_17));
  DFFSR \out_reg[2] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_12), .Q
       (n_16));
  INVX1 g66(.A (n_11), .Y (n_12));
  MUX2X1 g67(.A (n_9), .B (out[2]), .S (en), .Y (n_11));
  DFFSR \out_reg[1] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_7), .Q
       (n_15));
  HAX1 g70(.A (out[2]), .B (n_4), .YC (n_8), .YS (n_9));
  INVX1 g71(.A (n_6), .Y (n_7));
  MUX2X1 g72(.A (n_5), .B (out[1]), .S (en), .Y (n_6));
  DFFSR \out_reg[0] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_14));
  HAX1 g74(.A (out[1]), .B (out[0]), .YC (n_4), .YS (n_5));
  INVX1 g79(.A (rst), .Y (n_3));
  BUFX2 drc_bufs95(.A (n_17), .Y (out[3]));
  BUFX2 drc_bufs96(.A (n_14), .Y (out[0]));
  BUFX2 drc_bufs97(.A (n_15), .Y (out[1]));
  BUFX2 drc_bufs98(.A (n_16), .Y (out[2]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
  XOR2X1 g103(.A (n_26), .B (out[3]), .Y (n_27));
  AND2X1 g3(.A (n_8), .B (en), .Y (n_26));
endmodule

module counter_WIDTH4_9(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [3:0] out;
  output overflow;
  wire clk, en, rst;
  wire [3:0] out;
  wire overflow;
  wire n_0, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_11, n_12, n_14, n_15, n_16, n_17, n_26, n_27;
  DFFSR \out_reg[3] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_27), .Q
       (n_17));
  DFFSR \out_reg[2] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_12), .Q
       (n_16));
  INVX1 g66(.A (n_11), .Y (n_12));
  MUX2X1 g67(.A (n_9), .B (out[2]), .S (en), .Y (n_11));
  DFFSR \out_reg[1] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_7), .Q
       (n_15));
  HAX1 g70(.A (out[2]), .B (n_4), .YC (n_8), .YS (n_9));
  INVX1 g71(.A (n_6), .Y (n_7));
  MUX2X1 g72(.A (n_5), .B (out[1]), .S (en), .Y (n_6));
  DFFSR \out_reg[0] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_14));
  HAX1 g74(.A (out[1]), .B (out[0]), .YC (n_4), .YS (n_5));
  INVX1 g79(.A (rst), .Y (n_3));
  BUFX2 drc_bufs95(.A (n_17), .Y (out[3]));
  BUFX2 drc_bufs96(.A (n_14), .Y (out[0]));
  BUFX2 drc_bufs97(.A (n_15), .Y (out[1]));
  BUFX2 drc_bufs98(.A (n_16), .Y (out[2]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
  XOR2X1 g103(.A (n_26), .B (out[3]), .Y (n_27));
  AND2X1 g3(.A (n_8), .B (en), .Y (n_26));
endmodule

module counter_WIDTH4_10(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [3:0] out;
  output overflow;
  wire clk, en, rst;
  wire [3:0] out;
  wire overflow;
  wire n_0, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_11, n_12, n_14, n_15, n_16, n_17, n_26, n_27;
  DFFSR \out_reg[3] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_27), .Q
       (n_17));
  DFFSR \out_reg[2] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_12), .Q
       (n_16));
  INVX1 g66(.A (n_11), .Y (n_12));
  MUX2X1 g67(.A (n_9), .B (out[2]), .S (en), .Y (n_11));
  DFFSR \out_reg[1] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_7), .Q
       (n_15));
  HAX1 g70(.A (out[2]), .B (n_4), .YC (n_8), .YS (n_9));
  INVX1 g71(.A (n_6), .Y (n_7));
  MUX2X1 g72(.A (n_5), .B (out[1]), .S (en), .Y (n_6));
  DFFSR \out_reg[0] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_14));
  HAX1 g74(.A (out[1]), .B (out[0]), .YC (n_4), .YS (n_5));
  INVX1 g79(.A (rst), .Y (n_3));
  BUFX2 drc_bufs95(.A (n_17), .Y (out[3]));
  BUFX2 drc_bufs96(.A (n_14), .Y (out[0]));
  BUFX2 drc_bufs97(.A (n_15), .Y (out[1]));
  BUFX2 drc_bufs98(.A (n_16), .Y (out[2]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
  XOR2X1 g103(.A (n_26), .B (out[3]), .Y (n_27));
  AND2X1 g3(.A (n_8), .B (en), .Y (n_26));
endmodule

module ctr_out_bank(clk, rst, mul_in, bin_out);
  input clk, rst;
  input [15:0] mul_in;
  output [31:0] bin_out;
  wire clk, rst;
  wire [15:0] mul_in;
  wire [31:0] bin_out;
  wire [3:0] ctr15;
  wire [3:0] ctr14;
  wire [3:0] ctr13;
  wire [3:0] ctr12;
  wire [3:0] ctr11;
  wire [3:0] ctr10;
  wire [3:0] ctr9;
  wire [3:0] ctr8;
  wire [3:0] ctr7;
  wire [3:0] ctr6;
  wire [3:0] ctr5;
  wire [3:0] ctr4;
  wire [3:0] ctr3;
  wire [3:0] ctr2;
  wire [3:0] ctr0;
  wire [3:0] ctr1;
  wire [15:0] unused;
  csa_tree_add_469_129_group_97 csa_tree_add_469_129_groupi(.in_0
       (ctr15), .in_1 (ctr14), .in_2 (ctr13), .in_3 (ctr12), .in_4
       (ctr11), .in_5 (ctr10), .in_6 (ctr9), .in_7 (ctr8), .in_8
       (ctr7), .in_9 (ctr6), .in_10 (ctr5), .in_11 (ctr4), .in_12
       (ctr3), .in_13 (ctr2), .in_14 (ctr0), .in_15 (ctr1), .out_0
       (bin_out[7:0]));
  counter_WIDTH4_1 stoch2bin_0(.out (ctr0), .clk (clk), .en
       (mul_in[0]), .rst (rst), .overflow (unused[0]));
  counter_WIDTH4_2 stoch2bin_1(.out (ctr1), .clk (clk), .en
       (mul_in[1]), .rst (rst), .overflow (unused[1]));
  counter_WIDTH4_11 stoch2bin_10(.out (ctr10), .clk (clk), .en
       (mul_in[10]), .rst (rst), .overflow (unused[10]));
  counter_WIDTH4_12 stoch2bin_11(.out (ctr11), .clk (clk), .en
       (mul_in[11]), .rst (rst), .overflow (unused[11]));
  counter_WIDTH4_13 stoch2bin_12(.out (ctr12), .clk (clk), .en
       (mul_in[12]), .rst (rst), .overflow (unused[12]));
  counter_WIDTH4_14 stoch2bin_13(.out (ctr13), .clk (clk), .en
       (mul_in[13]), .rst (rst), .overflow (unused[13]));
  counter_WIDTH4_15 stoch2bin_14(.out (ctr14), .clk (clk), .en
       (mul_in[14]), .rst (rst), .overflow (unused[14]));
  counter_WIDTH4_16 stoch2bin_15(.out (ctr15), .clk (clk), .en
       (mul_in[15]), .rst (rst), .overflow (unused[15]));
  counter_WIDTH4_3 stoch2bin_2(.out (ctr2), .clk (clk), .en
       (mul_in[2]), .rst (rst), .overflow (unused[2]));
  counter_WIDTH4_4 stoch2bin_3(.out (ctr3), .clk (clk), .en
       (mul_in[3]), .rst (rst), .overflow (unused[3]));
  counter_WIDTH4_5 stoch2bin_4(.out (ctr4), .clk (clk), .en
       (mul_in[4]), .rst (rst), .overflow (unused[4]));
  counter_WIDTH4_6 stoch2bin_5(.out (ctr5), .clk (clk), .en
       (mul_in[5]), .rst (rst), .overflow (unused[5]));
  counter_WIDTH4_7 stoch2bin_6(.out (ctr6), .clk (clk), .en
       (mul_in[6]), .rst (rst), .overflow (unused[6]));
  counter_WIDTH4_8 stoch2bin_7(.out (ctr7), .clk (clk), .en
       (mul_in[7]), .rst (rst), .overflow (unused[7]));
  counter_WIDTH4_9 stoch2bin_8(.out (ctr8), .clk (clk), .en
       (mul_in[8]), .rst (rst), .overflow (unused[8]));
  counter_WIDTH4_10 stoch2bin_9(.out (ctr9), .clk (clk), .en
       (mul_in[9]), .rst (rst), .overflow (unused[9]));
endmodule

module pipe_mul_16b(a, b, y);
  input [15:0] a, b;
  output [15:0] y;
  wire [15:0] a, b;
  wire [15:0] y;
  AND2X1 g113(.A (b[15]), .B (a[15]), .Y (y[15]));
  AND2X1 g114(.A (b[14]), .B (a[14]), .Y (y[14]));
  AND2X1 g115(.A (b[10]), .B (a[10]), .Y (y[10]));
  AND2X1 g116(.A (b[4]), .B (a[4]), .Y (y[4]));
  AND2X1 g117(.A (b[9]), .B (a[9]), .Y (y[9]));
  AND2X1 g118(.A (b[3]), .B (a[3]), .Y (y[3]));
  AND2X1 g119(.A (b[12]), .B (a[12]), .Y (y[12]));
  AND2X1 g120(.A (b[2]), .B (a[2]), .Y (y[2]));
  AND2X1 g121(.A (b[1]), .B (a[1]), .Y (y[1]));
  AND2X1 g122(.A (b[8]), .B (a[8]), .Y (y[8]));
  AND2X1 g123(.A (b[0]), .B (a[0]), .Y (y[0]));
  AND2X1 g124(.A (b[13]), .B (a[13]), .Y (y[13]));
  AND2X1 g125(.A (b[11]), .B (a[11]), .Y (y[11]));
  AND2X1 g126(.A (b[7]), .B (a[7]), .Y (y[7]));
  AND2X1 g127(.A (b[6]), .B (a[6]), .Y (y[6]));
  AND2X1 g128(.A (b[5]), .B (a[5]), .Y (y[5]));
endmodule

module comp_1b(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_1;
  AND2X1 g14(.A (n_1), .B (a), .Y (a_larger));
  INVX1 g15(.A (b), .Y (n_1));
endmodule

module comp_1b_1(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_2(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_3(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_4b(a_gt_b, a, b);
  input [3:0] a, b;
  output a_gt_b;
  wire [3:0] a, b;
  wire a_gt_b;
  wire UNCONNECTED, agt, agt_9, agt_11, agt_16, e, e_13, e_19;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  comp_1b comp0(.a (a[0]), .b (b[0]), .equal (UNCONNECTED), .a_larger
       (agt_16));
  comp_1b_1 comp1(.a (a[1]), .b (b[1]), .equal (e_19), .a_larger
       (agt_11));
  comp_1b_2 comp2(.a (a[2]), .b (b[2]), .equal (e_13), .a_larger (agt));
  comp_1b_3 comp3(.a (a[3]), .b (b[3]), .equal (e), .a_larger (agt_9));
  INVX1 g13(.A (e), .Y (n_6));
  INVX1 g12(.A (agt_9), .Y (n_5));
  OAI21X1 g73(.A (n_6), .B (n_1), .C (n_5), .Y (a_gt_b));
  AOI21X1 g74(.A (e_13), .B (n_3), .C (agt), .Y (n_4));
  INVX1 g75(.A (n_0), .Y (n_3));
  AOI21X1 g76(.A (agt_16), .B (e_19), .C (agt_11), .Y (n_2));
  BUFX2 drc_bufs(.A (n_4), .Y (n_1));
  BUFX2 drc_bufs77(.A (n_2), .Y (n_0));
endmodule

module counter_WIDTH4(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [3:0] out;
  output overflow;
  wire clk, en, rst;
  wire [3:0] out;
  wire overflow;
  wire n_0, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_11, n_12, n_14, n_15, n_16, n_17, n_26, n_27;
  DFFSR \out_reg[3] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_27), .Q
       (n_17));
  DFFSR \out_reg[2] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_12), .Q
       (n_16));
  INVX1 g66(.A (n_11), .Y (n_12));
  MUX2X1 g67(.A (n_9), .B (out[2]), .S (en), .Y (n_11));
  DFFSR \out_reg[1] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_7), .Q
       (n_15));
  HAX1 g70(.A (out[2]), .B (n_4), .YC (n_8), .YS (n_9));
  INVX1 g71(.A (n_6), .Y (n_7));
  MUX2X1 g72(.A (n_5), .B (out[1]), .S (en), .Y (n_6));
  DFFSR \out_reg[0] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_14));
  HAX1 g74(.A (out[1]), .B (out[0]), .YC (n_4), .YS (n_5));
  INVX1 g79(.A (rst), .Y (n_3));
  BUFX2 drc_bufs95(.A (n_17), .Y (out[3]));
  BUFX2 drc_bufs96(.A (n_14), .Y (out[0]));
  BUFX2 drc_bufs97(.A (n_15), .Y (out[1]));
  BUFX2 drc_bufs98(.A (n_16), .Y (out[2]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
  XOR2X1 g103(.A (n_26), .B (out[3]), .Y (n_27));
  AND2X1 g3(.A (n_8), .B (en), .Y (n_26));
endmodule

module prg_4b(clk, rst, en, bin_in, sn_out, ctr_overflow);
  input clk, rst, en;
  input [3:0] bin_in;
  output sn_out, ctr_overflow;
  wire clk, rst, en;
  wire [3:0] bin_in;
  wire sn_out, ctr_overflow;
  wire [3:0] ctr4_out;
  wire n_1;
  comp_4b comp4(.a_gt_b (sn_out), .a (bin_in), .b (ctr4_out));
  counter_WIDTH4 ctr4(.out (ctr4_out), .clk (clk), .en (en), .rst
       (rst), .overflow (n_1));
endmodule

module comp_1b_4(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_1;
  AND2X1 g14(.A (n_1), .B (a), .Y (a_larger));
  INVX1 g15(.A (b), .Y (n_1));
endmodule

module comp_1b_5(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_6(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_7(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_4b_1(a_gt_b, a, b);
  input [3:0] a, b;
  output a_gt_b;
  wire [3:0] a, b;
  wire a_gt_b;
  wire UNCONNECTED0, agt, agt_9, agt_11, agt_16, e, e_13, e_19;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  comp_1b_4 comp0(.a (a[0]), .b (b[0]), .equal (UNCONNECTED0),
       .a_larger (agt_16));
  comp_1b_5 comp1(.a (a[1]), .b (b[1]), .equal (e_19), .a_larger
       (agt_11));
  comp_1b_6 comp2(.a (a[2]), .b (b[2]), .equal (e_13), .a_larger (agt));
  comp_1b_7 comp3(.a (a[3]), .b (b[3]), .equal (e), .a_larger (agt_9));
  INVX1 g12(.A (e), .Y (n_6));
  INVX1 g13(.A (agt_9), .Y (n_5));
  OAI21X1 g73(.A (n_6), .B (n_1), .C (n_5), .Y (a_gt_b));
  AOI21X1 g74(.A (e_13), .B (n_3), .C (agt), .Y (n_4));
  INVX1 g75(.A (n_0), .Y (n_3));
  AOI21X1 g76(.A (agt_16), .B (e_19), .C (agt_11), .Y (n_2));
  BUFX2 drc_bufs(.A (n_4), .Y (n_1));
  BUFX2 drc_bufs77(.A (n_2), .Y (n_0));
endmodule

module counter_WIDTH4_17(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [3:0] out;
  output overflow;
  wire clk, en, rst;
  wire [3:0] out;
  wire overflow;
  wire n_0, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_11, n_12, n_14, n_15, n_16, n_17, n_26, n_27;
  DFFSR \out_reg[3] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_27), .Q
       (n_17));
  DFFSR \out_reg[2] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_12), .Q
       (n_16));
  INVX1 g66(.A (n_11), .Y (n_12));
  MUX2X1 g67(.A (n_9), .B (out[2]), .S (en), .Y (n_11));
  DFFSR \out_reg[1] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_7), .Q
       (n_15));
  HAX1 g70(.A (out[2]), .B (n_4), .YC (n_8), .YS (n_9));
  INVX1 g71(.A (n_6), .Y (n_7));
  MUX2X1 g72(.A (n_5), .B (out[1]), .S (en), .Y (n_6));
  DFFSR \out_reg[0] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_14));
  HAX1 g74(.A (out[1]), .B (out[0]), .YC (n_4), .YS (n_5));
  INVX1 g79(.A (rst), .Y (n_3));
  BUFX2 drc_bufs95(.A (n_17), .Y (out[3]));
  BUFX2 drc_bufs96(.A (n_14), .Y (out[0]));
  BUFX2 drc_bufs97(.A (n_15), .Y (out[1]));
  BUFX2 drc_bufs98(.A (n_16), .Y (out[2]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
  XOR2X1 g103(.A (n_26), .B (out[3]), .Y (n_27));
  AND2X1 g3(.A (n_8), .B (en), .Y (n_26));
endmodule

module prg_4b_1(clk, rst, en, bin_in, sn_out, ctr_overflow);
  input clk, rst, en;
  input [3:0] bin_in;
  output sn_out, ctr_overflow;
  wire clk, rst, en;
  wire [3:0] bin_in;
  wire sn_out, ctr_overflow;
  wire [3:0] ctr4_out;
  wire n_1;
  comp_4b_1 comp4(.a_gt_b (sn_out), .a (bin_in), .b (ctr4_out));
  counter_WIDTH4_17 ctr4(.out (ctr4_out), .clk (clk), .en (en), .rst
       (rst), .overflow (n_1));
endmodule

module shift_reg_16b_noshift(clk, scan_in, en, rst, shiftreg_out);
  input clk, scan_in, en, rst;
  output [15:0] shiftreg_out;
  wire clk, scan_in, en, rst;
  wire [15:0] shiftreg_out;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_51, n_52, n_53, n_54, n_55, n_56, n_57;
  wire n_58, n_59, n_60, n_61, n_62, n_63, n_64, n_65;
  wire n_69;
  DFFSR \shiftreg_reg[0] (.R (n_17), .S (1'b1), .CLK (clk), .D (n_29),
       .Q (n_65));
  DFFSR \shiftreg_reg[11] (.R (n_17), .S (1'b1), .CLK (clk), .D (n_27),
       .Q (n_54));
  DFFSR \shiftreg_reg[12] (.R (n_17), .S (1'b1), .CLK (clk), .D (n_47),
       .Q (n_53));
  DFFSR \shiftreg_reg[4] (.R (n_17), .S (1'b1), .CLK (clk), .D (n_26),
       .Q (n_61));
  DFFSR \shiftreg_reg[5] (.R (n_17), .S (1'b1), .CLK (clk), .D (n_49),
       .Q (n_60));
  DFFSR \shiftreg_reg[6] (.R (n_17), .S (1'b1), .CLK (clk), .D (n_48),
       .Q (n_59));
  DFFSR \shiftreg_reg[7] (.R (n_17), .S (1'b1), .CLK (clk), .D (n_46),
       .Q (n_58));
  DFFSR \shiftreg_reg[13] (.R (n_17), .S (1'b1), .CLK (clk), .D (n_45),
       .Q (n_52));
  DFFSR \shiftreg_reg[8] (.R (n_17), .S (1'b1), .CLK (clk), .D (n_44),
       .Q (n_57));
  DFFSR \shiftreg_reg[9] (.R (n_17), .S (1'b1), .CLK (clk), .D (n_42),
       .Q (n_56));
  DFFSR \shiftreg_reg[14] (.R (n_17), .S (1'b1), .CLK (clk), .D (n_43),
       .Q (n_51));
  DFFSR \shiftreg_reg[10] (.R (n_17), .S (1'b1), .CLK (clk), .D (n_32),
       .Q (n_55));
  DFFSR \shiftreg_reg[15] (.R (n_17), .S (1'b1), .CLK (clk), .D (n_33),
       .Q (n_69));
  DFFSR \shiftreg_reg[1] (.R (n_17), .S (1'b1), .CLK (clk), .D (n_31),
       .Q (n_64));
  DFFSR \shiftreg_reg[2] (.R (n_17), .S (1'b1), .CLK (clk), .D (n_30),
       .Q (n_63));
  DFFSR \shiftreg_reg[3] (.R (n_17), .S (1'b1), .CLK (clk), .D (n_28),
       .Q (n_62));
  INVX1 g35(.A (n_41), .Y (n_49));
  INVX1 g36(.A (n_40), .Y (n_48));
  INVX1 g37(.A (n_39), .Y (n_47));
  INVX1 g38(.A (n_38), .Y (n_46));
  INVX1 g39(.A (n_37), .Y (n_45));
  INVX1 g40(.A (n_36), .Y (n_44));
  INVX1 g41(.A (n_35), .Y (n_43));
  INVX1 g42(.A (n_34), .Y (n_42));
  MUX2X1 g43(.A (shiftreg_out[4]), .B (shiftreg_out[5]), .S (en), .Y
       (n_41));
  MUX2X1 g44(.A (shiftreg_out[5]), .B (shiftreg_out[6]), .S (en), .Y
       (n_40));
  MUX2X1 g45(.A (shiftreg_out[11]), .B (shiftreg_out[12]), .S (en), .Y
       (n_39));
  MUX2X1 g46(.A (shiftreg_out[6]), .B (shiftreg_out[7]), .S (en), .Y
       (n_38));
  MUX2X1 g47(.A (shiftreg_out[12]), .B (shiftreg_out[13]), .S (en), .Y
       (n_37));
  MUX2X1 g48(.A (shiftreg_out[7]), .B (shiftreg_out[8]), .S (en), .Y
       (n_36));
  MUX2X1 g49(.A (shiftreg_out[13]), .B (shiftreg_out[14]), .S (en), .Y
       (n_35));
  MUX2X1 g50(.A (shiftreg_out[8]), .B (shiftreg_out[9]), .S (en), .Y
       (n_34));
  INVX1 g51(.A (n_25), .Y (n_33));
  INVX1 g52(.A (n_24), .Y (n_32));
  INVX1 g53(.A (n_23), .Y (n_31));
  INVX1 g54(.A (n_22), .Y (n_30));
  INVX1 g55(.A (n_21), .Y (n_29));
  INVX1 g56(.A (n_20), .Y (n_28));
  INVX1 g57(.A (n_19), .Y (n_27));
  INVX1 g58(.A (n_18), .Y (n_26));
  MUX2X1 g59(.A (shiftreg_out[14]), .B (shiftreg_out[15]), .S (en), .Y
       (n_25));
  MUX2X1 g60(.A (shiftreg_out[9]), .B (shiftreg_out[10]), .S (en), .Y
       (n_24));
  MUX2X1 g61(.A (shiftreg_out[0]), .B (shiftreg_out[1]), .S (en), .Y
       (n_23));
  MUX2X1 g62(.A (shiftreg_out[1]), .B (shiftreg_out[2]), .S (en), .Y
       (n_22));
  MUX2X1 g63(.A (scan_in), .B (shiftreg_out[0]), .S (en), .Y (n_21));
  MUX2X1 g64(.A (shiftreg_out[2]), .B (shiftreg_out[3]), .S (en), .Y
       (n_20));
  MUX2X1 g65(.A (shiftreg_out[10]), .B (shiftreg_out[11]), .S (en), .Y
       (n_19));
  MUX2X1 g66(.A (shiftreg_out[3]), .B (shiftreg_out[4]), .S (en), .Y
       (n_18));
  INVX1 g67(.A (rst), .Y (n_17));
  BUFX2 drc_bufs131(.A (n_69), .Y (shiftreg_out[15]));
  BUFX2 drc_bufs132(.A (n_51), .Y (shiftreg_out[14]));
  BUFX2 drc_bufs133(.A (n_52), .Y (shiftreg_out[13]));
  BUFX2 drc_bufs134(.A (n_53), .Y (shiftreg_out[12]));
  BUFX2 drc_bufs135(.A (n_54), .Y (shiftreg_out[11]));
  BUFX2 drc_bufs136(.A (n_55), .Y (shiftreg_out[10]));
  BUFX2 drc_bufs137(.A (n_56), .Y (shiftreg_out[9]));
  BUFX2 drc_bufs138(.A (n_57), .Y (shiftreg_out[8]));
  BUFX2 drc_bufs139(.A (n_58), .Y (shiftreg_out[7]));
  BUFX2 drc_bufs140(.A (n_59), .Y (shiftreg_out[6]));
  BUFX2 drc_bufs141(.A (n_60), .Y (shiftreg_out[5]));
  BUFX2 drc_bufs142(.A (n_61), .Y (shiftreg_out[4]));
  BUFX2 drc_bufs143(.A (n_62), .Y (shiftreg_out[3]));
  BUFX2 drc_bufs144(.A (n_63), .Y (shiftreg_out[2]));
  BUFX2 drc_bufs145(.A (n_64), .Y (shiftreg_out[1]));
  BUFX2 drc_bufs146(.A (n_65), .Y (shiftreg_out[0]));
endmodule

module shift_reg_16b(clk, scan_in, wrap_mode, en, rst, shiftreg_out);
  input clk, scan_in, wrap_mode, en, rst;
  output [15:0] shiftreg_out;
  wire clk, scan_in, wrap_mode, en, rst;
  wire [15:0] shiftreg_out;
  wire n_0, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51, n_52, n_55, n_56, n_57, n_58;
  wire n_59, n_60, n_61, n_62, n_63, n_64, n_65, n_66;
  wire n_67, n_68, n_69, shiftreg;
  DFFSR \shiftreg_reg[0] (.R (n_19), .S (1'b1), .CLK (clk), .D (n_52),
       .Q (n_69));
  OAI21X1 g43(.A (n_18), .B (n_21), .C (n_0), .Y (n_52));
  DFFSR \shiftreg_reg[10] (.R (n_19), .S (1'b1), .CLK (clk), .D (n_30),
       .Q (n_59));
  DFFSR \shiftreg_reg[11] (.R (n_19), .S (1'b1), .CLK (clk), .D (n_49),
       .Q (n_58));
  DFFSR \shiftreg_reg[3] (.R (n_19), .S (1'b1), .CLK (clk), .D (n_29),
       .Q (n_66));
  DFFSR \shiftreg_reg[4] (.R (n_19), .S (1'b1), .CLK (clk), .D (n_51),
       .Q (n_65));
  DFFSR \shiftreg_reg[5] (.R (n_19), .S (1'b1), .CLK (clk), .D (n_50),
       .Q (n_64));
  DFFSR \shiftreg_reg[6] (.R (n_19), .S (1'b1), .CLK (clk), .D (n_48),
       .Q (n_63));
  DFFSR \shiftreg_reg[12] (.R (n_19), .S (1'b1), .CLK (clk), .D (n_47),
       .Q (n_57));
  DFFSR \shiftreg_reg[7] (.R (n_19), .S (1'b1), .CLK (clk), .D (n_46),
       .Q (n_62));
  DFFSR \shiftreg_reg[8] (.R (n_19), .S (1'b1), .CLK (clk), .D (n_44),
       .Q (n_61));
  DFFSR \shiftreg_reg[13] (.R (n_19), .S (1'b1), .CLK (clk), .D (n_45),
       .Q (n_56));
  DFFSR \shiftreg_reg[9] (.R (n_19), .S (1'b1), .CLK (clk), .D (n_35),
       .Q (n_60));
  DFFSR \shiftreg_reg[14] (.R (n_19), .S (1'b1), .CLK (clk), .D (n_34),
       .Q (n_55));
  DFFSR \shiftreg_reg[15] (.R (n_19), .S (1'b1), .CLK (clk), .D (n_33),
       .Q (shiftreg));
  DFFSR \shiftreg_reg[1] (.R (n_19), .S (1'b1), .CLK (clk), .D (n_32),
       .Q (n_68));
  DFFSR \shiftreg_reg[2] (.R (n_19), .S (1'b1), .CLK (clk), .D (n_31),
       .Q (n_67));
  INVX1 g59(.A (n_43), .Y (n_51));
  INVX1 g60(.A (n_42), .Y (n_50));
  INVX1 g61(.A (n_41), .Y (n_49));
  INVX1 g62(.A (n_40), .Y (n_48));
  INVX1 g63(.A (n_39), .Y (n_47));
  INVX1 g64(.A (n_38), .Y (n_46));
  INVX1 g65(.A (n_37), .Y (n_45));
  INVX1 g66(.A (n_36), .Y (n_44));
  MUX2X1 g67(.A (shiftreg_out[4]), .B (shiftreg_out[3]), .S (n_18), .Y
       (n_43));
  MUX2X1 g68(.A (shiftreg_out[5]), .B (shiftreg_out[4]), .S (n_18), .Y
       (n_42));
  MUX2X1 g69(.A (shiftreg_out[11]), .B (shiftreg_out[10]), .S (n_18),
       .Y (n_41));
  MUX2X1 g70(.A (shiftreg_out[6]), .B (shiftreg_out[5]), .S (n_18), .Y
       (n_40));
  MUX2X1 g71(.A (shiftreg_out[12]), .B (shiftreg_out[11]), .S (n_18),
       .Y (n_39));
  MUX2X1 g72(.A (shiftreg_out[7]), .B (shiftreg_out[6]), .S (n_18), .Y
       (n_38));
  MUX2X1 g73(.A (shiftreg_out[13]), .B (shiftreg_out[12]), .S (n_18),
       .Y (n_37));
  MUX2X1 g74(.A (shiftreg_out[8]), .B (shiftreg_out[7]), .S (n_18), .Y
       (n_36));
  INVX1 g75(.A (n_28), .Y (n_35));
  INVX1 g76(.A (n_27), .Y (n_34));
  INVX1 g77(.A (n_26), .Y (n_33));
  INVX1 g78(.A (n_25), .Y (n_32));
  INVX1 g79(.A (n_24), .Y (n_31));
  INVX1 g80(.A (n_23), .Y (n_30));
  INVX1 g81(.A (n_22), .Y (n_29));
  MUX2X1 g82(.A (shiftreg_out[9]), .B (shiftreg_out[8]), .S (n_18), .Y
       (n_28));
  MUX2X1 g83(.A (shiftreg_out[14]), .B (shiftreg_out[13]), .S (n_18),
       .Y (n_27));
  MUX2X1 g84(.A (shiftreg_out[15]), .B (shiftreg_out[14]), .S (n_18),
       .Y (n_26));
  MUX2X1 g85(.A (shiftreg_out[1]), .B (shiftreg_out[0]), .S (n_18), .Y
       (n_25));
  MUX2X1 g86(.A (shiftreg_out[2]), .B (shiftreg_out[1]), .S (n_18), .Y
       (n_24));
  MUX2X1 g87(.A (shiftreg_out[10]), .B (shiftreg_out[9]), .S (n_18), .Y
       (n_23));
  MUX2X1 g88(.A (shiftreg_out[3]), .B (shiftreg_out[2]), .S (n_18), .Y
       (n_22));
  MUX2X1 g89(.A (shiftreg_out[15]), .B (scan_in), .S (wrap_mode), .Y
       (n_21));
  NAND2X1 g90(.A (n_18), .B (shiftreg_out[0]), .Y (n_20));
  INVX1 g91(.A (rst), .Y (n_19));
  INVX1 g92(.A (en), .Y (n_18));
  BUFX2 drc_bufs156(.A (n_20), .Y (n_0));
  BUFX2 drc_bufs157(.A (n_69), .Y (shiftreg_out[0]));
  BUFX2 drc_bufs158(.A (n_68), .Y (shiftreg_out[1]));
  BUFX2 drc_bufs159(.A (n_66), .Y (shiftreg_out[3]));
  BUFX2 drc_bufs160(.A (n_55), .Y (shiftreg_out[14]));
  BUFX2 drc_bufs161(.A (n_56), .Y (shiftreg_out[13]));
  BUFX2 drc_bufs162(.A (n_57), .Y (shiftreg_out[12]));
  BUFX2 drc_bufs163(.A (n_58), .Y (shiftreg_out[11]));
  BUFX2 drc_bufs164(.A (n_59), .Y (shiftreg_out[10]));
  BUFX2 drc_bufs165(.A (n_60), .Y (shiftreg_out[9]));
  BUFX2 drc_bufs166(.A (n_61), .Y (shiftreg_out[8]));
  BUFX2 drc_bufs167(.A (n_62), .Y (shiftreg_out[7]));
  BUFX2 drc_bufs168(.A (n_63), .Y (shiftreg_out[6]));
  BUFX2 drc_bufs169(.A (n_64), .Y (shiftreg_out[5]));
  BUFX2 drc_bufs170(.A (n_65), .Y (shiftreg_out[4]));
  BUFX2 drc_bufs171(.A (shiftreg), .Y (shiftreg_out[15]));
  BUFX2 drc_bufs172(.A (n_67), .Y (shiftreg_out[2]));
endmodule

module pipe_mul_top(clk, rst, en, input_bin_a, input_bin_b,
     input_bin_c, wrap_mode_a, wrap_mode_b, en_sr_a, en_sr_b, rst_out,
     bin_out);
  input clk, rst, en, wrap_mode_a, wrap_mode_b, en_sr_a, en_sr_b,
       rst_out;
  input [3:0] input_bin_a, input_bin_b;
  input [7:0] input_bin_c;
  output [7:0] bin_out;
  wire clk, rst, en, wrap_mode_a, wrap_mode_b, en_sr_a, en_sr_b,
       rst_out;
  wire [3:0] input_bin_a, input_bin_b;
  wire [7:0] input_bin_c;
  wire [7:0] bin_out;
  wire [15:0] sr_mul_out;
  wire [7:0] bin_out_int;
  wire [15:0] sr_out_a;
  wire [15:0] sr_out_b;
  wire UNCONNECTED1, UNCONNECTED2, UNCONNECTED3, UNCONNECTED4,
       UNCONNECTED5, UNCONNECTED6, UNCONNECTED7, UNCONNECTED8;
  wire UNCONNECTED9, UNCONNECTED10, UNCONNECTED11, UNCONNECTED12,
       UNCONNECTED13, UNCONNECTED14, UNCONNECTED15, UNCONNECTED16;
  wire UNCONNECTED17, UNCONNECTED18, UNCONNECTED19, UNCONNECTED20,
       UNCONNECTED21, UNCONNECTED22, UNCONNECTED23, UNCONNECTED24;
  wire UNCONNECTED25, ctr4_overflow_a, ctr4_overflow_b, n_1, n_2, n_3,
       n_4, n_5;
  wire n_6, n_7, sn_out_a, sn_out_b;
  ctr_out_bank dut_ctr_out(.clk (clk), .rst (rst_out), .mul_in
       (sr_mul_out), .bin_out ({UNCONNECTED24, UNCONNECTED23,
       UNCONNECTED22, UNCONNECTED21, UNCONNECTED20, UNCONNECTED19,
       UNCONNECTED18, UNCONNECTED17, UNCONNECTED16, UNCONNECTED15,
       UNCONNECTED14, UNCONNECTED13, UNCONNECTED12, UNCONNECTED11,
       UNCONNECTED10, UNCONNECTED9, UNCONNECTED8, UNCONNECTED7,
       UNCONNECTED6, UNCONNECTED5, UNCONNECTED4, UNCONNECTED3,
       UNCONNECTED2, UNCONNECTED1, bin_out_int}));
  pipe_mul_16b dut_pipe_mul(.a (sr_out_a), .b (sr_out_b), .y
       (sr_mul_out));
  prg_4b dut_prg4b_a(.clk (clk), .rst (rst), .en (en), .bin_in
       (input_bin_a), .sn_out (sn_out_a), .ctr_overflow
       (ctr4_overflow_a));
  prg_4b_1 dut_prg4b_b(.clk (clk), .rst (rst), .en (en), .bin_in
       (input_bin_b), .sn_out (sn_out_b), .ctr_overflow
       (ctr4_overflow_b));
  shift_reg_16b_noshift dut_sr_a(.clk (clk), .scan_in (sn_out_a), .en
       (en_sr_a), .rst (rst), .shiftreg_out (sr_out_a));
  shift_reg_16b dut_sr_b(.clk (clk), .scan_in (sn_out_b), .wrap_mode
       (wrap_mode_b), .en (en_sr_b), .rst (rst), .shiftreg_out
       (sr_out_b));
  FAX1 g444(.A (input_bin_c[6]), .B (bin_out_int[6]), .C (n_6), .YC
       (n_7), .YS (bin_out[6]));
  FAX1 g445(.A (input_bin_c[5]), .B (bin_out_int[5]), .C (n_5), .YC
       (n_6), .YS (bin_out[5]));
  FAX1 g446(.A (input_bin_c[4]), .B (bin_out_int[4]), .C (n_4), .YC
       (n_5), .YS (bin_out[4]));
  FAX1 g447(.A (input_bin_c[3]), .B (bin_out_int[3]), .C (n_3), .YC
       (n_4), .YS (bin_out[3]));
  FAX1 g448(.A (input_bin_c[2]), .B (bin_out_int[2]), .C (n_2), .YC
       (n_3), .YS (bin_out[2]));
  FAX1 g449(.A (input_bin_c[1]), .B (n_1), .C (bin_out_int[1]), .YC
       (n_2), .YS (bin_out[1]));
  HAX1 g450(.A (input_bin_c[0]), .B (bin_out_int[0]), .YC (n_1), .YS
       (bin_out[0]));
  FAX1 g2(.A (n_7), .B (bin_out_int[7]), .C (input_bin_c[7]), .YC
       (UNCONNECTED25), .YS (bin_out[7]));
endmodule

