
// Generated by Cadence Encounter(R) RTL Compiler RC14.28 - v14.20-s067_1

// Verification Directory fv/ctr_out_bank_32 

module csa_tree_add_905_257_group_281(in_0, in_1, in_2, in_3, in_4,
     in_5, in_6, in_7, in_8, in_9, in_10, in_11, in_12, in_13, in_14,
     in_15, in_16, in_17, in_18, in_19, in_20, in_21, in_22, in_23,
     in_24, in_25, in_26, in_27, in_28, in_29, in_30, in_31, out_0);
  input [4:0] in_0, in_1, in_2, in_3, in_4, in_5, in_6, in_7, in_8,
       in_9, in_10, in_11, in_12, in_13, in_14, in_15, in_16, in_17,
       in_18, in_19, in_20, in_21, in_22, in_23, in_24, in_25, in_26,
       in_27, in_28, in_29, in_30, in_31;
  output [9:0] out_0;
  wire [4:0] in_0, in_1, in_2, in_3, in_4, in_5, in_6, in_7, in_8,
       in_9, in_10, in_11, in_12, in_13, in_14, in_15, in_16, in_17,
       in_18, in_19, in_20, in_21, in_22, in_23, in_24, in_25, in_26,
       in_27, in_28, in_29, in_30, in_31;
  wire [9:0] out_0;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_84, n_85, n_86, n_87;
  wire n_88, n_89, n_90, n_91, n_92, n_93, n_94, n_95;
  wire n_96, n_97, n_98, n_99, n_100, n_101, n_102, n_103;
  wire n_104, n_105, n_106, n_107, n_108, n_109, n_110, n_111;
  wire n_112, n_113, n_114, n_115, n_116, n_117, n_118, n_119;
  wire n_120, n_121, n_122, n_123, n_124, n_125, n_126, n_127;
  wire n_128, n_129, n_130, n_131, n_132, n_133, n_134, n_135;
  wire n_136, n_137, n_138, n_139, n_140, n_141, n_142, n_143;
  wire n_144, n_145, n_146, n_147, n_148, n_149, n_150, n_151;
  wire n_152, n_153, n_154, n_155, n_156, n_157, n_158, n_159;
  wire n_160, n_161, n_162, n_163, n_164, n_165, n_166, n_167;
  wire n_168, n_169, n_170, n_171, n_172, n_173, n_174, n_175;
  wire n_176, n_177, n_178, n_179, n_180, n_181, n_182, n_183;
  wire n_184, n_185, n_186, n_187, n_188, n_189, n_190, n_191;
  wire n_192, n_193, n_194, n_195, n_196, n_197, n_198, n_199;
  wire n_200, n_201, n_202, n_203, n_204, n_205, n_206, n_207;
  wire n_208, n_209, n_210, n_211, n_212, n_213, n_214, n_215;
  wire n_216, n_217, n_218, n_219, n_220, n_221, n_222, n_223;
  wire n_224, n_226, n_227, n_228, n_229, n_230, n_231, n_232;
  wire n_233, n_234, n_235, n_236, n_237, n_238, n_239, n_240;
  wire n_241, n_242, n_243, n_244, n_245, n_246, n_247, n_248;
  wire n_249, n_250, n_251, n_252, n_253, n_254, n_255, n_256;
  wire n_257, n_258, n_259, n_260, n_261, n_262, n_263, n_264;
  wire n_266, n_267, n_268, n_269, n_270, n_271, n_272, n_273;
  wire n_274, n_275, n_276, n_277, n_278, n_279, n_280, n_281;
  wire n_282, n_283, n_284, n_286, n_287, n_288, n_289, n_290;
  wire n_291, n_292, n_293, n_294, n_296, n_297, n_298, n_299;
  wire n_300, n_302, n_304, n_306;
  FAX1 g4053(.A (n_278), .B (n_292), .C (n_306), .YC (out_0[9]), .YS
       (out_0[8]));
  FAX1 g4054(.A (n_293), .B (n_298), .C (n_304), .YC (n_306), .YS
       (out_0[7]));
  FAX1 g4055(.A (n_299), .B (n_296), .C (n_302), .YC (n_304), .YS
       (out_0[6]));
  FAX1 g4056(.A (n_290), .B (n_297), .C (n_300), .YC (n_302), .YS
       (out_0[5]));
  FAX1 g4057(.A (n_280), .B (n_291), .C (n_294), .YC (n_300), .YS
       (out_0[4]));
  FAX1 g4058(.A (n_272), .B (n_289), .C (n_286), .YC (n_298), .YS
       (n_299));
  FAX1 g4059(.A (n_273), .B (n_282), .C (n_287), .YC (n_296), .YS
       (n_297));
  FAX1 g4060(.A (n_262), .B (n_284), .C (n_281), .YC (n_294), .YS
       (out_0[3]));
  FAX1 g4061(.A (n_276), .B (n_279), .C (n_288), .YC (n_292), .YS
       (n_293));
  FAX1 g4062(.A (n_275), .B (n_266), .C (n_283), .YC (n_290), .YS
       (n_291));
  FAX1 g4063(.A (n_259), .B (n_268), .C (n_277), .YC (n_288), .YS
       (n_289));
  FAX1 g4064(.A (n_270), .B (n_274), .C (n_269), .YC (n_286), .YS
       (n_287));
  FAX1 g4065(.A (n_257), .B (n_263), .C (n_264), .YC (n_284), .YS
       (out_0[2]));
  FAX1 g4066(.A (n_235), .B (n_260), .C (n_271), .YC (n_282), .YS
       (n_283));
  FAX1 g4067(.A (n_256), .B (n_261), .C (n_267), .YC (n_280), .YS
       (n_281));
  FAX1 g4068(.A (n_228), .B (n_250), .C (n_258), .YC (n_278), .YS
       (n_279));
  FAX1 g4069(.A (n_251), .B (n_248), .C (n_246), .YC (n_276), .YS
       (n_277));
  FAX1 g4070(.A (n_243), .B (n_255), .C (n_252), .YC (n_274), .YS
       (n_275));
  FAX1 g4071(.A (n_249), .B (n_234), .C (n_247), .YC (n_272), .YS
       (n_273));
  FAX1 g4072(.A (n_238), .B (n_191), .C (n_236), .YC (n_270), .YS
       (n_271));
  FAX1 g4073(.A (n_242), .B (n_241), .C (n_254), .YC (n_268), .YS
       (n_269));
  FAX1 g4074(.A (n_237), .B (n_244), .C (n_253), .YC (n_266), .YS
       (n_267));
  FAX1 g4075(.A (n_224), .B (n_227), .C (n_233), .YC (n_264), .YS
       (out_0[1]));
  FAX1 g4076(.A (n_231), .B (n_232), .C (n_245), .YC (n_262), .YS
       (n_263));
  FAX1 g4077(.A (n_201), .B (n_239), .C (n_230), .YC (n_260), .YS
       (n_261));
  FAX1 g4078(.A (n_229), .B (n_214), .C (n_240), .YC (n_258), .YS
       (n_259));
  FAX1 g4079(.A (n_203), .B (n_211), .C (n_226), .YC (n_256), .YS
       (n_257));
  FAX1 g4080(.A (n_207), .B (n_187), .C (n_222), .YC (n_254), .YS
       (n_255));
  FAX1 g4081(.A (n_213), .B (n_223), .C (n_210), .YC (n_252), .YS
       (n_253));
  FAX1 g4082(.A (n_178), .B (n_204), .C (n_218), .YC (n_250), .YS
       (n_251));
  FAX1 g4083(.A (n_205), .B (n_198), .C (n_220), .YC (n_248), .YS
       (n_249));
  FAX1 g4084(.A (n_215), .B (n_219), .C (n_190), .YC (n_246), .YS
       (n_247));
  FAX1 g4085(.A (n_209), .B (n_195), .C (n_196), .YC (n_244), .YS
       (n_245));
  FAX1 g4086(.A (n_216), .B (n_212), .C (n_188), .YC (n_242), .YS
       (n_243));
  FAX1 g4087(.A (n_179), .B (n_186), .C (n_206), .YC (n_240), .YS
       (n_241));
  FAX1 g4088(.A (n_184), .B (n_208), .C (n_217), .YC (n_238), .YS
       (n_239));
  FAX1 g4089(.A (n_202), .B (n_189), .C (n_194), .YC (n_236), .YS
       (n_237));
  FAX1 g4090(.A (n_199), .B (n_221), .C (n_200), .YC (n_234), .YS
       (n_235));
  FAX1 g4091(.A (n_193), .B (n_180), .C (n_197), .YC (n_232), .YS
       (n_233));
  FAX1 g4092(.A (n_182), .B (n_185), .C (n_192), .YC (n_230), .YS
       (n_231));
  FAX1 g4093(.A (n_172), .B (n_122), .C (n_152), .YC (n_228), .YS
       (n_229));
  FAX1 g4094(.A (n_149), .B (n_143), .C (n_183), .YC (n_226), .YS
       (n_227));
  FAX1 g4095(.A (n_121), .B (n_129), .C (n_181), .YC (n_224), .YS
       (out_0[0]));
  FAX1 g4096(.A (n_139), .B (n_166), .C (n_136), .YC (n_222), .YS
       (n_223));
  FAX1 g4097(.A (n_174), .B (n_130), .C (n_156), .YC (n_220), .YS
       (n_221));
  FAX1 g4098(.A (n_123), .B (n_126), .C (n_176), .YC (n_218), .YS
       (n_219));
  FAX1 g4099(.A (n_124), .B (n_144), .C (n_110), .YC (n_216), .YS
       (n_217));
  FAX1 g4100(.A (n_173), .B (n_153), .C (n_150), .YC (n_214), .YS
       (n_215));
  FAX1 g4101(.A (n_163), .B (n_165), .C (n_140), .YC (n_212), .YS
       (n_213));
  FAX1 g4102(.A (n_137), .B (n_141), .C (n_167), .YC (n_210), .YS
       (n_211));
  FAX1 g4103(.A (n_112), .B (n_134), .C (n_146), .YC (n_208), .YS
       (n_209));
  FAX1 g4104(.A (n_114), .B (n_164), .C (n_162), .YC (n_206), .YS
       (n_207));
  FAX1 g4105(.A (n_170), .B (n_160), .C (n_154), .YC (n_204), .YS
       (n_205));
  FAX1 g4106(.A (n_125), .B (n_169), .C (n_158), .YC (n_202), .YS
       (n_203));
  FAX1 g4107(.A (n_175), .B (n_131), .C (n_157), .YC (n_200), .YS
       (n_201));
  FAX1 g4108(.A (n_171), .B (n_155), .C (n_161), .YC (n_198), .YS
       (n_199));
  FAX1 g4109(.A (n_133), .B (n_118), .C (n_159), .YC (n_196), .YS
       (n_197));
  FAX1 g4110(.A (n_145), .B (n_148), .C (n_142), .YC (n_194), .YS
       (n_195));
  FAX1 g4111(.A (n_147), .B (n_135), .C (n_120), .YC (n_192), .YS
       (n_193));
  FAX1 g4112(.A (n_177), .B (n_127), .C (n_151), .YC (n_190), .YS
       (n_191));
  FAX1 g4113(.A (n_49), .B (n_168), .C (n_115), .YC (n_188), .YS
       (n_189));
  FAX1 g4114(.A (n_105), .B (n_138), .C (n_117), .YC (n_186), .YS
       (n_187));
  FAX1 g4115(.A (n_35), .B (n_132), .C (n_111), .YC (n_184), .YS
       (n_185));
  FAX1 g4116(.A (n_39), .B (n_113), .C (n_128), .YC (n_182), .YS
       (n_183));
  FAX1 g4117(.A (n_29), .B (n_23), .C (n_119), .YC (n_180), .YS
       (n_181));
  FAX1 g4118(.A (n_108), .B (n_70), .C (n_116), .YC (n_178), .YS
       (n_179));
  FAX1 g4119(.A (n_25), .B (n_75), .C (n_17), .YC (n_176), .YS (n_177));
  FAX1 g4120(.A (n_21), .B (n_101), .C (n_11), .YC (n_174), .YS
       (n_175));
  FAX1 g4121(.A (n_2), .B (n_68), .C (n_24), .YC (n_172), .YS (n_173));
  FAX1 g4122(.A (n_98), .B (n_48), .C (n_20), .YC (n_170), .YS (n_171));
  FAX1 g4123(.A (n_90), .B (n_42), .C (n_86), .YC (n_168), .YS (n_169));
  FAX1 g4124(.A (n_83), .B (n_93), .C (n_81), .YC (n_166), .YS (n_167));
  FAX1 g4125(.A (n_82), .B (n_80), .C (n_88), .YC (n_164), .YS (n_165));
  FAX1 g4126(.A (n_78), .B (n_12), .C (n_34), .YC (n_162), .YS (n_163));
  FAX1 g4127(.A (n_14), .B (n_66), .C (n_76), .YC (n_160), .YS (n_161));
  FAX1 g4128(.A (n_97), .B (n_57), .C (n_51), .YC (n_158), .YS (n_159));
  FAX1 g4129(.A (n_65), .B (n_103), .C (n_67), .YC (n_156), .YS
       (n_157));
  FAX1 g4130(.A (n_100), .B (n_102), .C (n_10), .YC (n_154), .YS
       (n_155));
  FAX1 g4131(.A (n_58), .B (n_104), .C (n_106), .YC (n_152), .YS
       (n_153));
  FAX1 g4132(.A (n_109), .B (n_71), .C (n_37), .YC (n_150), .YS
       (n_151));
  FAX1 g4133(.A (n_47), .B (n_73), .C (n_43), .YC (n_148), .YS (n_149));
  FAX1 g4134(.A (n_54), .B (n_32), .C (n_52), .YC (n_146), .YS (n_147));
  FAX1 g4135(.A (n_38), .B (n_50), .C (n_94), .YC (n_144), .YS (n_145));
  FAX1 g4136(.A (n_95), .B (n_91), .C (n_87), .YC (n_142), .YS (n_143));
  FAX1 g4137(.A (n_41), .B (n_19), .C (n_79), .YC (n_140), .YS (n_141));
  FAX1 g4138(.A (n_18), .B (n_40), .C (n_92), .YC (n_138), .YS (n_139));
  FAX1 g4139(.A (n_85), .B (n_13), .C (n_89), .YC (n_136), .YS (n_137));
  FAX1 g4140(.A (n_30), .B (n_28), .C (n_22), .YC (n_134), .YS (n_135));
  FAX1 g4141(.A (n_44), .B (n_26), .C (n_62), .YC (n_132), .YS (n_133));
  FAX1 g4142(.A (n_99), .B (n_15), .C (n_77), .YC (n_130), .YS (n_131));
  FAX1 g4143(.A (n_27), .B (n_53), .C (n_45), .YC (n_128), .YS (n_129));
  FAX1 g4144(.A (n_69), .B (n_59), .C (n_107), .YC (n_126), .YS
       (n_127));
  FAX1 g4145(.A (n_56), .B (n_72), .C (n_46), .YC (n_124), .YS (n_125));
  FAX1 g4146(.A (n_74), .B (n_36), .C (n_16), .YC (n_122), .YS (n_123));
  FAX1 g4147(.A (n_63), .B (n_61), .C (n_33), .YC (n_120), .YS (n_121));
  FAX1 g4148(.A (n_5), .B (n_31), .C (n_55), .YC (n_118), .YS (n_119));
  FAX1 g4149(.A (n_0), .B (n_3), .C (n_64), .YC (n_116), .YS (n_117));
  FAX1 g4150(.A (n_8), .B (n_1), .C (n_84), .YC (n_114), .YS (n_115));
  FAX1 g4151(.A (n_4), .B (n_7), .C (n_60), .YC (n_112), .YS (n_113));
  FAX1 g4152(.A (n_6), .B (n_9), .C (n_96), .YC (n_110), .YS (n_111));
  FAX1 g4153(.A (in_2[4]), .B (in_5[4]), .C (in_11[4]), .YC (n_108),
       .YS (n_109));
  FAX1 g4154(.A (in_14[4]), .B (in_29[4]), .C (in_30[4]), .YC (n_106),
       .YS (n_107));
  FAX1 g4155(.A (in_13[4]), .B (in_27[4]), .C (in_28[4]), .YC (n_104),
       .YS (n_105));
  FAX1 g4156(.A (in_10[3]), .B (in_21[3]), .C (in_22[3]), .YC (n_102),
       .YS (n_103));
  FAX1 g4157(.A (in_9[3]), .B (in_19[3]), .C (in_20[3]), .YC (n_100),
       .YS (n_101));
  FAX1 g4158(.A (in_3[3]), .B (in_7[3]), .C (in_15[3]), .YC (n_98), .YS
       (n_99));
  FAX1 g4159(.A (in_3[1]), .B (in_7[1]), .C (in_15[1]), .YC (n_96), .YS
       (n_97));
  FAX1 g4160(.A (in_2[1]), .B (in_5[1]), .C (in_11[1]), .YC (n_94), .YS
       (n_95));
  FAX1 g4161(.A (in_9[2]), .B (in_19[2]), .C (in_20[2]), .YC (n_92),
       .YS (n_93));
  FAX1 g4162(.A (in_10[1]), .B (in_21[1]), .C (in_22[1]), .YC (n_90),
       .YS (n_91));
  FAX1 g4163(.A (in_14[2]), .B (in_29[2]), .C (in_30[2]), .YC (n_88),
       .YS (n_89));
  FAX1 g4164(.A (in_25[1]), .B (in_26[1]), .C (in_30[1]), .YC (n_86),
       .YS (n_87));
  FAX1 g4165(.A (in_3[2]), .B (in_7[2]), .C (in_15[2]), .YC (n_84), .YS
       (n_85));
  FAX1 g4166(.A (in_2[2]), .B (in_5[2]), .C (in_11[2]), .YC (n_82), .YS
       (n_83));
  FAX1 g4167(.A (in_13[2]), .B (in_27[2]), .C (in_28[2]), .YC (n_80),
       .YS (n_81));
  FAX1 g4168(.A (in_10[2]), .B (in_21[2]), .C (in_22[2]), .YC (n_78),
       .YS (n_79));
  FAX1 g4169(.A (in_14[3]), .B (in_29[3]), .C (in_30[3]), .YC (n_76),
       .YS (n_77));
  FAX1 g4170(.A (in_9[4]), .B (in_19[4]), .C (in_20[4]), .YC (n_74),
       .YS (n_75));
  FAX1 g4171(.A (in_9[1]), .B (in_19[1]), .C (in_20[1]), .YC (n_72),
       .YS (n_73));
  FAX1 g4172(.A (in_10[4]), .B (in_21[4]), .C (in_22[4]), .YC (n_70),
       .YS (n_71));
  FAX1 g4173(.A (in_3[4]), .B (in_7[4]), .C (in_15[4]), .YC (n_68), .YS
       (n_69));
  FAX1 g4174(.A (in_13[3]), .B (in_27[3]), .C (in_28[3]), .YC (n_66),
       .YS (n_67));
  FAX1 g4175(.A (in_2[3]), .B (in_5[3]), .C (in_11[3]), .YC (n_64), .YS
       (n_65));
  FAX1 g4176(.A (in_2[0]), .B (in_9[0]), .C (in_10[0]), .YC (n_62), .YS
       (n_63));
  FAX1 g4177(.A (in_15[0]), .B (in_23[0]), .C (in_24[0]), .YC (n_60),
       .YS (n_61));
  FAX1 g4178(.A (in_8[4]), .B (in_16[4]), .C (in_31[4]), .YC (n_58),
       .YS (n_59));
  FAX1 g4179(.A (in_8[1]), .B (in_16[1]), .C (in_31[1]), .YC (n_56),
       .YS (n_57));
  FAX1 g4180(.A (in_6[0]), .B (in_11[0]), .C (in_12[0]), .YC (n_54),
       .YS (n_55));
  FAX1 g4181(.A (in_7[0]), .B (in_25[0]), .C (in_26[0]), .YC (n_52),
       .YS (n_53));
  FAX1 g4182(.A (in_14[1]), .B (in_27[1]), .C (in_28[1]), .YC (n_50),
       .YS (n_51));
  FAX1 g4183(.A (in_8[3]), .B (in_16[3]), .C (in_31[3]), .YC (n_48),
       .YS (n_49));
  FAX1 g4184(.A (in_4[1]), .B (in_17[1]), .C (in_18[1]), .YC (n_46),
       .YS (n_47));
  FAX1 g4185(.A (in_4[0]), .B (in_17[0]), .C (in_18[0]), .YC (n_44),
       .YS (n_45));
  FAX1 g4186(.A (in_12[1]), .B (in_23[1]), .C (in_24[1]), .YC (n_42),
       .YS (n_43));
  FAX1 g4187(.A (in_4[2]), .B (in_17[2]), .C (in_18[2]), .YC (n_40),
       .YS (n_41));
  FAX1 g4188(.A (in_6[1]), .B (in_13[1]), .C (in_29[1]), .YC (n_38),
       .YS (n_39));
  FAX1 g4189(.A (in_12[4]), .B (in_23[4]), .C (in_24[4]), .YC (n_36),
       .YS (n_37));
  FAX1 g4190(.A (in_6[2]), .B (in_25[2]), .C (in_26[2]), .YC (n_34),
       .YS (n_35));
  FAX1 g4191(.A (in_5[0]), .B (in_13[0]), .C (in_14[0]), .YC (n_32),
       .YS (n_33));
  FAX1 g4192(.A (in_8[0]), .B (in_19[0]), .C (in_20[0]), .YC (n_30),
       .YS (n_31));
  FAX1 g4193(.A (in_3[0]), .B (in_27[0]), .C (in_28[0]), .YC (n_28),
       .YS (n_29));
  FAX1 g4194(.A (in_16[0]), .B (in_21[0]), .C (in_22[0]), .YC (n_26),
       .YS (n_27));
  FAX1 g4195(.A (in_4[4]), .B (in_17[4]), .C (in_18[4]), .YC (n_24),
       .YS (n_25));
  FAX1 g4196(.A (in_1[0]), .B (in_29[0]), .C (in_30[0]), .YC (n_22),
       .YS (n_23));
  FAX1 g4197(.A (in_4[3]), .B (in_17[3]), .C (in_18[3]), .YC (n_20),
       .YS (n_21));
  FAX1 g4198(.A (in_8[2]), .B (in_16[2]), .C (in_31[2]), .YC (n_18),
       .YS (n_19));
  FAX1 g4199(.A (in_6[4]), .B (in_25[4]), .C (in_26[4]), .YC (n_16),
       .YS (n_17));
  FAX1 g4200(.A (in_6[3]), .B (in_25[3]), .C (in_26[3]), .YC (n_14),
       .YS (n_15));
  FAX1 g4201(.A (in_12[2]), .B (in_23[2]), .C (in_24[2]), .YC (n_12),
       .YS (n_13));
  FAX1 g4202(.A (in_12[3]), .B (in_23[3]), .C (in_24[3]), .YC (n_10),
       .YS (n_11));
  HAX1 g4203(.A (in_1[2]), .B (in_0[2]), .YC (n_8), .YS (n_9));
  HAX1 g4204(.A (in_1[1]), .B (in_0[1]), .YC (n_6), .YS (n_7));
  HAX1 g4205(.A (in_31[0]), .B (in_0[0]), .YC (n_4), .YS (n_5));
  HAX1 g4206(.A (in_1[4]), .B (in_0[4]), .YC (n_2), .YS (n_3));
  HAX1 g4207(.A (in_1[3]), .B (in_0[3]), .YC (n_0), .YS (n_1));
endmodule

module counter_WIDTH5(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [4:0] out;
  output overflow;
  wire clk, en, rst;
  wire [4:0] out;
  wire overflow;
  wire n_0, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_15, n_16, n_18, n_19;
  wire n_20, n_21, n_22, n_32, n_33;
  DFFSR \out_reg[4] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_33), .Q
       (n_22));
  DFFSR \out_reg[3] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_16), .Q
       (n_21));
  INVX1 g81(.A (n_15), .Y (n_16));
  MUX2X1 g82(.A (n_13), .B (out[3]), .S (en), .Y (n_15));
  DFFSR \out_reg[2] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_11), .Q
       (n_20));
  HAX1 g85(.A (out[3]), .B (n_8), .YC (n_12), .YS (n_13));
  INVX1 g86(.A (n_10), .Y (n_11));
  MUX2X1 g87(.A (n_9), .B (out[2]), .S (en), .Y (n_10));
  DFFSR \out_reg[1] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_7), .Q
       (n_19));
  HAX1 g89(.A (out[2]), .B (n_4), .YC (n_8), .YS (n_9));
  INVX1 g90(.A (n_6), .Y (n_7));
  MUX2X1 g91(.A (n_5), .B (out[1]), .S (en), .Y (n_6));
  DFFSR \out_reg[0] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_18));
  HAX1 g93(.A (out[1]), .B (out[0]), .YC (n_4), .YS (n_5));
  INVX1 g98(.A (rst), .Y (n_3));
  BUFX2 drc_bufs118(.A (n_22), .Y (out[4]));
  BUFX2 drc_bufs119(.A (n_18), .Y (out[0]));
  BUFX2 drc_bufs120(.A (n_19), .Y (out[1]));
  BUFX2 drc_bufs121(.A (n_20), .Y (out[2]));
  BUFX2 drc_bufs122(.A (n_21), .Y (out[3]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
  XOR2X1 g128(.A (n_32), .B (out[4]), .Y (n_33));
  AND2X1 g3(.A (n_12), .B (en), .Y (n_32));
endmodule

module counter_WIDTH5_1(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [4:0] out;
  output overflow;
  wire clk, en, rst;
  wire [4:0] out;
  wire overflow;
  wire n_0, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_15, n_16, n_18, n_19;
  wire n_20, n_21, n_22, n_32, n_33;
  DFFSR \out_reg[4] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_33), .Q
       (n_22));
  DFFSR \out_reg[3] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_16), .Q
       (n_21));
  INVX1 g81(.A (n_15), .Y (n_16));
  MUX2X1 g82(.A (n_13), .B (out[3]), .S (en), .Y (n_15));
  DFFSR \out_reg[2] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_11), .Q
       (n_20));
  HAX1 g85(.A (out[3]), .B (n_8), .YC (n_12), .YS (n_13));
  INVX1 g86(.A (n_10), .Y (n_11));
  MUX2X1 g87(.A (n_9), .B (out[2]), .S (en), .Y (n_10));
  DFFSR \out_reg[1] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_7), .Q
       (n_19));
  HAX1 g89(.A (out[2]), .B (n_4), .YC (n_8), .YS (n_9));
  INVX1 g90(.A (n_6), .Y (n_7));
  MUX2X1 g91(.A (n_5), .B (out[1]), .S (en), .Y (n_6));
  DFFSR \out_reg[0] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_18));
  HAX1 g93(.A (out[1]), .B (out[0]), .YC (n_4), .YS (n_5));
  INVX1 g98(.A (rst), .Y (n_3));
  BUFX2 drc_bufs118(.A (n_22), .Y (out[4]));
  BUFX2 drc_bufs119(.A (n_18), .Y (out[0]));
  BUFX2 drc_bufs120(.A (n_19), .Y (out[1]));
  BUFX2 drc_bufs121(.A (n_20), .Y (out[2]));
  BUFX2 drc_bufs122(.A (n_21), .Y (out[3]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
  XOR2X1 g128(.A (n_32), .B (out[4]), .Y (n_33));
  AND2X1 g3(.A (n_12), .B (en), .Y (n_32));
endmodule

module counter_WIDTH5_10(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [4:0] out;
  output overflow;
  wire clk, en, rst;
  wire [4:0] out;
  wire overflow;
  wire n_0, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_15, n_16, n_18, n_19;
  wire n_20, n_21, n_22, n_32, n_33;
  DFFSR \out_reg[4] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_33), .Q
       (n_22));
  DFFSR \out_reg[3] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_16), .Q
       (n_21));
  INVX1 g81(.A (n_15), .Y (n_16));
  MUX2X1 g82(.A (n_13), .B (out[3]), .S (en), .Y (n_15));
  DFFSR \out_reg[2] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_11), .Q
       (n_20));
  HAX1 g85(.A (out[3]), .B (n_8), .YC (n_12), .YS (n_13));
  INVX1 g86(.A (n_10), .Y (n_11));
  MUX2X1 g87(.A (n_9), .B (out[2]), .S (en), .Y (n_10));
  DFFSR \out_reg[1] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_7), .Q
       (n_19));
  HAX1 g89(.A (out[2]), .B (n_4), .YC (n_8), .YS (n_9));
  INVX1 g90(.A (n_6), .Y (n_7));
  MUX2X1 g91(.A (n_5), .B (out[1]), .S (en), .Y (n_6));
  DFFSR \out_reg[0] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_18));
  HAX1 g93(.A (out[1]), .B (out[0]), .YC (n_4), .YS (n_5));
  INVX1 g98(.A (rst), .Y (n_3));
  BUFX2 drc_bufs118(.A (n_22), .Y (out[4]));
  BUFX2 drc_bufs119(.A (n_18), .Y (out[0]));
  BUFX2 drc_bufs120(.A (n_19), .Y (out[1]));
  BUFX2 drc_bufs121(.A (n_20), .Y (out[2]));
  BUFX2 drc_bufs122(.A (n_21), .Y (out[3]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
  XOR2X1 g128(.A (n_32), .B (out[4]), .Y (n_33));
  AND2X1 g3(.A (n_12), .B (en), .Y (n_32));
endmodule

module counter_WIDTH5_11(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [4:0] out;
  output overflow;
  wire clk, en, rst;
  wire [4:0] out;
  wire overflow;
  wire n_0, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_15, n_16, n_18, n_19;
  wire n_20, n_21, n_22, n_32, n_33;
  DFFSR \out_reg[4] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_33), .Q
       (n_22));
  DFFSR \out_reg[3] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_16), .Q
       (n_21));
  INVX1 g81(.A (n_15), .Y (n_16));
  MUX2X1 g82(.A (n_13), .B (out[3]), .S (en), .Y (n_15));
  DFFSR \out_reg[2] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_11), .Q
       (n_20));
  HAX1 g85(.A (out[3]), .B (n_8), .YC (n_12), .YS (n_13));
  INVX1 g86(.A (n_10), .Y (n_11));
  MUX2X1 g87(.A (n_9), .B (out[2]), .S (en), .Y (n_10));
  DFFSR \out_reg[1] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_7), .Q
       (n_19));
  HAX1 g89(.A (out[2]), .B (n_4), .YC (n_8), .YS (n_9));
  INVX1 g90(.A (n_6), .Y (n_7));
  MUX2X1 g91(.A (n_5), .B (out[1]), .S (en), .Y (n_6));
  DFFSR \out_reg[0] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_18));
  HAX1 g93(.A (out[1]), .B (out[0]), .YC (n_4), .YS (n_5));
  INVX1 g98(.A (rst), .Y (n_3));
  BUFX2 drc_bufs118(.A (n_22), .Y (out[4]));
  BUFX2 drc_bufs119(.A (n_18), .Y (out[0]));
  BUFX2 drc_bufs120(.A (n_19), .Y (out[1]));
  BUFX2 drc_bufs121(.A (n_20), .Y (out[2]));
  BUFX2 drc_bufs122(.A (n_21), .Y (out[3]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
  XOR2X1 g128(.A (n_32), .B (out[4]), .Y (n_33));
  AND2X1 g3(.A (n_12), .B (en), .Y (n_32));
endmodule

module counter_WIDTH5_12(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [4:0] out;
  output overflow;
  wire clk, en, rst;
  wire [4:0] out;
  wire overflow;
  wire n_0, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_15, n_16, n_18, n_19;
  wire n_20, n_21, n_22, n_32, n_33;
  DFFSR \out_reg[4] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_33), .Q
       (n_22));
  DFFSR \out_reg[3] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_16), .Q
       (n_21));
  INVX1 g81(.A (n_15), .Y (n_16));
  MUX2X1 g82(.A (n_13), .B (out[3]), .S (en), .Y (n_15));
  DFFSR \out_reg[2] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_11), .Q
       (n_20));
  HAX1 g85(.A (out[3]), .B (n_8), .YC (n_12), .YS (n_13));
  INVX1 g86(.A (n_10), .Y (n_11));
  MUX2X1 g87(.A (n_9), .B (out[2]), .S (en), .Y (n_10));
  DFFSR \out_reg[1] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_7), .Q
       (n_19));
  HAX1 g89(.A (out[2]), .B (n_4), .YC (n_8), .YS (n_9));
  INVX1 g90(.A (n_6), .Y (n_7));
  MUX2X1 g91(.A (n_5), .B (out[1]), .S (en), .Y (n_6));
  DFFSR \out_reg[0] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_18));
  HAX1 g93(.A (out[1]), .B (out[0]), .YC (n_4), .YS (n_5));
  INVX1 g98(.A (rst), .Y (n_3));
  BUFX2 drc_bufs118(.A (n_22), .Y (out[4]));
  BUFX2 drc_bufs119(.A (n_18), .Y (out[0]));
  BUFX2 drc_bufs120(.A (n_19), .Y (out[1]));
  BUFX2 drc_bufs121(.A (n_20), .Y (out[2]));
  BUFX2 drc_bufs122(.A (n_21), .Y (out[3]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
  XOR2X1 g128(.A (n_32), .B (out[4]), .Y (n_33));
  AND2X1 g3(.A (n_12), .B (en), .Y (n_32));
endmodule

module counter_WIDTH5_13(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [4:0] out;
  output overflow;
  wire clk, en, rst;
  wire [4:0] out;
  wire overflow;
  wire n_0, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_15, n_16, n_18, n_19;
  wire n_20, n_21, n_22, n_32, n_33;
  DFFSR \out_reg[4] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_33), .Q
       (n_22));
  DFFSR \out_reg[3] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_16), .Q
       (n_21));
  INVX1 g81(.A (n_15), .Y (n_16));
  MUX2X1 g82(.A (n_13), .B (out[3]), .S (en), .Y (n_15));
  DFFSR \out_reg[2] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_11), .Q
       (n_20));
  HAX1 g85(.A (out[3]), .B (n_8), .YC (n_12), .YS (n_13));
  INVX1 g86(.A (n_10), .Y (n_11));
  MUX2X1 g87(.A (n_9), .B (out[2]), .S (en), .Y (n_10));
  DFFSR \out_reg[1] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_7), .Q
       (n_19));
  HAX1 g89(.A (out[2]), .B (n_4), .YC (n_8), .YS (n_9));
  INVX1 g90(.A (n_6), .Y (n_7));
  MUX2X1 g91(.A (n_5), .B (out[1]), .S (en), .Y (n_6));
  DFFSR \out_reg[0] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_18));
  HAX1 g93(.A (out[1]), .B (out[0]), .YC (n_4), .YS (n_5));
  INVX1 g98(.A (rst), .Y (n_3));
  BUFX2 drc_bufs118(.A (n_22), .Y (out[4]));
  BUFX2 drc_bufs119(.A (n_18), .Y (out[0]));
  BUFX2 drc_bufs120(.A (n_19), .Y (out[1]));
  BUFX2 drc_bufs121(.A (n_20), .Y (out[2]));
  BUFX2 drc_bufs122(.A (n_21), .Y (out[3]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
  XOR2X1 g128(.A (n_32), .B (out[4]), .Y (n_33));
  AND2X1 g3(.A (n_12), .B (en), .Y (n_32));
endmodule

module counter_WIDTH5_14(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [4:0] out;
  output overflow;
  wire clk, en, rst;
  wire [4:0] out;
  wire overflow;
  wire n_0, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_15, n_16, n_18, n_19;
  wire n_20, n_21, n_22, n_32, n_33;
  DFFSR \out_reg[4] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_33), .Q
       (n_22));
  DFFSR \out_reg[3] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_16), .Q
       (n_21));
  INVX1 g81(.A (n_15), .Y (n_16));
  MUX2X1 g82(.A (n_13), .B (out[3]), .S (en), .Y (n_15));
  DFFSR \out_reg[2] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_11), .Q
       (n_20));
  HAX1 g85(.A (out[3]), .B (n_8), .YC (n_12), .YS (n_13));
  INVX1 g86(.A (n_10), .Y (n_11));
  MUX2X1 g87(.A (n_9), .B (out[2]), .S (en), .Y (n_10));
  DFFSR \out_reg[1] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_7), .Q
       (n_19));
  HAX1 g89(.A (out[2]), .B (n_4), .YC (n_8), .YS (n_9));
  INVX1 g90(.A (n_6), .Y (n_7));
  MUX2X1 g91(.A (n_5), .B (out[1]), .S (en), .Y (n_6));
  DFFSR \out_reg[0] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_18));
  HAX1 g93(.A (out[1]), .B (out[0]), .YC (n_4), .YS (n_5));
  INVX1 g98(.A (rst), .Y (n_3));
  BUFX2 drc_bufs118(.A (n_22), .Y (out[4]));
  BUFX2 drc_bufs119(.A (n_18), .Y (out[0]));
  BUFX2 drc_bufs120(.A (n_19), .Y (out[1]));
  BUFX2 drc_bufs121(.A (n_20), .Y (out[2]));
  BUFX2 drc_bufs122(.A (n_21), .Y (out[3]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
  XOR2X1 g128(.A (n_32), .B (out[4]), .Y (n_33));
  AND2X1 g3(.A (n_12), .B (en), .Y (n_32));
endmodule

module counter_WIDTH5_15(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [4:0] out;
  output overflow;
  wire clk, en, rst;
  wire [4:0] out;
  wire overflow;
  wire n_0, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_15, n_16, n_18, n_19;
  wire n_20, n_21, n_22, n_32, n_33;
  DFFSR \out_reg[4] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_33), .Q
       (n_22));
  DFFSR \out_reg[3] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_16), .Q
       (n_21));
  INVX1 g81(.A (n_15), .Y (n_16));
  MUX2X1 g82(.A (n_13), .B (out[3]), .S (en), .Y (n_15));
  DFFSR \out_reg[2] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_11), .Q
       (n_20));
  HAX1 g85(.A (out[3]), .B (n_8), .YC (n_12), .YS (n_13));
  INVX1 g86(.A (n_10), .Y (n_11));
  MUX2X1 g87(.A (n_9), .B (out[2]), .S (en), .Y (n_10));
  DFFSR \out_reg[1] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_7), .Q
       (n_19));
  HAX1 g89(.A (out[2]), .B (n_4), .YC (n_8), .YS (n_9));
  INVX1 g90(.A (n_6), .Y (n_7));
  MUX2X1 g91(.A (n_5), .B (out[1]), .S (en), .Y (n_6));
  DFFSR \out_reg[0] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_18));
  HAX1 g93(.A (out[1]), .B (out[0]), .YC (n_4), .YS (n_5));
  INVX1 g98(.A (rst), .Y (n_3));
  BUFX2 drc_bufs118(.A (n_22), .Y (out[4]));
  BUFX2 drc_bufs119(.A (n_18), .Y (out[0]));
  BUFX2 drc_bufs120(.A (n_19), .Y (out[1]));
  BUFX2 drc_bufs121(.A (n_20), .Y (out[2]));
  BUFX2 drc_bufs122(.A (n_21), .Y (out[3]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
  XOR2X1 g128(.A (n_32), .B (out[4]), .Y (n_33));
  AND2X1 g3(.A (n_12), .B (en), .Y (n_32));
endmodule

module counter_WIDTH5_16(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [4:0] out;
  output overflow;
  wire clk, en, rst;
  wire [4:0] out;
  wire overflow;
  wire n_0, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_15, n_16, n_18, n_19;
  wire n_20, n_21, n_22, n_32, n_33;
  DFFSR \out_reg[4] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_33), .Q
       (n_22));
  DFFSR \out_reg[3] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_16), .Q
       (n_21));
  INVX1 g81(.A (n_15), .Y (n_16));
  MUX2X1 g82(.A (n_13), .B (out[3]), .S (en), .Y (n_15));
  DFFSR \out_reg[2] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_11), .Q
       (n_20));
  HAX1 g85(.A (out[3]), .B (n_8), .YC (n_12), .YS (n_13));
  INVX1 g86(.A (n_10), .Y (n_11));
  MUX2X1 g87(.A (n_9), .B (out[2]), .S (en), .Y (n_10));
  DFFSR \out_reg[1] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_7), .Q
       (n_19));
  HAX1 g89(.A (out[2]), .B (n_4), .YC (n_8), .YS (n_9));
  INVX1 g90(.A (n_6), .Y (n_7));
  MUX2X1 g91(.A (n_5), .B (out[1]), .S (en), .Y (n_6));
  DFFSR \out_reg[0] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_18));
  HAX1 g93(.A (out[1]), .B (out[0]), .YC (n_4), .YS (n_5));
  INVX1 g98(.A (rst), .Y (n_3));
  BUFX2 drc_bufs118(.A (n_22), .Y (out[4]));
  BUFX2 drc_bufs119(.A (n_18), .Y (out[0]));
  BUFX2 drc_bufs120(.A (n_19), .Y (out[1]));
  BUFX2 drc_bufs121(.A (n_20), .Y (out[2]));
  BUFX2 drc_bufs122(.A (n_21), .Y (out[3]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
  XOR2X1 g128(.A (n_32), .B (out[4]), .Y (n_33));
  AND2X1 g3(.A (n_12), .B (en), .Y (n_32));
endmodule

module counter_WIDTH5_17(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [4:0] out;
  output overflow;
  wire clk, en, rst;
  wire [4:0] out;
  wire overflow;
  wire n_0, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_15, n_16, n_18, n_19;
  wire n_20, n_21, n_22, n_32, n_33;
  DFFSR \out_reg[4] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_33), .Q
       (n_22));
  DFFSR \out_reg[3] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_16), .Q
       (n_21));
  INVX1 g81(.A (n_15), .Y (n_16));
  MUX2X1 g82(.A (n_13), .B (out[3]), .S (en), .Y (n_15));
  DFFSR \out_reg[2] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_11), .Q
       (n_20));
  HAX1 g85(.A (out[3]), .B (n_8), .YC (n_12), .YS (n_13));
  INVX1 g86(.A (n_10), .Y (n_11));
  MUX2X1 g87(.A (n_9), .B (out[2]), .S (en), .Y (n_10));
  DFFSR \out_reg[1] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_7), .Q
       (n_19));
  HAX1 g89(.A (out[2]), .B (n_4), .YC (n_8), .YS (n_9));
  INVX1 g90(.A (n_6), .Y (n_7));
  MUX2X1 g91(.A (n_5), .B (out[1]), .S (en), .Y (n_6));
  DFFSR \out_reg[0] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_18));
  HAX1 g93(.A (out[1]), .B (out[0]), .YC (n_4), .YS (n_5));
  INVX1 g98(.A (rst), .Y (n_3));
  BUFX2 drc_bufs118(.A (n_22), .Y (out[4]));
  BUFX2 drc_bufs119(.A (n_18), .Y (out[0]));
  BUFX2 drc_bufs120(.A (n_19), .Y (out[1]));
  BUFX2 drc_bufs121(.A (n_20), .Y (out[2]));
  BUFX2 drc_bufs122(.A (n_21), .Y (out[3]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
  XOR2X1 g128(.A (n_32), .B (out[4]), .Y (n_33));
  AND2X1 g3(.A (n_12), .B (en), .Y (n_32));
endmodule

module counter_WIDTH5_18(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [4:0] out;
  output overflow;
  wire clk, en, rst;
  wire [4:0] out;
  wire overflow;
  wire n_0, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_15, n_16, n_18, n_19;
  wire n_20, n_21, n_22, n_32, n_33;
  DFFSR \out_reg[4] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_33), .Q
       (n_22));
  DFFSR \out_reg[3] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_16), .Q
       (n_21));
  INVX1 g81(.A (n_15), .Y (n_16));
  MUX2X1 g82(.A (n_13), .B (out[3]), .S (en), .Y (n_15));
  DFFSR \out_reg[2] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_11), .Q
       (n_20));
  HAX1 g85(.A (out[3]), .B (n_8), .YC (n_12), .YS (n_13));
  INVX1 g86(.A (n_10), .Y (n_11));
  MUX2X1 g87(.A (n_9), .B (out[2]), .S (en), .Y (n_10));
  DFFSR \out_reg[1] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_7), .Q
       (n_19));
  HAX1 g89(.A (out[2]), .B (n_4), .YC (n_8), .YS (n_9));
  INVX1 g90(.A (n_6), .Y (n_7));
  MUX2X1 g91(.A (n_5), .B (out[1]), .S (en), .Y (n_6));
  DFFSR \out_reg[0] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_18));
  HAX1 g93(.A (out[1]), .B (out[0]), .YC (n_4), .YS (n_5));
  INVX1 g98(.A (rst), .Y (n_3));
  BUFX2 drc_bufs118(.A (n_22), .Y (out[4]));
  BUFX2 drc_bufs119(.A (n_18), .Y (out[0]));
  BUFX2 drc_bufs120(.A (n_19), .Y (out[1]));
  BUFX2 drc_bufs121(.A (n_20), .Y (out[2]));
  BUFX2 drc_bufs122(.A (n_21), .Y (out[3]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
  XOR2X1 g128(.A (n_32), .B (out[4]), .Y (n_33));
  AND2X1 g3(.A (n_12), .B (en), .Y (n_32));
endmodule

module counter_WIDTH5_19(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [4:0] out;
  output overflow;
  wire clk, en, rst;
  wire [4:0] out;
  wire overflow;
  wire n_0, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_15, n_16, n_18, n_19;
  wire n_20, n_21, n_22, n_32, n_33;
  DFFSR \out_reg[4] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_33), .Q
       (n_22));
  DFFSR \out_reg[3] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_16), .Q
       (n_21));
  INVX1 g81(.A (n_15), .Y (n_16));
  MUX2X1 g82(.A (n_13), .B (out[3]), .S (en), .Y (n_15));
  DFFSR \out_reg[2] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_11), .Q
       (n_20));
  HAX1 g85(.A (out[3]), .B (n_8), .YC (n_12), .YS (n_13));
  INVX1 g86(.A (n_10), .Y (n_11));
  MUX2X1 g87(.A (n_9), .B (out[2]), .S (en), .Y (n_10));
  DFFSR \out_reg[1] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_7), .Q
       (n_19));
  HAX1 g89(.A (out[2]), .B (n_4), .YC (n_8), .YS (n_9));
  INVX1 g90(.A (n_6), .Y (n_7));
  MUX2X1 g91(.A (n_5), .B (out[1]), .S (en), .Y (n_6));
  DFFSR \out_reg[0] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_18));
  HAX1 g93(.A (out[1]), .B (out[0]), .YC (n_4), .YS (n_5));
  INVX1 g98(.A (rst), .Y (n_3));
  BUFX2 drc_bufs118(.A (n_22), .Y (out[4]));
  BUFX2 drc_bufs119(.A (n_18), .Y (out[0]));
  BUFX2 drc_bufs120(.A (n_19), .Y (out[1]));
  BUFX2 drc_bufs121(.A (n_20), .Y (out[2]));
  BUFX2 drc_bufs122(.A (n_21), .Y (out[3]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
  XOR2X1 g128(.A (n_32), .B (out[4]), .Y (n_33));
  AND2X1 g3(.A (n_12), .B (en), .Y (n_32));
endmodule

module counter_WIDTH5_2(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [4:0] out;
  output overflow;
  wire clk, en, rst;
  wire [4:0] out;
  wire overflow;
  wire n_0, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_15, n_16, n_18, n_19;
  wire n_20, n_21, n_22, n_32, n_33;
  DFFSR \out_reg[4] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_33), .Q
       (n_22));
  DFFSR \out_reg[3] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_16), .Q
       (n_21));
  INVX1 g81(.A (n_15), .Y (n_16));
  MUX2X1 g82(.A (n_13), .B (out[3]), .S (en), .Y (n_15));
  DFFSR \out_reg[2] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_11), .Q
       (n_20));
  HAX1 g85(.A (out[3]), .B (n_8), .YC (n_12), .YS (n_13));
  INVX1 g86(.A (n_10), .Y (n_11));
  MUX2X1 g87(.A (n_9), .B (out[2]), .S (en), .Y (n_10));
  DFFSR \out_reg[1] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_7), .Q
       (n_19));
  HAX1 g89(.A (out[2]), .B (n_4), .YC (n_8), .YS (n_9));
  INVX1 g90(.A (n_6), .Y (n_7));
  MUX2X1 g91(.A (n_5), .B (out[1]), .S (en), .Y (n_6));
  DFFSR \out_reg[0] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_18));
  HAX1 g93(.A (out[1]), .B (out[0]), .YC (n_4), .YS (n_5));
  INVX1 g98(.A (rst), .Y (n_3));
  BUFX2 drc_bufs118(.A (n_22), .Y (out[4]));
  BUFX2 drc_bufs119(.A (n_18), .Y (out[0]));
  BUFX2 drc_bufs120(.A (n_19), .Y (out[1]));
  BUFX2 drc_bufs121(.A (n_20), .Y (out[2]));
  BUFX2 drc_bufs122(.A (n_21), .Y (out[3]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
  XOR2X1 g128(.A (n_32), .B (out[4]), .Y (n_33));
  AND2X1 g3(.A (n_12), .B (en), .Y (n_32));
endmodule

module counter_WIDTH5_20(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [4:0] out;
  output overflow;
  wire clk, en, rst;
  wire [4:0] out;
  wire overflow;
  wire n_0, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_15, n_16, n_18, n_19;
  wire n_20, n_21, n_22, n_32, n_33;
  DFFSR \out_reg[4] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_33), .Q
       (n_22));
  DFFSR \out_reg[3] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_16), .Q
       (n_21));
  INVX1 g81(.A (n_15), .Y (n_16));
  MUX2X1 g82(.A (n_13), .B (out[3]), .S (en), .Y (n_15));
  DFFSR \out_reg[2] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_11), .Q
       (n_20));
  HAX1 g85(.A (out[3]), .B (n_8), .YC (n_12), .YS (n_13));
  INVX1 g86(.A (n_10), .Y (n_11));
  MUX2X1 g87(.A (n_9), .B (out[2]), .S (en), .Y (n_10));
  DFFSR \out_reg[1] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_7), .Q
       (n_19));
  HAX1 g89(.A (out[2]), .B (n_4), .YC (n_8), .YS (n_9));
  INVX1 g90(.A (n_6), .Y (n_7));
  MUX2X1 g91(.A (n_5), .B (out[1]), .S (en), .Y (n_6));
  DFFSR \out_reg[0] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_18));
  HAX1 g93(.A (out[1]), .B (out[0]), .YC (n_4), .YS (n_5));
  INVX1 g98(.A (rst), .Y (n_3));
  BUFX2 drc_bufs118(.A (n_22), .Y (out[4]));
  BUFX2 drc_bufs119(.A (n_18), .Y (out[0]));
  BUFX2 drc_bufs120(.A (n_19), .Y (out[1]));
  BUFX2 drc_bufs121(.A (n_20), .Y (out[2]));
  BUFX2 drc_bufs122(.A (n_21), .Y (out[3]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
  XOR2X1 g128(.A (n_32), .B (out[4]), .Y (n_33));
  AND2X1 g3(.A (n_12), .B (en), .Y (n_32));
endmodule

module counter_WIDTH5_21(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [4:0] out;
  output overflow;
  wire clk, en, rst;
  wire [4:0] out;
  wire overflow;
  wire n_0, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_15, n_16, n_18, n_19;
  wire n_20, n_21, n_22, n_32, n_33;
  DFFSR \out_reg[4] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_33), .Q
       (n_22));
  DFFSR \out_reg[3] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_16), .Q
       (n_21));
  INVX1 g81(.A (n_15), .Y (n_16));
  MUX2X1 g82(.A (n_13), .B (out[3]), .S (en), .Y (n_15));
  DFFSR \out_reg[2] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_11), .Q
       (n_20));
  HAX1 g85(.A (out[3]), .B (n_8), .YC (n_12), .YS (n_13));
  INVX1 g86(.A (n_10), .Y (n_11));
  MUX2X1 g87(.A (n_9), .B (out[2]), .S (en), .Y (n_10));
  DFFSR \out_reg[1] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_7), .Q
       (n_19));
  HAX1 g89(.A (out[2]), .B (n_4), .YC (n_8), .YS (n_9));
  INVX1 g90(.A (n_6), .Y (n_7));
  MUX2X1 g91(.A (n_5), .B (out[1]), .S (en), .Y (n_6));
  DFFSR \out_reg[0] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_18));
  HAX1 g93(.A (out[1]), .B (out[0]), .YC (n_4), .YS (n_5));
  INVX1 g98(.A (rst), .Y (n_3));
  BUFX2 drc_bufs118(.A (n_22), .Y (out[4]));
  BUFX2 drc_bufs119(.A (n_18), .Y (out[0]));
  BUFX2 drc_bufs120(.A (n_19), .Y (out[1]));
  BUFX2 drc_bufs121(.A (n_20), .Y (out[2]));
  BUFX2 drc_bufs122(.A (n_21), .Y (out[3]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
  XOR2X1 g128(.A (n_32), .B (out[4]), .Y (n_33));
  AND2X1 g3(.A (n_12), .B (en), .Y (n_32));
endmodule

module counter_WIDTH5_22(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [4:0] out;
  output overflow;
  wire clk, en, rst;
  wire [4:0] out;
  wire overflow;
  wire n_0, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_15, n_16, n_18, n_19;
  wire n_20, n_21, n_22, n_32, n_33;
  DFFSR \out_reg[4] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_33), .Q
       (n_22));
  DFFSR \out_reg[3] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_16), .Q
       (n_21));
  INVX1 g81(.A (n_15), .Y (n_16));
  MUX2X1 g82(.A (n_13), .B (out[3]), .S (en), .Y (n_15));
  DFFSR \out_reg[2] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_11), .Q
       (n_20));
  HAX1 g85(.A (out[3]), .B (n_8), .YC (n_12), .YS (n_13));
  INVX1 g86(.A (n_10), .Y (n_11));
  MUX2X1 g87(.A (n_9), .B (out[2]), .S (en), .Y (n_10));
  DFFSR \out_reg[1] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_7), .Q
       (n_19));
  HAX1 g89(.A (out[2]), .B (n_4), .YC (n_8), .YS (n_9));
  INVX1 g90(.A (n_6), .Y (n_7));
  MUX2X1 g91(.A (n_5), .B (out[1]), .S (en), .Y (n_6));
  DFFSR \out_reg[0] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_18));
  HAX1 g93(.A (out[1]), .B (out[0]), .YC (n_4), .YS (n_5));
  INVX1 g98(.A (rst), .Y (n_3));
  BUFX2 drc_bufs118(.A (n_22), .Y (out[4]));
  BUFX2 drc_bufs119(.A (n_18), .Y (out[0]));
  BUFX2 drc_bufs120(.A (n_19), .Y (out[1]));
  BUFX2 drc_bufs121(.A (n_20), .Y (out[2]));
  BUFX2 drc_bufs122(.A (n_21), .Y (out[3]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
  XOR2X1 g128(.A (n_32), .B (out[4]), .Y (n_33));
  AND2X1 g3(.A (n_12), .B (en), .Y (n_32));
endmodule

module counter_WIDTH5_23(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [4:0] out;
  output overflow;
  wire clk, en, rst;
  wire [4:0] out;
  wire overflow;
  wire n_0, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_15, n_16, n_18, n_19;
  wire n_20, n_21, n_22, n_32, n_33;
  DFFSR \out_reg[4] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_33), .Q
       (n_22));
  DFFSR \out_reg[3] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_16), .Q
       (n_21));
  INVX1 g81(.A (n_15), .Y (n_16));
  MUX2X1 g82(.A (n_13), .B (out[3]), .S (en), .Y (n_15));
  DFFSR \out_reg[2] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_11), .Q
       (n_20));
  HAX1 g85(.A (out[3]), .B (n_8), .YC (n_12), .YS (n_13));
  INVX1 g86(.A (n_10), .Y (n_11));
  MUX2X1 g87(.A (n_9), .B (out[2]), .S (en), .Y (n_10));
  DFFSR \out_reg[1] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_7), .Q
       (n_19));
  HAX1 g89(.A (out[2]), .B (n_4), .YC (n_8), .YS (n_9));
  INVX1 g90(.A (n_6), .Y (n_7));
  MUX2X1 g91(.A (n_5), .B (out[1]), .S (en), .Y (n_6));
  DFFSR \out_reg[0] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_18));
  HAX1 g93(.A (out[1]), .B (out[0]), .YC (n_4), .YS (n_5));
  INVX1 g98(.A (rst), .Y (n_3));
  BUFX2 drc_bufs118(.A (n_22), .Y (out[4]));
  BUFX2 drc_bufs119(.A (n_18), .Y (out[0]));
  BUFX2 drc_bufs120(.A (n_19), .Y (out[1]));
  BUFX2 drc_bufs121(.A (n_20), .Y (out[2]));
  BUFX2 drc_bufs122(.A (n_21), .Y (out[3]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
  XOR2X1 g128(.A (n_32), .B (out[4]), .Y (n_33));
  AND2X1 g3(.A (n_12), .B (en), .Y (n_32));
endmodule

module counter_WIDTH5_24(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [4:0] out;
  output overflow;
  wire clk, en, rst;
  wire [4:0] out;
  wire overflow;
  wire n_0, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_15, n_16, n_18, n_19;
  wire n_20, n_21, n_22, n_32, n_33;
  DFFSR \out_reg[4] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_33), .Q
       (n_22));
  DFFSR \out_reg[3] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_16), .Q
       (n_21));
  INVX1 g81(.A (n_15), .Y (n_16));
  MUX2X1 g82(.A (n_13), .B (out[3]), .S (en), .Y (n_15));
  DFFSR \out_reg[2] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_11), .Q
       (n_20));
  HAX1 g85(.A (out[3]), .B (n_8), .YC (n_12), .YS (n_13));
  INVX1 g86(.A (n_10), .Y (n_11));
  MUX2X1 g87(.A (n_9), .B (out[2]), .S (en), .Y (n_10));
  DFFSR \out_reg[1] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_7), .Q
       (n_19));
  HAX1 g89(.A (out[2]), .B (n_4), .YC (n_8), .YS (n_9));
  INVX1 g90(.A (n_6), .Y (n_7));
  MUX2X1 g91(.A (n_5), .B (out[1]), .S (en), .Y (n_6));
  DFFSR \out_reg[0] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_18));
  HAX1 g93(.A (out[1]), .B (out[0]), .YC (n_4), .YS (n_5));
  INVX1 g98(.A (rst), .Y (n_3));
  BUFX2 drc_bufs118(.A (n_22), .Y (out[4]));
  BUFX2 drc_bufs119(.A (n_18), .Y (out[0]));
  BUFX2 drc_bufs120(.A (n_19), .Y (out[1]));
  BUFX2 drc_bufs121(.A (n_20), .Y (out[2]));
  BUFX2 drc_bufs122(.A (n_21), .Y (out[3]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
  XOR2X1 g128(.A (n_32), .B (out[4]), .Y (n_33));
  AND2X1 g3(.A (n_12), .B (en), .Y (n_32));
endmodule

module counter_WIDTH5_25(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [4:0] out;
  output overflow;
  wire clk, en, rst;
  wire [4:0] out;
  wire overflow;
  wire n_0, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_15, n_16, n_18, n_19;
  wire n_20, n_21, n_22, n_32, n_33;
  DFFSR \out_reg[4] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_33), .Q
       (n_22));
  DFFSR \out_reg[3] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_16), .Q
       (n_21));
  INVX1 g81(.A (n_15), .Y (n_16));
  MUX2X1 g82(.A (n_13), .B (out[3]), .S (en), .Y (n_15));
  DFFSR \out_reg[2] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_11), .Q
       (n_20));
  HAX1 g85(.A (out[3]), .B (n_8), .YC (n_12), .YS (n_13));
  INVX1 g86(.A (n_10), .Y (n_11));
  MUX2X1 g87(.A (n_9), .B (out[2]), .S (en), .Y (n_10));
  DFFSR \out_reg[1] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_7), .Q
       (n_19));
  HAX1 g89(.A (out[2]), .B (n_4), .YC (n_8), .YS (n_9));
  INVX1 g90(.A (n_6), .Y (n_7));
  MUX2X1 g91(.A (n_5), .B (out[1]), .S (en), .Y (n_6));
  DFFSR \out_reg[0] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_18));
  HAX1 g93(.A (out[1]), .B (out[0]), .YC (n_4), .YS (n_5));
  INVX1 g98(.A (rst), .Y (n_3));
  BUFX2 drc_bufs118(.A (n_22), .Y (out[4]));
  BUFX2 drc_bufs119(.A (n_18), .Y (out[0]));
  BUFX2 drc_bufs120(.A (n_19), .Y (out[1]));
  BUFX2 drc_bufs121(.A (n_20), .Y (out[2]));
  BUFX2 drc_bufs122(.A (n_21), .Y (out[3]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
  XOR2X1 g128(.A (n_32), .B (out[4]), .Y (n_33));
  AND2X1 g3(.A (n_12), .B (en), .Y (n_32));
endmodule

module counter_WIDTH5_26(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [4:0] out;
  output overflow;
  wire clk, en, rst;
  wire [4:0] out;
  wire overflow;
  wire n_0, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_15, n_16, n_18, n_19;
  wire n_20, n_21, n_22, n_32, n_33;
  DFFSR \out_reg[4] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_33), .Q
       (n_22));
  DFFSR \out_reg[3] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_16), .Q
       (n_21));
  INVX1 g81(.A (n_15), .Y (n_16));
  MUX2X1 g82(.A (n_13), .B (out[3]), .S (en), .Y (n_15));
  DFFSR \out_reg[2] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_11), .Q
       (n_20));
  HAX1 g85(.A (out[3]), .B (n_8), .YC (n_12), .YS (n_13));
  INVX1 g86(.A (n_10), .Y (n_11));
  MUX2X1 g87(.A (n_9), .B (out[2]), .S (en), .Y (n_10));
  DFFSR \out_reg[1] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_7), .Q
       (n_19));
  HAX1 g89(.A (out[2]), .B (n_4), .YC (n_8), .YS (n_9));
  INVX1 g90(.A (n_6), .Y (n_7));
  MUX2X1 g91(.A (n_5), .B (out[1]), .S (en), .Y (n_6));
  DFFSR \out_reg[0] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_18));
  HAX1 g93(.A (out[1]), .B (out[0]), .YC (n_4), .YS (n_5));
  INVX1 g98(.A (rst), .Y (n_3));
  BUFX2 drc_bufs118(.A (n_22), .Y (out[4]));
  BUFX2 drc_bufs119(.A (n_18), .Y (out[0]));
  BUFX2 drc_bufs120(.A (n_19), .Y (out[1]));
  BUFX2 drc_bufs121(.A (n_20), .Y (out[2]));
  BUFX2 drc_bufs122(.A (n_21), .Y (out[3]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
  XOR2X1 g128(.A (n_32), .B (out[4]), .Y (n_33));
  AND2X1 g3(.A (n_12), .B (en), .Y (n_32));
endmodule

module counter_WIDTH5_27(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [4:0] out;
  output overflow;
  wire clk, en, rst;
  wire [4:0] out;
  wire overflow;
  wire n_0, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_15, n_16, n_18, n_19;
  wire n_20, n_21, n_22, n_32, n_33;
  DFFSR \out_reg[4] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_33), .Q
       (n_22));
  DFFSR \out_reg[3] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_16), .Q
       (n_21));
  INVX1 g81(.A (n_15), .Y (n_16));
  MUX2X1 g82(.A (n_13), .B (out[3]), .S (en), .Y (n_15));
  DFFSR \out_reg[2] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_11), .Q
       (n_20));
  HAX1 g85(.A (out[3]), .B (n_8), .YC (n_12), .YS (n_13));
  INVX1 g86(.A (n_10), .Y (n_11));
  MUX2X1 g87(.A (n_9), .B (out[2]), .S (en), .Y (n_10));
  DFFSR \out_reg[1] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_7), .Q
       (n_19));
  HAX1 g89(.A (out[2]), .B (n_4), .YC (n_8), .YS (n_9));
  INVX1 g90(.A (n_6), .Y (n_7));
  MUX2X1 g91(.A (n_5), .B (out[1]), .S (en), .Y (n_6));
  DFFSR \out_reg[0] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_18));
  HAX1 g93(.A (out[1]), .B (out[0]), .YC (n_4), .YS (n_5));
  INVX1 g98(.A (rst), .Y (n_3));
  BUFX2 drc_bufs118(.A (n_22), .Y (out[4]));
  BUFX2 drc_bufs119(.A (n_18), .Y (out[0]));
  BUFX2 drc_bufs120(.A (n_19), .Y (out[1]));
  BUFX2 drc_bufs121(.A (n_20), .Y (out[2]));
  BUFX2 drc_bufs122(.A (n_21), .Y (out[3]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
  XOR2X1 g128(.A (n_32), .B (out[4]), .Y (n_33));
  AND2X1 g3(.A (n_12), .B (en), .Y (n_32));
endmodule

module counter_WIDTH5_28(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [4:0] out;
  output overflow;
  wire clk, en, rst;
  wire [4:0] out;
  wire overflow;
  wire n_0, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_15, n_16, n_18, n_19;
  wire n_20, n_21, n_22, n_32, n_33;
  DFFSR \out_reg[4] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_33), .Q
       (n_22));
  DFFSR \out_reg[3] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_16), .Q
       (n_21));
  INVX1 g81(.A (n_15), .Y (n_16));
  MUX2X1 g82(.A (n_13), .B (out[3]), .S (en), .Y (n_15));
  DFFSR \out_reg[2] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_11), .Q
       (n_20));
  HAX1 g85(.A (out[3]), .B (n_8), .YC (n_12), .YS (n_13));
  INVX1 g86(.A (n_10), .Y (n_11));
  MUX2X1 g87(.A (n_9), .B (out[2]), .S (en), .Y (n_10));
  DFFSR \out_reg[1] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_7), .Q
       (n_19));
  HAX1 g89(.A (out[2]), .B (n_4), .YC (n_8), .YS (n_9));
  INVX1 g90(.A (n_6), .Y (n_7));
  MUX2X1 g91(.A (n_5), .B (out[1]), .S (en), .Y (n_6));
  DFFSR \out_reg[0] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_18));
  HAX1 g93(.A (out[1]), .B (out[0]), .YC (n_4), .YS (n_5));
  INVX1 g98(.A (rst), .Y (n_3));
  BUFX2 drc_bufs118(.A (n_22), .Y (out[4]));
  BUFX2 drc_bufs119(.A (n_18), .Y (out[0]));
  BUFX2 drc_bufs120(.A (n_19), .Y (out[1]));
  BUFX2 drc_bufs121(.A (n_20), .Y (out[2]));
  BUFX2 drc_bufs122(.A (n_21), .Y (out[3]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
  XOR2X1 g128(.A (n_32), .B (out[4]), .Y (n_33));
  AND2X1 g3(.A (n_12), .B (en), .Y (n_32));
endmodule

module counter_WIDTH5_29(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [4:0] out;
  output overflow;
  wire clk, en, rst;
  wire [4:0] out;
  wire overflow;
  wire n_0, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_15, n_16, n_18, n_19;
  wire n_20, n_21, n_22, n_32, n_33;
  DFFSR \out_reg[4] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_33), .Q
       (n_22));
  DFFSR \out_reg[3] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_16), .Q
       (n_21));
  INVX1 g81(.A (n_15), .Y (n_16));
  MUX2X1 g82(.A (n_13), .B (out[3]), .S (en), .Y (n_15));
  DFFSR \out_reg[2] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_11), .Q
       (n_20));
  HAX1 g85(.A (out[3]), .B (n_8), .YC (n_12), .YS (n_13));
  INVX1 g86(.A (n_10), .Y (n_11));
  MUX2X1 g87(.A (n_9), .B (out[2]), .S (en), .Y (n_10));
  DFFSR \out_reg[1] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_7), .Q
       (n_19));
  HAX1 g89(.A (out[2]), .B (n_4), .YC (n_8), .YS (n_9));
  INVX1 g90(.A (n_6), .Y (n_7));
  MUX2X1 g91(.A (n_5), .B (out[1]), .S (en), .Y (n_6));
  DFFSR \out_reg[0] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_18));
  HAX1 g93(.A (out[1]), .B (out[0]), .YC (n_4), .YS (n_5));
  INVX1 g98(.A (rst), .Y (n_3));
  BUFX2 drc_bufs118(.A (n_22), .Y (out[4]));
  BUFX2 drc_bufs119(.A (n_18), .Y (out[0]));
  BUFX2 drc_bufs120(.A (n_19), .Y (out[1]));
  BUFX2 drc_bufs121(.A (n_20), .Y (out[2]));
  BUFX2 drc_bufs122(.A (n_21), .Y (out[3]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
  XOR2X1 g128(.A (n_32), .B (out[4]), .Y (n_33));
  AND2X1 g3(.A (n_12), .B (en), .Y (n_32));
endmodule

module counter_WIDTH5_3(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [4:0] out;
  output overflow;
  wire clk, en, rst;
  wire [4:0] out;
  wire overflow;
  wire n_0, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_15, n_16, n_18, n_19;
  wire n_20, n_21, n_22, n_32, n_33;
  DFFSR \out_reg[4] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_33), .Q
       (n_22));
  DFFSR \out_reg[3] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_16), .Q
       (n_21));
  INVX1 g81(.A (n_15), .Y (n_16));
  MUX2X1 g82(.A (n_13), .B (out[3]), .S (en), .Y (n_15));
  DFFSR \out_reg[2] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_11), .Q
       (n_20));
  HAX1 g85(.A (out[3]), .B (n_8), .YC (n_12), .YS (n_13));
  INVX1 g86(.A (n_10), .Y (n_11));
  MUX2X1 g87(.A (n_9), .B (out[2]), .S (en), .Y (n_10));
  DFFSR \out_reg[1] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_7), .Q
       (n_19));
  HAX1 g89(.A (out[2]), .B (n_4), .YC (n_8), .YS (n_9));
  INVX1 g90(.A (n_6), .Y (n_7));
  MUX2X1 g91(.A (n_5), .B (out[1]), .S (en), .Y (n_6));
  DFFSR \out_reg[0] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_18));
  HAX1 g93(.A (out[1]), .B (out[0]), .YC (n_4), .YS (n_5));
  INVX1 g98(.A (rst), .Y (n_3));
  BUFX2 drc_bufs118(.A (n_22), .Y (out[4]));
  BUFX2 drc_bufs119(.A (n_18), .Y (out[0]));
  BUFX2 drc_bufs120(.A (n_19), .Y (out[1]));
  BUFX2 drc_bufs121(.A (n_20), .Y (out[2]));
  BUFX2 drc_bufs122(.A (n_21), .Y (out[3]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
  XOR2X1 g128(.A (n_32), .B (out[4]), .Y (n_33));
  AND2X1 g3(.A (n_12), .B (en), .Y (n_32));
endmodule

module counter_WIDTH5_30(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [4:0] out;
  output overflow;
  wire clk, en, rst;
  wire [4:0] out;
  wire overflow;
  wire n_0, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_15, n_16, n_18, n_19;
  wire n_20, n_21, n_22, n_32, n_33;
  DFFSR \out_reg[4] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_33), .Q
       (n_22));
  DFFSR \out_reg[3] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_16), .Q
       (n_21));
  INVX1 g81(.A (n_15), .Y (n_16));
  MUX2X1 g82(.A (n_13), .B (out[3]), .S (en), .Y (n_15));
  DFFSR \out_reg[2] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_11), .Q
       (n_20));
  HAX1 g85(.A (out[3]), .B (n_8), .YC (n_12), .YS (n_13));
  INVX1 g86(.A (n_10), .Y (n_11));
  MUX2X1 g87(.A (n_9), .B (out[2]), .S (en), .Y (n_10));
  DFFSR \out_reg[1] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_7), .Q
       (n_19));
  HAX1 g89(.A (out[2]), .B (n_4), .YC (n_8), .YS (n_9));
  INVX1 g90(.A (n_6), .Y (n_7));
  MUX2X1 g91(.A (n_5), .B (out[1]), .S (en), .Y (n_6));
  DFFSR \out_reg[0] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_18));
  HAX1 g93(.A (out[1]), .B (out[0]), .YC (n_4), .YS (n_5));
  INVX1 g98(.A (rst), .Y (n_3));
  BUFX2 drc_bufs118(.A (n_22), .Y (out[4]));
  BUFX2 drc_bufs119(.A (n_18), .Y (out[0]));
  BUFX2 drc_bufs120(.A (n_19), .Y (out[1]));
  BUFX2 drc_bufs121(.A (n_20), .Y (out[2]));
  BUFX2 drc_bufs122(.A (n_21), .Y (out[3]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
  XOR2X1 g128(.A (n_32), .B (out[4]), .Y (n_33));
  AND2X1 g3(.A (n_12), .B (en), .Y (n_32));
endmodule

module counter_WIDTH5_31(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [4:0] out;
  output overflow;
  wire clk, en, rst;
  wire [4:0] out;
  wire overflow;
  wire n_0, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_15, n_16, n_18, n_19;
  wire n_20, n_21, n_22, n_32, n_33;
  DFFSR \out_reg[4] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_33), .Q
       (n_22));
  DFFSR \out_reg[3] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_16), .Q
       (n_21));
  INVX1 g81(.A (n_15), .Y (n_16));
  MUX2X1 g82(.A (n_13), .B (out[3]), .S (en), .Y (n_15));
  DFFSR \out_reg[2] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_11), .Q
       (n_20));
  HAX1 g85(.A (out[3]), .B (n_8), .YC (n_12), .YS (n_13));
  INVX1 g86(.A (n_10), .Y (n_11));
  MUX2X1 g87(.A (n_9), .B (out[2]), .S (en), .Y (n_10));
  DFFSR \out_reg[1] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_7), .Q
       (n_19));
  HAX1 g89(.A (out[2]), .B (n_4), .YC (n_8), .YS (n_9));
  INVX1 g90(.A (n_6), .Y (n_7));
  MUX2X1 g91(.A (n_5), .B (out[1]), .S (en), .Y (n_6));
  DFFSR \out_reg[0] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_18));
  HAX1 g93(.A (out[1]), .B (out[0]), .YC (n_4), .YS (n_5));
  INVX1 g98(.A (rst), .Y (n_3));
  BUFX2 drc_bufs118(.A (n_22), .Y (out[4]));
  BUFX2 drc_bufs119(.A (n_18), .Y (out[0]));
  BUFX2 drc_bufs120(.A (n_19), .Y (out[1]));
  BUFX2 drc_bufs121(.A (n_20), .Y (out[2]));
  BUFX2 drc_bufs122(.A (n_21), .Y (out[3]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
  XOR2X1 g128(.A (n_32), .B (out[4]), .Y (n_33));
  AND2X1 g3(.A (n_12), .B (en), .Y (n_32));
endmodule

module counter_WIDTH5_4(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [4:0] out;
  output overflow;
  wire clk, en, rst;
  wire [4:0] out;
  wire overflow;
  wire n_0, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_15, n_16, n_18, n_19;
  wire n_20, n_21, n_22, n_32, n_33;
  DFFSR \out_reg[4] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_33), .Q
       (n_22));
  DFFSR \out_reg[3] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_16), .Q
       (n_21));
  INVX1 g81(.A (n_15), .Y (n_16));
  MUX2X1 g82(.A (n_13), .B (out[3]), .S (en), .Y (n_15));
  DFFSR \out_reg[2] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_11), .Q
       (n_20));
  HAX1 g85(.A (out[3]), .B (n_8), .YC (n_12), .YS (n_13));
  INVX1 g86(.A (n_10), .Y (n_11));
  MUX2X1 g87(.A (n_9), .B (out[2]), .S (en), .Y (n_10));
  DFFSR \out_reg[1] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_7), .Q
       (n_19));
  HAX1 g89(.A (out[2]), .B (n_4), .YC (n_8), .YS (n_9));
  INVX1 g90(.A (n_6), .Y (n_7));
  MUX2X1 g91(.A (n_5), .B (out[1]), .S (en), .Y (n_6));
  DFFSR \out_reg[0] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_18));
  HAX1 g93(.A (out[1]), .B (out[0]), .YC (n_4), .YS (n_5));
  INVX1 g98(.A (rst), .Y (n_3));
  BUFX2 drc_bufs118(.A (n_22), .Y (out[4]));
  BUFX2 drc_bufs119(.A (n_18), .Y (out[0]));
  BUFX2 drc_bufs120(.A (n_19), .Y (out[1]));
  BUFX2 drc_bufs121(.A (n_20), .Y (out[2]));
  BUFX2 drc_bufs122(.A (n_21), .Y (out[3]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
  XOR2X1 g128(.A (n_32), .B (out[4]), .Y (n_33));
  AND2X1 g3(.A (n_12), .B (en), .Y (n_32));
endmodule

module counter_WIDTH5_5(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [4:0] out;
  output overflow;
  wire clk, en, rst;
  wire [4:0] out;
  wire overflow;
  wire n_0, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_15, n_16, n_18, n_19;
  wire n_20, n_21, n_22, n_32, n_33;
  DFFSR \out_reg[4] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_33), .Q
       (n_22));
  DFFSR \out_reg[3] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_16), .Q
       (n_21));
  INVX1 g81(.A (n_15), .Y (n_16));
  MUX2X1 g82(.A (n_13), .B (out[3]), .S (en), .Y (n_15));
  DFFSR \out_reg[2] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_11), .Q
       (n_20));
  HAX1 g85(.A (out[3]), .B (n_8), .YC (n_12), .YS (n_13));
  INVX1 g86(.A (n_10), .Y (n_11));
  MUX2X1 g87(.A (n_9), .B (out[2]), .S (en), .Y (n_10));
  DFFSR \out_reg[1] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_7), .Q
       (n_19));
  HAX1 g89(.A (out[2]), .B (n_4), .YC (n_8), .YS (n_9));
  INVX1 g90(.A (n_6), .Y (n_7));
  MUX2X1 g91(.A (n_5), .B (out[1]), .S (en), .Y (n_6));
  DFFSR \out_reg[0] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_18));
  HAX1 g93(.A (out[1]), .B (out[0]), .YC (n_4), .YS (n_5));
  INVX1 g98(.A (rst), .Y (n_3));
  BUFX2 drc_bufs118(.A (n_22), .Y (out[4]));
  BUFX2 drc_bufs119(.A (n_18), .Y (out[0]));
  BUFX2 drc_bufs120(.A (n_19), .Y (out[1]));
  BUFX2 drc_bufs121(.A (n_20), .Y (out[2]));
  BUFX2 drc_bufs122(.A (n_21), .Y (out[3]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
  XOR2X1 g128(.A (n_32), .B (out[4]), .Y (n_33));
  AND2X1 g3(.A (n_12), .B (en), .Y (n_32));
endmodule

module counter_WIDTH5_6(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [4:0] out;
  output overflow;
  wire clk, en, rst;
  wire [4:0] out;
  wire overflow;
  wire n_0, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_15, n_16, n_18, n_19;
  wire n_20, n_21, n_22, n_32, n_33;
  DFFSR \out_reg[4] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_33), .Q
       (n_22));
  DFFSR \out_reg[3] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_16), .Q
       (n_21));
  INVX1 g81(.A (n_15), .Y (n_16));
  MUX2X1 g82(.A (n_13), .B (out[3]), .S (en), .Y (n_15));
  DFFSR \out_reg[2] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_11), .Q
       (n_20));
  HAX1 g85(.A (out[3]), .B (n_8), .YC (n_12), .YS (n_13));
  INVX1 g86(.A (n_10), .Y (n_11));
  MUX2X1 g87(.A (n_9), .B (out[2]), .S (en), .Y (n_10));
  DFFSR \out_reg[1] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_7), .Q
       (n_19));
  HAX1 g89(.A (out[2]), .B (n_4), .YC (n_8), .YS (n_9));
  INVX1 g90(.A (n_6), .Y (n_7));
  MUX2X1 g91(.A (n_5), .B (out[1]), .S (en), .Y (n_6));
  DFFSR \out_reg[0] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_18));
  HAX1 g93(.A (out[1]), .B (out[0]), .YC (n_4), .YS (n_5));
  INVX1 g98(.A (rst), .Y (n_3));
  BUFX2 drc_bufs118(.A (n_22), .Y (out[4]));
  BUFX2 drc_bufs119(.A (n_18), .Y (out[0]));
  BUFX2 drc_bufs120(.A (n_19), .Y (out[1]));
  BUFX2 drc_bufs121(.A (n_20), .Y (out[2]));
  BUFX2 drc_bufs122(.A (n_21), .Y (out[3]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
  XOR2X1 g128(.A (n_32), .B (out[4]), .Y (n_33));
  AND2X1 g3(.A (n_12), .B (en), .Y (n_32));
endmodule

module counter_WIDTH5_7(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [4:0] out;
  output overflow;
  wire clk, en, rst;
  wire [4:0] out;
  wire overflow;
  wire n_0, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_15, n_16, n_18, n_19;
  wire n_20, n_21, n_22, n_32, n_33;
  DFFSR \out_reg[4] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_33), .Q
       (n_22));
  DFFSR \out_reg[3] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_16), .Q
       (n_21));
  INVX1 g81(.A (n_15), .Y (n_16));
  MUX2X1 g82(.A (n_13), .B (out[3]), .S (en), .Y (n_15));
  DFFSR \out_reg[2] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_11), .Q
       (n_20));
  HAX1 g85(.A (out[3]), .B (n_8), .YC (n_12), .YS (n_13));
  INVX1 g86(.A (n_10), .Y (n_11));
  MUX2X1 g87(.A (n_9), .B (out[2]), .S (en), .Y (n_10));
  DFFSR \out_reg[1] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_7), .Q
       (n_19));
  HAX1 g89(.A (out[2]), .B (n_4), .YC (n_8), .YS (n_9));
  INVX1 g90(.A (n_6), .Y (n_7));
  MUX2X1 g91(.A (n_5), .B (out[1]), .S (en), .Y (n_6));
  DFFSR \out_reg[0] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_18));
  HAX1 g93(.A (out[1]), .B (out[0]), .YC (n_4), .YS (n_5));
  INVX1 g98(.A (rst), .Y (n_3));
  BUFX2 drc_bufs118(.A (n_22), .Y (out[4]));
  BUFX2 drc_bufs119(.A (n_18), .Y (out[0]));
  BUFX2 drc_bufs120(.A (n_19), .Y (out[1]));
  BUFX2 drc_bufs121(.A (n_20), .Y (out[2]));
  BUFX2 drc_bufs122(.A (n_21), .Y (out[3]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
  XOR2X1 g128(.A (n_32), .B (out[4]), .Y (n_33));
  AND2X1 g3(.A (n_12), .B (en), .Y (n_32));
endmodule

module counter_WIDTH5_8(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [4:0] out;
  output overflow;
  wire clk, en, rst;
  wire [4:0] out;
  wire overflow;
  wire n_0, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_15, n_16, n_18, n_19;
  wire n_20, n_21, n_22, n_32, n_33;
  DFFSR \out_reg[4] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_33), .Q
       (n_22));
  DFFSR \out_reg[3] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_16), .Q
       (n_21));
  INVX1 g81(.A (n_15), .Y (n_16));
  MUX2X1 g82(.A (n_13), .B (out[3]), .S (en), .Y (n_15));
  DFFSR \out_reg[2] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_11), .Q
       (n_20));
  HAX1 g85(.A (out[3]), .B (n_8), .YC (n_12), .YS (n_13));
  INVX1 g86(.A (n_10), .Y (n_11));
  MUX2X1 g87(.A (n_9), .B (out[2]), .S (en), .Y (n_10));
  DFFSR \out_reg[1] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_7), .Q
       (n_19));
  HAX1 g89(.A (out[2]), .B (n_4), .YC (n_8), .YS (n_9));
  INVX1 g90(.A (n_6), .Y (n_7));
  MUX2X1 g91(.A (n_5), .B (out[1]), .S (en), .Y (n_6));
  DFFSR \out_reg[0] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_18));
  HAX1 g93(.A (out[1]), .B (out[0]), .YC (n_4), .YS (n_5));
  INVX1 g98(.A (rst), .Y (n_3));
  BUFX2 drc_bufs118(.A (n_22), .Y (out[4]));
  BUFX2 drc_bufs119(.A (n_18), .Y (out[0]));
  BUFX2 drc_bufs120(.A (n_19), .Y (out[1]));
  BUFX2 drc_bufs121(.A (n_20), .Y (out[2]));
  BUFX2 drc_bufs122(.A (n_21), .Y (out[3]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
  XOR2X1 g128(.A (n_32), .B (out[4]), .Y (n_33));
  AND2X1 g3(.A (n_12), .B (en), .Y (n_32));
endmodule

module counter_WIDTH5_9(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [4:0] out;
  output overflow;
  wire clk, en, rst;
  wire [4:0] out;
  wire overflow;
  wire n_0, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_15, n_16, n_18, n_19;
  wire n_20, n_21, n_22, n_32, n_33;
  DFFSR \out_reg[4] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_33), .Q
       (n_22));
  DFFSR \out_reg[3] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_16), .Q
       (n_21));
  INVX1 g81(.A (n_15), .Y (n_16));
  MUX2X1 g82(.A (n_13), .B (out[3]), .S (en), .Y (n_15));
  DFFSR \out_reg[2] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_11), .Q
       (n_20));
  HAX1 g85(.A (out[3]), .B (n_8), .YC (n_12), .YS (n_13));
  INVX1 g86(.A (n_10), .Y (n_11));
  MUX2X1 g87(.A (n_9), .B (out[2]), .S (en), .Y (n_10));
  DFFSR \out_reg[1] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_7), .Q
       (n_19));
  HAX1 g89(.A (out[2]), .B (n_4), .YC (n_8), .YS (n_9));
  INVX1 g90(.A (n_6), .Y (n_7));
  MUX2X1 g91(.A (n_5), .B (out[1]), .S (en), .Y (n_6));
  DFFSR \out_reg[0] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_18));
  HAX1 g93(.A (out[1]), .B (out[0]), .YC (n_4), .YS (n_5));
  INVX1 g98(.A (rst), .Y (n_3));
  BUFX2 drc_bufs118(.A (n_22), .Y (out[4]));
  BUFX2 drc_bufs119(.A (n_18), .Y (out[0]));
  BUFX2 drc_bufs120(.A (n_19), .Y (out[1]));
  BUFX2 drc_bufs121(.A (n_20), .Y (out[2]));
  BUFX2 drc_bufs122(.A (n_21), .Y (out[3]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
  XOR2X1 g128(.A (n_32), .B (out[4]), .Y (n_33));
  AND2X1 g3(.A (n_12), .B (en), .Y (n_32));
endmodule

module ctr_out_bank_32(clk, rst, en, mul_in, bin_out);
  input clk, rst, en;
  input [31:0] mul_in;
  output [31:0] bin_out;
  wire clk, rst, en;
  wire [31:0] mul_in;
  wire [31:0] bin_out;
  wire [4:0] ctr31;
  wire [4:0] ctr30;
  wire [4:0] ctr29;
  wire [4:0] ctr28;
  wire [4:0] ctr27;
  wire [4:0] ctr26;
  wire [4:0] ctr25;
  wire [4:0] ctr24;
  wire [4:0] ctr23;
  wire [4:0] ctr22;
  wire [4:0] ctr21;
  wire [4:0] ctr20;
  wire [4:0] ctr19;
  wire [4:0] ctr18;
  wire [4:0] ctr17;
  wire [4:0] ctr16;
  wire [4:0] ctr15;
  wire [4:0] ctr14;
  wire [4:0] ctr13;
  wire [4:0] ctr12;
  wire [4:0] ctr11;
  wire [4:0] ctr10;
  wire [4:0] ctr9;
  wire [4:0] ctr8;
  wire [4:0] ctr7;
  wire [4:0] ctr6;
  wire [4:0] ctr5;
  wire [4:0] ctr4;
  wire [4:0] ctr3;
  wire [4:0] ctr2;
  wire [4:0] ctr0;
  wire [4:0] ctr1;
  wire [31:0] unused;
  wire n_1, n_2, n_10, n_21, n_32, n_43, n_49, n_50;
  wire n_51, n_52, n_53, n_55, n_56, n_57, n_58, n_59;
  wire n_60, n_61, n_62, n_63, n_64, n_65, n_66, n_67;
  wire n_68, n_69, n_70, n_71, n_72, n_74, n_75;
  assign bin_out[10] = 1'b0;
  assign bin_out[11] = 1'b0;
  assign bin_out[12] = 1'b0;
  assign bin_out[13] = 1'b0;
  assign bin_out[14] = 1'b0;
  assign bin_out[15] = 1'b0;
  assign bin_out[16] = 1'b0;
  assign bin_out[17] = 1'b0;
  assign bin_out[18] = 1'b0;
  assign bin_out[19] = 1'b0;
  assign bin_out[20] = 1'b0;
  assign bin_out[21] = 1'b0;
  assign bin_out[22] = 1'b0;
  assign bin_out[23] = 1'b0;
  assign bin_out[24] = 1'b0;
  assign bin_out[25] = 1'b0;
  assign bin_out[26] = 1'b0;
  assign bin_out[27] = 1'b0;
  assign bin_out[28] = 1'b0;
  assign bin_out[29] = 1'b0;
  assign bin_out[30] = 1'b0;
  assign bin_out[31] = 1'b0;
  csa_tree_add_905_257_group_281 csa_tree_add_905_257_groupi(.in_0
       (ctr31), .in_1 (ctr30), .in_2 (ctr29), .in_3 (ctr28), .in_4
       (ctr27), .in_5 (ctr26), .in_6 (ctr25), .in_7 (ctr24), .in_8
       (ctr23), .in_9 (ctr22), .in_10 (ctr21), .in_11 (ctr20), .in_12
       (ctr19), .in_13 (ctr18), .in_14 (ctr17), .in_15 (ctr16), .in_16
       (ctr15), .in_17 (ctr14), .in_18 (ctr13), .in_19 (ctr12), .in_20
       (ctr11), .in_21 (ctr10), .in_22 (ctr9), .in_23 (ctr8), .in_24
       (ctr7), .in_25 (ctr6), .in_26 (ctr5), .in_27 (ctr4), .in_28
       (ctr3), .in_29 (ctr2), .in_30 (ctr0), .in_31 (ctr1), .out_0
       (bin_out[9:0]));
  counter_WIDTH5 stoch2bin_0(.out (ctr0), .clk (clk), .en (n_65), .rst
       (rst), .overflow (unused[0]));
  counter_WIDTH5_1 stoch2bin_1(.out (ctr1), .clk (clk), .en (n_43),
       .rst (rst), .overflow (unused[1]));
  counter_WIDTH5_10 stoch2bin_10(.out (ctr10), .clk (clk), .en (n_72),
       .rst (rst), .overflow (unused[10]));
  counter_WIDTH5_11 stoch2bin_11(.out (ctr11), .clk (clk), .en (n_71),
       .rst (rst), .overflow (unused[11]));
  counter_WIDTH5_12 stoch2bin_12(.out (ctr12), .clk (clk), .en (n_70),
       .rst (rst), .overflow (unused[12]));
  counter_WIDTH5_13 stoch2bin_13(.out (ctr13), .clk (clk), .en (n_69),
       .rst (rst), .overflow (unused[13]));
  counter_WIDTH5_14 stoch2bin_14(.out (ctr14), .clk (clk), .en (n_68),
       .rst (rst), .overflow (unused[14]));
  counter_WIDTH5_15 stoch2bin_15(.out (ctr15), .clk (clk), .en (n_67),
       .rst (rst), .overflow (unused[15]));
  counter_WIDTH5_16 stoch2bin_16(.out (ctr16), .clk (clk), .en (n_66),
       .rst (rst), .overflow (unused[16]));
  counter_WIDTH5_17 stoch2bin_17(.out (ctr17), .clk (clk), .en (n_64),
       .rst (rst), .overflow (unused[17]));
  counter_WIDTH5_18 stoch2bin_18(.out (ctr18), .clk (clk), .en (n_63),
       .rst (rst), .overflow (unused[18]));
  counter_WIDTH5_19 stoch2bin_19(.out (ctr19), .clk (clk), .en (n_62),
       .rst (rst), .overflow (unused[19]));
  counter_WIDTH5_2 stoch2bin_2(.out (ctr2), .clk (clk), .en (n_32),
       .rst (rst), .overflow (unused[2]));
  counter_WIDTH5_20 stoch2bin_20(.out (ctr20), .clk (clk), .en (n_61),
       .rst (rst), .overflow (unused[20]));
  counter_WIDTH5_21 stoch2bin_21(.out (ctr21), .clk (clk), .en (n_60),
       .rst (rst), .overflow (unused[21]));
  counter_WIDTH5_22 stoch2bin_22(.out (ctr22), .clk (clk), .en (n_59),
       .rst (rst), .overflow (unused[22]));
  counter_WIDTH5_23 stoch2bin_23(.out (ctr23), .clk (clk), .en (n_58),
       .rst (rst), .overflow (unused[23]));
  counter_WIDTH5_24 stoch2bin_24(.out (ctr24), .clk (clk), .en (n_57),
       .rst (rst), .overflow (unused[24]));
  counter_WIDTH5_25 stoch2bin_25(.out (ctr25), .clk (clk), .en (n_56),
       .rst (rst), .overflow (unused[25]));
  counter_WIDTH5_26 stoch2bin_26(.out (ctr26), .clk (clk), .en (n_55),
       .rst (rst), .overflow (unused[26]));
  counter_WIDTH5_27 stoch2bin_27(.out (ctr27), .clk (clk), .en (n_53),
       .rst (rst), .overflow (unused[27]));
  counter_WIDTH5_28 stoch2bin_28(.out (ctr28), .clk (clk), .en (n_52),
       .rst (rst), .overflow (unused[28]));
  counter_WIDTH5_29 stoch2bin_29(.out (ctr29), .clk (clk), .en (n_51),
       .rst (rst), .overflow (unused[29]));
  counter_WIDTH5_3 stoch2bin_3(.out (ctr3), .clk (clk), .en (n_21),
       .rst (rst), .overflow (unused[3]));
  counter_WIDTH5_30 stoch2bin_30(.out (ctr30), .clk (clk), .en (n_50),
       .rst (rst), .overflow (unused[30]));
  counter_WIDTH5_31 stoch2bin_31(.out (ctr31), .clk (clk), .en (n_49),
       .rst (rst), .overflow (unused[31]));
  counter_WIDTH5_4 stoch2bin_4(.out (ctr4), .clk (clk), .en (n_10),
       .rst (rst), .overflow (unused[4]));
  counter_WIDTH5_5 stoch2bin_5(.out (ctr5), .clk (clk), .en (n_2), .rst
       (rst), .overflow (unused[5]));
  counter_WIDTH5_6 stoch2bin_6(.out (ctr6), .clk (clk), .en (n_1), .rst
       (rst), .overflow (unused[6]));
  counter_WIDTH5_7 stoch2bin_7(.out (ctr7), .clk (clk), .en (n_75),
       .rst (rst), .overflow (unused[7]));
  counter_WIDTH5_8 stoch2bin_8(.out (ctr8), .clk (clk), .en (n_74),
       .rst (rst), .overflow (unused[8]));
  counter_WIDTH5_9 stoch2bin_9(.out (ctr9), .clk (clk), .en
       (mul_in[9]), .rst (rst), .overflow (unused[9]));
  AND2X1 g218(.A (en), .B (mul_in[0]), .Y (n_65));
  AND2X1 g219(.A (en), .B (mul_in[10]), .Y (n_72));
  AND2X1 g220(.A (en), .B (mul_in[12]), .Y (n_70));
  AND2X1 g221(.A (en), .B (mul_in[16]), .Y (n_66));
  AND2X1 g222(.A (en), .B (mul_in[23]), .Y (n_58));
  AND2X1 g223(.A (en), .B (mul_in[24]), .Y (n_57));
  AND2X1 g224(.A (en), .B (mul_in[17]), .Y (n_64));
  AND2X1 g225(.A (en), .B (mul_in[25]), .Y (n_56));
  AND2X1 g226(.A (en), .B (mul_in[26]), .Y (n_55));
  AND2X1 g227(.A (en), .B (mul_in[13]), .Y (n_69));
  AND2X1 g228(.A (en), .B (mul_in[18]), .Y (n_63));
  AND2X1 g229(.A (en), .B (mul_in[27]), .Y (n_53));
  AND2X1 g230(.A (en), .B (mul_in[28]), .Y (n_52));
  AND2X1 g231(.A (en), .B (mul_in[19]), .Y (n_62));
  AND2X1 g232(.A (en), .B (mul_in[29]), .Y (n_51));
  AND2X1 g233(.A (en), .B (mul_in[2]), .Y (n_32));
  AND2X1 g234(.A (en), .B (mul_in[11]), .Y (n_71));
  AND2X1 g235(.A (en), .B (mul_in[14]), .Y (n_68));
  AND2X1 g236(.A (en), .B (mul_in[1]), .Y (n_43));
  AND2X1 g237(.A (en), .B (mul_in[30]), .Y (n_50));
  AND2X1 g238(.A (en), .B (mul_in[31]), .Y (n_49));
  AND2X1 g239(.A (en), .B (mul_in[20]), .Y (n_61));
  AND2X1 g240(.A (en), .B (mul_in[3]), .Y (n_21));
  AND2X1 g241(.A (en), .B (mul_in[4]), .Y (n_10));
  AND2X1 g242(.A (en), .B (mul_in[15]), .Y (n_67));
  AND2X1 g243(.A (en), .B (mul_in[21]), .Y (n_60));
  AND2X1 g244(.A (en), .B (mul_in[5]), .Y (n_2));
  AND2X1 g245(.A (en), .B (mul_in[6]), .Y (n_1));
  AND2X1 g246(.A (en), .B (mul_in[22]), .Y (n_59));
  AND2X1 g247(.A (en), .B (mul_in[7]), .Y (n_75));
  AND2X1 g248(.A (en), .B (mul_in[8]), .Y (n_74));
endmodule

