
// Generated by Cadence Encounter(R) RTL Compiler RC14.28 - v14.20-s067_1

// Verification Directory fv/dsc_mac_top 

module counter_WIDTH1(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [0:0] out;
  output overflow;
  wire clk, en, rst;
  wire [0:0] out;
  wire overflow;
  wire n_1, n_2, n_4;
  INVX1 g7(.A (rst), .Y (n_4));
  DFFSR \out_reg[0] (.R (n_4), .S (1'b1), .CLK (clk), .D (n_1), .Q
       (n_2));
  XOR2X1 g8(.A (out), .B (en), .Y (n_1));
  BUFX2 drc_bufs12(.A (n_2), .Y (out));
endmodule

module det_stoch_scale_add(a, b, s, y);
  input a, b, s;
  output y;
  wire a, b, s;
  wire y;
  wire n_7;
  INVX1 g3(.A (n_7), .Y (y));
  MUX2X1 g2(.A (b), .B (a), .S (s), .Y (n_7));
endmodule

module det_stoch_mul(a, b, y);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X1 g8(.A (b), .B (a), .Y (y));
endmodule

module comp_1b_5(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_1;
  AND2X1 g14(.A (n_1), .B (a), .Y (a_larger));
  INVX1 g15(.A (b), .Y (n_1));
endmodule

module comp_1b_6(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_7(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_8(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_9(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_10(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_11(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_12(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_10b(a_gt_b, a, b);
  input [9:0] a, b;
  output a_gt_b;
  wire [9:0] a, b;
  wire a_gt_b;
  wire [9:0] e;
  wire [9:0] agt;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21;
  comp_1b_5 comp0(.a (a[0]), .b (b[0]), .equal (e[0]), .a_larger
       (agt[0]));
  comp_1b_6 comp1(.a (a[1]), .b (b[1]), .equal (e[1]), .a_larger
       (agt[1]));
  comp_1b_7 comp2(.a (a[2]), .b (b[2]), .equal (e[2]), .a_larger
       (agt[2]));
  comp_1b_8 comp3(.a (a[3]), .b (b[3]), .equal (e[3]), .a_larger
       (agt[3]));
  comp_1b_9 comp4(.a (a[4]), .b (b[4]), .equal (e[4]), .a_larger
       (agt[4]));
  comp_1b_10 comp5(.a (a[5]), .b (b[5]), .equal (e[5]), .a_larger
       (agt[5]));
  comp_1b_11 comp6(.a (a[6]), .b (b[6]), .equal (e[6]), .a_larger
       (agt[6]));
  comp_1b_12 comp7(.a (a[7]), .b (b[7]), .equal (e[7]), .a_larger
       (agt[7]));
  INVX1 g38(.A (e[3]), .Y (n_21));
  INVX1 g39(.A (agt[3]), .Y (n_20));
  INVX1 g40(.A (e[5]), .Y (n_19));
  INVX1 g41(.A (agt[5]), .Y (n_18));
  INVX1 g42(.A (e[7]), .Y (n_17));
  INVX1 g43(.A (agt[7]), .Y (n_16));
  OAI21X1 g308(.A (n_6), .B (n_4), .C (n_5), .Y (a_gt_b));
  AOI21X1 g309(.A (e[8]), .B (n_14), .C (agt[8]), .Y (n_15));
  OAI21X1 g310(.A (n_17), .B (n_3), .C (n_16), .Y (n_14));
  AOI21X1 g311(.A (e[6]), .B (n_12), .C (agt[6]), .Y (n_13));
  OAI21X1 g312(.A (n_19), .B (n_1), .C (n_18), .Y (n_12));
  AOI21X1 g313(.A (e[4]), .B (n_10), .C (agt[4]), .Y (n_11));
  OAI21X1 g314(.A (n_21), .B (n_2), .C (n_20), .Y (n_10));
  AOI21X1 g315(.A (e[2]), .B (n_8), .C (agt[2]), .Y (n_9));
  INVX1 g316(.A (n_0), .Y (n_8));
  AOI21X1 g317(.A (agt[0]), .B (e[1]), .C (agt[1]), .Y (n_7));
  INVX1 g318(.A (e[9]), .Y (n_6));
  INVX1 g319(.A (agt[9]), .Y (n_5));
  BUFX2 drc_bufs(.A (n_15), .Y (n_4));
  BUFX2 drc_bufs320(.A (n_13), .Y (n_3));
  BUFX2 drc_bufs321(.A (n_9), .Y (n_2));
  BUFX2 drc_bufs322(.A (n_11), .Y (n_1));
  BUFX2 drc_bufs323(.A (n_7), .Y (n_0));
endmodule

module counter_WIDTH10(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [9:0] out;
  output overflow;
  wire clk, en, rst;
  wire [9:0] out;
  wire overflow;
  wire n_0, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_26, n_27, n_30, n_31, n_32, n_33, n_34, n_35;
  wire n_36, n_37, n_50, n_51;
  DFFSR \out_reg[7] (.R (n_2), .S (1'b1), .CLK (clk), .D (n_51), .Q
       (n_30));
  DFFSR \out_reg[6] (.R (n_2), .S (1'b1), .CLK (clk), .D (n_27), .Q
       (n_31));
  INVX1 g141(.A (n_26), .Y (n_27));
  MUX2X1 g142(.A (n_24), .B (out[6]), .S (en), .Y (n_26));
  DFFSR \out_reg[5] (.R (n_2), .S (1'b1), .CLK (clk), .D (n_22), .Q
       (n_32));
  HAX1 g145(.A (out[6]), .B (n_19), .YC (n_23), .YS (n_24));
  INVX1 g146(.A (n_21), .Y (n_22));
  MUX2X1 g147(.A (n_20), .B (out[5]), .S (en), .Y (n_21));
  DFFSR \out_reg[4] (.R (n_2), .S (1'b1), .CLK (clk), .D (n_18), .Q
       (n_33));
  HAX1 g149(.A (out[5]), .B (n_15), .YC (n_19), .YS (n_20));
  INVX1 g150(.A (n_17), .Y (n_18));
  MUX2X1 g151(.A (n_16), .B (out[4]), .S (en), .Y (n_17));
  DFFSR \out_reg[3] (.R (n_2), .S (1'b1), .CLK (clk), .D (n_14), .Q
       (n_34));
  HAX1 g153(.A (out[4]), .B (n_11), .YC (n_15), .YS (n_16));
  INVX1 g154(.A (n_13), .Y (n_14));
  MUX2X1 g155(.A (n_12), .B (out[3]), .S (en), .Y (n_13));
  DFFSR \out_reg[2] (.R (n_2), .S (1'b1), .CLK (clk), .D (n_10), .Q
       (n_35));
  HAX1 g157(.A (out[3]), .B (n_7), .YC (n_11), .YS (n_12));
  INVX1 g158(.A (n_9), .Y (n_10));
  MUX2X1 g159(.A (n_8), .B (out[2]), .S (en), .Y (n_9));
  DFFSR \out_reg[1] (.R (n_2), .S (1'b1), .CLK (clk), .D (n_6), .Q
       (n_36));
  HAX1 g161(.A (out[2]), .B (n_3), .YC (n_7), .YS (n_8));
  INVX1 g162(.A (n_5), .Y (n_6));
  MUX2X1 g163(.A (n_4), .B (out[1]), .S (en), .Y (n_5));
  DFFSR \out_reg[0] (.R (n_2), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_37));
  HAX1 g165(.A (out[1]), .B (out[0]), .YC (n_3), .YS (n_4));
  INVX1 g167(.A (rst), .Y (n_2));
  BUFX2 drc_bufs200(.A (n_37), .Y (out[0]));
  BUFX2 drc_bufs201(.A (n_30), .Y (out[7]));
  BUFX2 drc_bufs202(.A (n_31), .Y (out[6]));
  BUFX2 drc_bufs203(.A (n_32), .Y (out[5]));
  BUFX2 drc_bufs204(.A (n_33), .Y (out[4]));
  BUFX2 drc_bufs205(.A (n_34), .Y (out[3]));
  BUFX2 drc_bufs206(.A (n_35), .Y (out[2]));
  BUFX2 drc_bufs207(.A (n_36), .Y (out[1]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
  XOR2X1 g216(.A (n_50), .B (out[7]), .Y (n_51));
  AND2X1 g3(.A (en), .B (n_23), .Y (n_50));
endmodule

module prg_10b(clk, rst, en, bin_in, sn_out, ctr_overflow);
  input clk, rst, en;
  input [9:0] bin_in;
  output sn_out, ctr_overflow;
  wire clk, rst, en;
  wire [9:0] bin_in;
  wire sn_out, ctr_overflow;
  wire [9:0] ctr8_out;
  wire UNCONNECTED_HIER_Z, UNCONNECTED_HIER_Z0, UNCONNECTED_HIER_Z1,
       UNCONNECTED_HIER_Z2, n_9;
  comp_10b comp10(.a_gt_b (sn_out), .a ({UNCONNECTED_HIER_Z0,
       UNCONNECTED_HIER_Z, bin_in[7:0]}), .b ({UNCONNECTED_HIER_Z2,
       UNCONNECTED_HIER_Z1, ctr8_out[7:0]}));
  counter_WIDTH10 ctr8(.out (ctr8_out), .clk (clk), .en (en), .rst
       (rst), .overflow (n_9));
endmodule

module comp_1b(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_1;
  AND2X1 g14(.A (n_1), .B (a), .Y (a_larger));
  INVX1 g15(.A (b), .Y (n_1));
endmodule

module comp_1b_1(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_2(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_3(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_4(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_5b(a_gt_b, a, b);
  input [4:0] a, b;
  output a_gt_b;
  wire [4:0] a, b;
  wire a_gt_b;
  wire UNCONNECTED, agt, agt_11, agt_13, agt_18, agt_24, e, e_15;
  wire e_21, e_28, n_0, n_1, n_2, n_3, n_4, n_5;
  wire n_6, n_7, n_8;
  comp_1b comp0(.a (a[0]), .b (b[0]), .equal (UNCONNECTED), .a_larger
       (agt_24));
  comp_1b_1 comp1(.a (a[1]), .b (b[1]), .equal (e_28), .a_larger
       (agt_18));
  comp_1b_2 comp2(.a (a[2]), .b (b[2]), .equal (e_21), .a_larger
       (agt_13));
  comp_1b_3 comp3(.a (a[3]), .b (b[3]), .equal (e_15), .a_larger (agt));
  comp_1b_4 comp4(.a (a[4]), .b (b[4]), .equal (e), .a_larger (agt_11));
  INVX1 g20(.A (e_21), .Y (n_8));
  INVX1 g21(.A (agt_13), .Y (n_7));
  INVX1 g22(.A (e), .Y (n_6));
  INVX1 g23(.A (agt_11), .Y (n_5));
  OAI21X1 g116(.A (n_6), .B (n_1), .C (n_5), .Y (a_gt_b));
  AOI21X1 g117(.A (e_15), .B (n_3), .C (agt), .Y (n_4));
  OAI21X1 g118(.A (n_8), .B (n_0), .C (n_7), .Y (n_3));
  AOI21X1 g119(.A (agt_24), .B (e_28), .C (agt_18), .Y (n_2));
  BUFX2 drc_bufs(.A (n_4), .Y (n_1));
  BUFX2 drc_bufs120(.A (n_2), .Y (n_0));
endmodule

module counter_WIDTH5(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [4:0] out;
  output overflow;
  wire clk, en, rst;
  wire [4:0] out;
  wire overflow;
  wire n_0, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_31, n_32, n_33, n_34;
  wire n_35;
  DFFSR \out_reg[4] (.R (n_8), .S (1'b1), .CLK (clk), .D (n_26), .Q
       (n_31));
  DFFSR overflow_reg(.R (n_8), .S (1'b1), .CLK (clk), .D (n_24), .Q
       (overflow));
  INVX1 g78(.A (n_25), .Y (n_26));
  MUX2X1 g79(.A (n_22), .B (out[4]), .S (en), .Y (n_25));
  INVX1 g80(.A (n_23), .Y (n_24));
  MUX2X1 g81(.A (n_21), .B (overflow), .S (en), .Y (n_23));
  DFFSR \out_reg[3] (.R (n_8), .S (1'b1), .CLK (clk), .D (n_20), .Q
       (n_32));
  HAX1 g83(.A (out[4]), .B (n_17), .YC (n_21), .YS (n_22));
  INVX1 g84(.A (n_19), .Y (n_20));
  MUX2X1 g85(.A (n_18), .B (out[3]), .S (en), .Y (n_19));
  DFFSR \out_reg[2] (.R (n_8), .S (1'b1), .CLK (clk), .D (n_16), .Q
       (n_33));
  HAX1 g87(.A (out[3]), .B (n_13), .YC (n_17), .YS (n_18));
  INVX1 g88(.A (n_15), .Y (n_16));
  MUX2X1 g89(.A (n_14), .B (out[2]), .S (en), .Y (n_15));
  DFFSR \out_reg[1] (.R (n_8), .S (1'b1), .CLK (clk), .D (n_12), .Q
       (n_34));
  HAX1 g91(.A (out[2]), .B (n_9), .YC (n_13), .YS (n_14));
  INVX1 g92(.A (n_11), .Y (n_12));
  MUX2X1 g93(.A (n_10), .B (out[1]), .S (en), .Y (n_11));
  DFFSR \out_reg[0] (.R (n_8), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_35));
  HAX1 g95(.A (out[1]), .B (out[0]), .YC (n_9), .YS (n_10));
  INVX1 g97(.A (rst), .Y (n_8));
  BUFX2 drc_bufs122(.A (n_35), .Y (out[0]));
  BUFX2 drc_bufs124(.A (n_31), .Y (out[4]));
  BUFX2 drc_bufs125(.A (n_32), .Y (out[3]));
  BUFX2 drc_bufs126(.A (n_33), .Y (out[2]));
  BUFX2 drc_bufs127(.A (n_34), .Y (out[1]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
endmodule

module prg_5b(clk, rst, en, bin_in, sn_out, ctr_overflow);
  input clk, rst, en;
  input [4:0] bin_in;
  output sn_out, ctr_overflow;
  wire clk, rst, en;
  wire [4:0] bin_in;
  wire sn_out, ctr_overflow;
  wire [4:0] ctr4_out;
  comp_5b comp4(.a_gt_b (sn_out), .a (bin_in), .b (ctr4_out));
  counter_WIDTH5 ctr4(.out (ctr4_out), .clk (clk), .en (en), .rst
       (rst), .overflow (ctr_overflow));
endmodule

module comp_1b_13(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_1;
  AND2X1 g14(.A (n_1), .B (a), .Y (a_larger));
  INVX1 g15(.A (b), .Y (n_1));
endmodule

module comp_1b_14(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_15(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_16(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_17(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_5b_1(a_gt_b, a, b);
  input [4:0] a, b;
  output a_gt_b;
  wire [4:0] a, b;
  wire a_gt_b;
  wire UNCONNECTED0, agt, agt_11, agt_13, agt_18, agt_24, e, e_15;
  wire e_21, e_28, n_0, n_1, n_2, n_3, n_4, n_5;
  wire n_6, n_7, n_8;
  comp_1b_13 comp0(.a (a[0]), .b (b[0]), .equal (UNCONNECTED0),
       .a_larger (agt_24));
  comp_1b_14 comp1(.a (a[1]), .b (b[1]), .equal (e_28), .a_larger
       (agt_18));
  comp_1b_15 comp2(.a (a[2]), .b (b[2]), .equal (e_21), .a_larger
       (agt_13));
  comp_1b_16 comp3(.a (a[3]), .b (b[3]), .equal (e_15), .a_larger
       (agt));
  comp_1b_17 comp4(.a (a[4]), .b (b[4]), .equal (e), .a_larger
       (agt_11));
  INVX1 g23(.A (e_21), .Y (n_8));
  INVX1 g20(.A (agt_13), .Y (n_7));
  INVX1 g22(.A (e), .Y (n_6));
  INVX1 g21(.A (agt_11), .Y (n_5));
  OAI21X1 g116(.A (n_6), .B (n_1), .C (n_5), .Y (a_gt_b));
  AOI21X1 g117(.A (e_15), .B (n_3), .C (agt), .Y (n_4));
  OAI21X1 g118(.A (n_8), .B (n_0), .C (n_7), .Y (n_3));
  AOI21X1 g119(.A (agt_24), .B (e_28), .C (agt_18), .Y (n_2));
  BUFX2 drc_bufs(.A (n_4), .Y (n_1));
  BUFX2 drc_bufs120(.A (n_2), .Y (n_0));
endmodule

module counter_WIDTH5_1(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [4:0] out;
  output overflow;
  wire clk, en, rst;
  wire [4:0] out;
  wire overflow;
  wire n_0, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_31, n_32, n_33, n_34;
  wire n_35;
  DFFSR \out_reg[4] (.R (n_8), .S (1'b1), .CLK (clk), .D (n_26), .Q
       (n_31));
  DFFSR overflow_reg(.R (n_8), .S (1'b1), .CLK (clk), .D (n_24), .Q
       (overflow));
  INVX1 g78(.A (n_25), .Y (n_26));
  MUX2X1 g79(.A (n_22), .B (out[4]), .S (en), .Y (n_25));
  INVX1 g80(.A (n_23), .Y (n_24));
  MUX2X1 g81(.A (n_21), .B (overflow), .S (en), .Y (n_23));
  DFFSR \out_reg[3] (.R (n_8), .S (1'b1), .CLK (clk), .D (n_20), .Q
       (n_32));
  HAX1 g83(.A (out[4]), .B (n_17), .YC (n_21), .YS (n_22));
  INVX1 g84(.A (n_19), .Y (n_20));
  MUX2X1 g85(.A (n_18), .B (out[3]), .S (en), .Y (n_19));
  DFFSR \out_reg[2] (.R (n_8), .S (1'b1), .CLK (clk), .D (n_16), .Q
       (n_33));
  HAX1 g87(.A (out[3]), .B (n_13), .YC (n_17), .YS (n_18));
  INVX1 g88(.A (n_15), .Y (n_16));
  MUX2X1 g89(.A (n_14), .B (out[2]), .S (en), .Y (n_15));
  DFFSR \out_reg[1] (.R (n_8), .S (1'b1), .CLK (clk), .D (n_12), .Q
       (n_34));
  HAX1 g91(.A (out[2]), .B (n_9), .YC (n_13), .YS (n_14));
  INVX1 g92(.A (n_11), .Y (n_12));
  MUX2X1 g93(.A (n_10), .B (out[1]), .S (en), .Y (n_11));
  DFFSR \out_reg[0] (.R (n_8), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_35));
  HAX1 g95(.A (out[1]), .B (out[0]), .YC (n_9), .YS (n_10));
  INVX1 g97(.A (rst), .Y (n_8));
  BUFX2 drc_bufs122(.A (n_35), .Y (out[0]));
  BUFX2 drc_bufs124(.A (n_31), .Y (out[4]));
  BUFX2 drc_bufs125(.A (n_32), .Y (out[3]));
  BUFX2 drc_bufs126(.A (n_33), .Y (out[2]));
  BUFX2 drc_bufs127(.A (n_34), .Y (out[1]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
endmodule

module prg_5b_1(clk, rst, en, bin_in, sn_out, ctr_overflow);
  input clk, rst, en;
  input [4:0] bin_in;
  output sn_out, ctr_overflow;
  wire clk, rst, en;
  wire [4:0] bin_in;
  wire sn_out, ctr_overflow;
  wire [4:0] ctr4_out;
  comp_5b_1 comp4(.a_gt_b (sn_out), .a (bin_in), .b (ctr4_out));
  counter_WIDTH5_1 ctr4(.out (ctr4_out), .clk (clk), .en (en), .rst
       (rst), .overflow (ctr_overflow));
endmodule

module counter_WIDTH10_1(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [9:0] out;
  output overflow;
  wire clk, en, rst;
  wire [9:0] out;
  wire overflow;
  wire n_0, n_1, n_2, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51, n_52, n_53;
  INVX1 g41(.A (rst), .Y (n_53));
  DFFSR \out_reg[9] (.R (n_53), .S (1'b1), .CLK (clk), .D (n_41), .Q
       (n_42));
  DFFSR overflow_reg(.R (n_53), .S (1'b1), .CLK (clk), .D (n_39), .Q
       (n_44));
  INVX1 g166(.A (n_40), .Y (n_41));
  MUX2X1 g167(.A (n_37), .B (n_1), .S (en), .Y (n_40));
  INVX1 g168(.A (n_38), .Y (n_39));
  MUX2X1 g169(.A (n_36), .B (overflow), .S (en), .Y (n_38));
  DFFSR \out_reg[8] (.R (n_53), .S (1'b1), .CLK (clk), .D (n_35), .Q
       (n_43));
  HAX1 g171(.A (n_1), .B (n_32), .YC (n_36), .YS (n_37));
  INVX1 g172(.A (n_34), .Y (n_35));
  MUX2X1 g173(.A (n_33), .B (n_2), .S (en), .Y (n_34));
  DFFSR \out_reg[7] (.R (n_53), .S (1'b1), .CLK (clk), .D (n_31), .Q
       (n_52));
  HAX1 g175(.A (n_2), .B (n_28), .YC (n_32), .YS (n_33));
  INVX1 g176(.A (n_30), .Y (n_31));
  MUX2X1 g177(.A (n_29), .B (out[7]), .S (en), .Y (n_30));
  DFFSR \out_reg[6] (.R (n_53), .S (1'b1), .CLK (clk), .D (n_27), .Q
       (n_51));
  HAX1 g179(.A (out[7]), .B (n_24), .YC (n_28), .YS (n_29));
  INVX1 g180(.A (n_26), .Y (n_27));
  MUX2X1 g181(.A (n_25), .B (out[6]), .S (en), .Y (n_26));
  DFFSR \out_reg[5] (.R (n_53), .S (1'b1), .CLK (clk), .D (n_23), .Q
       (n_50));
  HAX1 g183(.A (out[6]), .B (n_20), .YC (n_24), .YS (n_25));
  INVX1 g184(.A (n_22), .Y (n_23));
  MUX2X1 g185(.A (n_21), .B (out[5]), .S (en), .Y (n_22));
  DFFSR \out_reg[4] (.R (n_53), .S (1'b1), .CLK (clk), .D (n_19), .Q
       (n_49));
  HAX1 g187(.A (out[5]), .B (n_16), .YC (n_20), .YS (n_21));
  INVX1 g188(.A (n_18), .Y (n_19));
  MUX2X1 g189(.A (n_17), .B (out[4]), .S (en), .Y (n_18));
  DFFSR \out_reg[3] (.R (n_53), .S (1'b1), .CLK (clk), .D (n_15), .Q
       (n_48));
  HAX1 g191(.A (out[4]), .B (n_12), .YC (n_16), .YS (n_17));
  INVX1 g192(.A (n_14), .Y (n_15));
  MUX2X1 g193(.A (n_13), .B (out[3]), .S (en), .Y (n_14));
  DFFSR \out_reg[2] (.R (n_53), .S (1'b1), .CLK (clk), .D (n_11), .Q
       (n_47));
  HAX1 g195(.A (out[3]), .B (n_8), .YC (n_12), .YS (n_13));
  INVX1 g196(.A (n_10), .Y (n_11));
  MUX2X1 g197(.A (n_9), .B (out[2]), .S (en), .Y (n_10));
  DFFSR \out_reg[1] (.R (n_53), .S (1'b1), .CLK (clk), .D (n_7), .Q
       (n_46));
  HAX1 g199(.A (out[2]), .B (n_4), .YC (n_8), .YS (n_9));
  INVX1 g200(.A (n_6), .Y (n_7));
  MUX2X1 g201(.A (n_5), .B (out[1]), .S (en), .Y (n_6));
  DFFSR \out_reg[0] (.R (n_53), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_45));
  HAX1 g203(.A (out[1]), .B (out[0]), .YC (n_4), .YS (n_5));
  BUFX2 drc_bufs249(.A (n_52), .Y (out[7]));
  BUFX2 drc_bufs250(.A (n_42), .Y (n_1));
  BUFX2 drc_bufs251(.A (n_43), .Y (n_2));
  BUFX2 drc_bufs252(.A (n_44), .Y (overflow));
  BUFX2 drc_bufs253(.A (n_45), .Y (out[0]));
  BUFX2 drc_bufs254(.A (n_46), .Y (out[1]));
  BUFX2 drc_bufs255(.A (n_47), .Y (out[2]));
  BUFX2 drc_bufs256(.A (n_48), .Y (out[3]));
  BUFX2 drc_bufs257(.A (n_49), .Y (out[4]));
  BUFX2 drc_bufs258(.A (n_50), .Y (out[5]));
  BUFX2 drc_bufs259(.A (n_51), .Y (out[6]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
endmodule

module dsc_mac_top(clk, rst, en, input_bin_a, input_bin_b, input_bin_c,
     en_c, bin_out, bin_out_overflow);
  input clk, rst, en, en_c;
  input [3:0] input_bin_a, input_bin_b;
  input [7:0] input_bin_c;
  output [7:0] bin_out;
  output bin_out_overflow;
  wire clk, rst, en, en_c;
  wire [3:0] input_bin_a, input_bin_b;
  wire [7:0] input_bin_c;
  wire [7:0] bin_out;
  wire bin_out_overflow;
  wire UNCONNECTED1, UNCONNECTED2, UNCONNECTED3, UNCONNECTED4,
       UNCONNECTED5, UNCONNECTED6, ctr4_overflow_a, ctr4_overflow_b;
  wire ctr8_overflow_c, op_end, sn_add_out, sn_mul_out, sn_out_a,
       sn_out_b, sn_out_c, start_add;
  counter_WIDTH1 control(.out (start_add), .clk (ctr4_overflow_b), .en
       (en), .rst (rst), .overflow (op_end));
  det_stoch_scale_add dut_adder(.a (sn_mul_out), .b (sn_out_c), .s
       (start_add), .y (sn_add_out));
  det_stoch_mul dut_mul(.a (sn_out_a), .b (sn_out_b), .y (sn_mul_out));
  prg_10b dut_prg10b_c(.clk (clk), .rst (rst), .en (en_c), .bin_in
       ({UNCONNECTED2, UNCONNECTED1, input_bin_c}), .sn_out (sn_out_c),
       .ctr_overflow (ctr8_overflow_c));
  prg_5b dut_prg5b_a(.clk (clk), .rst (rst), .en (en), .bin_in
       ({UNCONNECTED3, input_bin_a}), .sn_out (sn_out_a), .ctr_overflow
       (ctr4_overflow_a));
  prg_5b_1 dut_prg5b_b(.clk (ctr4_overflow_a), .rst (rst), .en (en),
       .bin_in ({UNCONNECTED4, input_bin_b}), .sn_out (sn_out_b),
       .ctr_overflow (ctr4_overflow_b));
  counter_WIDTH10_1 stoch2bin_out(.out ({UNCONNECTED6, UNCONNECTED5,
       bin_out}), .clk (clk), .en (sn_add_out), .rst (rst), .overflow
       (bin_out_overflow));
endmodule

