
// Generated by Cadence Encounter(R) RTL Compiler RC14.28 - v14.20-s067_1

// Verification Directory fv/pipe_mul_eighth_top 

module counter_WIDTH7(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [6:0] out;
  output overflow;
  wire clk, en, rst;
  wire [6:0] out;
  wire overflow;
  wire n_0, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_22, n_23, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_44, n_45;
  DFFSR \out_reg[6] (.R (n_2), .S (1'b1), .CLK (clk), .D (n_45), .Q
       (n_32));
  DFFSR \out_reg[5] (.R (n_2), .S (1'b1), .CLK (clk), .D (n_23), .Q
       (n_31));
  INVX1 g112(.A (n_22), .Y (n_23));
  MUX2X1 g113(.A (n_20), .B (out[5]), .S (en), .Y (n_22));
  DFFSR \out_reg[4] (.R (n_2), .S (1'b1), .CLK (clk), .D (n_18), .Q
       (n_30));
  HAX1 g116(.A (out[5]), .B (n_15), .YC (n_19), .YS (n_20));
  INVX1 g117(.A (n_17), .Y (n_18));
  MUX2X1 g118(.A (n_16), .B (out[4]), .S (en), .Y (n_17));
  DFFSR \out_reg[3] (.R (n_2), .S (1'b1), .CLK (clk), .D (n_14), .Q
       (n_29));
  HAX1 g120(.A (out[4]), .B (n_11), .YC (n_15), .YS (n_16));
  INVX1 g121(.A (n_13), .Y (n_14));
  MUX2X1 g122(.A (n_12), .B (out[3]), .S (en), .Y (n_13));
  DFFSR \out_reg[2] (.R (n_2), .S (1'b1), .CLK (clk), .D (n_10), .Q
       (n_28));
  HAX1 g124(.A (out[3]), .B (n_7), .YC (n_11), .YS (n_12));
  INVX1 g125(.A (n_9), .Y (n_10));
  MUX2X1 g126(.A (n_8), .B (out[2]), .S (en), .Y (n_9));
  DFFSR \out_reg[1] (.R (n_2), .S (1'b1), .CLK (clk), .D (n_6), .Q
       (n_27));
  HAX1 g128(.A (out[2]), .B (n_3), .YC (n_7), .YS (n_8));
  INVX1 g129(.A (n_5), .Y (n_6));
  MUX2X1 g130(.A (n_4), .B (out[1]), .S (en), .Y (n_5));
  DFFSR \out_reg[0] (.R (n_2), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_26));
  HAX1 g132(.A (out[1]), .B (out[0]), .YC (n_3), .YS (n_4));
  INVX1 g134(.A (rst), .Y (n_2));
  BUFX2 drc_bufs163(.A (n_32), .Y (out[6]));
  BUFX2 drc_bufs164(.A (n_26), .Y (out[0]));
  BUFX2 drc_bufs165(.A (n_27), .Y (out[1]));
  BUFX2 drc_bufs166(.A (n_28), .Y (out[2]));
  BUFX2 drc_bufs167(.A (n_29), .Y (out[3]));
  BUFX2 drc_bufs168(.A (n_30), .Y (out[4]));
  BUFX2 drc_bufs169(.A (n_31), .Y (out[5]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
  XOR2X1 g177(.A (n_44), .B (out[6]), .Y (n_45));
  AND2X1 g3(.A (en), .B (n_19), .Y (n_44));
endmodule

module counter_WIDTH7_1(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [6:0] out;
  output overflow;
  wire clk, en, rst;
  wire [6:0] out;
  wire overflow;
  wire n_0, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_22, n_23, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_44, n_45;
  DFFSR \out_reg[6] (.R (n_2), .S (1'b1), .CLK (clk), .D (n_45), .Q
       (n_32));
  DFFSR \out_reg[5] (.R (n_2), .S (1'b1), .CLK (clk), .D (n_23), .Q
       (n_31));
  INVX1 g112(.A (n_22), .Y (n_23));
  MUX2X1 g113(.A (n_20), .B (out[5]), .S (en), .Y (n_22));
  DFFSR \out_reg[4] (.R (n_2), .S (1'b1), .CLK (clk), .D (n_18), .Q
       (n_30));
  HAX1 g116(.A (out[5]), .B (n_15), .YC (n_19), .YS (n_20));
  INVX1 g117(.A (n_17), .Y (n_18));
  MUX2X1 g118(.A (n_16), .B (out[4]), .S (en), .Y (n_17));
  DFFSR \out_reg[3] (.R (n_2), .S (1'b1), .CLK (clk), .D (n_14), .Q
       (n_29));
  HAX1 g120(.A (out[4]), .B (n_11), .YC (n_15), .YS (n_16));
  INVX1 g121(.A (n_13), .Y (n_14));
  MUX2X1 g122(.A (n_12), .B (out[3]), .S (en), .Y (n_13));
  DFFSR \out_reg[2] (.R (n_2), .S (1'b1), .CLK (clk), .D (n_10), .Q
       (n_28));
  HAX1 g124(.A (out[3]), .B (n_7), .YC (n_11), .YS (n_12));
  INVX1 g125(.A (n_9), .Y (n_10));
  MUX2X1 g126(.A (n_8), .B (out[2]), .S (en), .Y (n_9));
  DFFSR \out_reg[1] (.R (n_2), .S (1'b1), .CLK (clk), .D (n_6), .Q
       (n_27));
  HAX1 g128(.A (out[2]), .B (n_3), .YC (n_7), .YS (n_8));
  INVX1 g129(.A (n_5), .Y (n_6));
  MUX2X1 g130(.A (n_4), .B (out[1]), .S (en), .Y (n_5));
  DFFSR \out_reg[0] (.R (n_2), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_26));
  HAX1 g132(.A (out[1]), .B (out[0]), .YC (n_3), .YS (n_4));
  INVX1 g134(.A (rst), .Y (n_2));
  BUFX2 drc_bufs163(.A (n_32), .Y (out[6]));
  BUFX2 drc_bufs164(.A (n_26), .Y (out[0]));
  BUFX2 drc_bufs165(.A (n_27), .Y (out[1]));
  BUFX2 drc_bufs166(.A (n_28), .Y (out[2]));
  BUFX2 drc_bufs167(.A (n_29), .Y (out[3]));
  BUFX2 drc_bufs168(.A (n_30), .Y (out[4]));
  BUFX2 drc_bufs169(.A (n_31), .Y (out[5]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
  XOR2X1 g177(.A (n_44), .B (out[6]), .Y (n_45));
  AND2X1 g3(.A (en), .B (n_19), .Y (n_44));
endmodule

module ctr_out_bank_eighth(clk, rst, en, mul_in, bin_out);
  input clk, rst, en;
  input [1:0] mul_in;
  output [31:0] bin_out;
  wire clk, rst, en;
  wire [1:0] mul_in;
  wire [31:0] bin_out;
  wire [6:0] ctr0;
  wire [1:0] unused;
  wire [6:0] ctr1;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_12, n_14;
  counter_WIDTH7 stoch2bin_0(.out (ctr0), .clk (clk), .en (n_14), .rst
       (rst), .overflow (unused[0]));
  counter_WIDTH7_1 stoch2bin_1(.out (ctr1), .clk (clk), .en (n_12),
       .rst (rst), .overflow (unused[1]));
  AND2X1 g75(.A (mul_in[0]), .B (en), .Y (n_14));
  AND2X1 g76(.A (mul_in[1]), .B (en), .Y (n_12));
  FAX1 g395(.A (ctr0[6]), .B (ctr1[6]), .C (n_5), .YC (bin_out[7]), .YS
       (bin_out[6]));
  FAX1 g396(.A (ctr0[5]), .B (ctr1[5]), .C (n_4), .YC (n_5), .YS
       (bin_out[5]));
  FAX1 g397(.A (ctr0[4]), .B (ctr1[4]), .C (n_3), .YC (n_4), .YS
       (bin_out[4]));
  FAX1 g398(.A (ctr0[3]), .B (ctr1[3]), .C (n_2), .YC (n_3), .YS
       (bin_out[3]));
  FAX1 g399(.A (ctr0[2]), .B (ctr1[2]), .C (n_1), .YC (n_2), .YS
       (bin_out[2]));
  FAX1 g400(.A (ctr0[1]), .B (ctr1[1]), .C (n_0), .YC (n_1), .YS
       (bin_out[1]));
  HAX1 g401(.A (ctr1[0]), .B (ctr0[0]), .YC (n_0), .YS (bin_out[0]));
endmodule

module pipe_mul_16b_eighth(a, b, y);
  input [1:0] a, b;
  output [1:0] y;
  wire [1:0] a, b;
  wire [1:0] y;
  AND2X1 g15(.A (b[1]), .B (a[1]), .Y (y[1]));
  AND2X1 g16(.A (b[0]), .B (a[0]), .Y (y[0]));
endmodule

module comp_1b(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_1;
  AND2X1 g14(.A (n_1), .B (a), .Y (a_larger));
  INVX1 g15(.A (b), .Y (n_1));
endmodule

module comp_1b_1(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_2(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_3(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_4b(a_gt_b, a, b);
  input [3:0] a, b;
  output a_gt_b;
  wire [3:0] a, b;
  wire a_gt_b;
  wire UNCONNECTED, agt, agt_9, agt_11, agt_16, e, e_13, e_19;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  comp_1b comp0(.a (a[0]), .b (b[0]), .equal (UNCONNECTED), .a_larger
       (agt_16));
  comp_1b_1 comp1(.a (a[1]), .b (b[1]), .equal (e_19), .a_larger
       (agt_11));
  comp_1b_2 comp2(.a (a[2]), .b (b[2]), .equal (e_13), .a_larger (agt));
  comp_1b_3 comp3(.a (a[3]), .b (b[3]), .equal (e), .a_larger (agt_9));
  INVX1 g12(.A (e), .Y (n_6));
  INVX1 g13(.A (agt_9), .Y (n_5));
  OAI21X1 g73(.A (n_6), .B (n_1), .C (n_5), .Y (a_gt_b));
  AOI21X1 g74(.A (e_13), .B (n_3), .C (agt), .Y (n_4));
  INVX1 g75(.A (n_0), .Y (n_3));
  AOI21X1 g76(.A (agt_16), .B (e_19), .C (agt_11), .Y (n_2));
  BUFX2 drc_bufs(.A (n_4), .Y (n_1));
  BUFX2 drc_bufs77(.A (n_2), .Y (n_0));
endmodule

module counter_WIDTH4(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [3:0] out;
  output overflow;
  wire clk, en, rst;
  wire [3:0] out;
  wire overflow;
  wire n_0, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_11, n_12, n_14, n_15, n_16, n_17, n_26, n_27;
  DFFSR \out_reg[3] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_27), .Q
       (n_17));
  DFFSR \out_reg[2] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_12), .Q
       (n_16));
  INVX1 g66(.A (n_11), .Y (n_12));
  MUX2X1 g67(.A (n_9), .B (out[2]), .S (en), .Y (n_11));
  DFFSR \out_reg[1] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_7), .Q
       (n_15));
  HAX1 g70(.A (out[2]), .B (n_4), .YC (n_8), .YS (n_9));
  INVX1 g71(.A (n_6), .Y (n_7));
  MUX2X1 g72(.A (n_5), .B (out[1]), .S (en), .Y (n_6));
  DFFSR \out_reg[0] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_14));
  HAX1 g74(.A (out[1]), .B (out[0]), .YC (n_4), .YS (n_5));
  INVX1 g79(.A (rst), .Y (n_3));
  BUFX2 drc_bufs95(.A (n_17), .Y (out[3]));
  BUFX2 drc_bufs96(.A (n_14), .Y (out[0]));
  BUFX2 drc_bufs97(.A (n_15), .Y (out[1]));
  BUFX2 drc_bufs98(.A (n_16), .Y (out[2]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
  XOR2X1 g103(.A (n_26), .B (out[3]), .Y (n_27));
  AND2X1 g3(.A (n_8), .B (en), .Y (n_26));
endmodule

module prg_4b(clk, rst, en, bin_in, sn_out, ctr_overflow);
  input clk, rst, en;
  input [3:0] bin_in;
  output sn_out, ctr_overflow;
  wire clk, rst, en;
  wire [3:0] bin_in;
  wire sn_out, ctr_overflow;
  wire [3:0] ctr4_out;
  wire n_1;
  comp_4b comp4(.a_gt_b (sn_out), .a (bin_in), .b (ctr4_out));
  counter_WIDTH4 ctr4(.out (ctr4_out), .clk (clk), .en (en), .rst
       (rst), .overflow (n_1));
endmodule

module comp_1b_4(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_1;
  AND2X1 g14(.A (n_1), .B (a), .Y (a_larger));
  INVX1 g15(.A (b), .Y (n_1));
endmodule

module comp_1b_5(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_6(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_7(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_4b_1(a_gt_b, a, b);
  input [3:0] a, b;
  output a_gt_b;
  wire [3:0] a, b;
  wire a_gt_b;
  wire UNCONNECTED0, agt, agt_9, agt_11, agt_16, e, e_13, e_19;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  comp_1b_4 comp0(.a (a[0]), .b (b[0]), .equal (UNCONNECTED0),
       .a_larger (agt_16));
  comp_1b_5 comp1(.a (a[1]), .b (b[1]), .equal (e_19), .a_larger
       (agt_11));
  comp_1b_6 comp2(.a (a[2]), .b (b[2]), .equal (e_13), .a_larger (agt));
  comp_1b_7 comp3(.a (a[3]), .b (b[3]), .equal (e), .a_larger (agt_9));
  INVX1 g13(.A (e), .Y (n_6));
  INVX1 g12(.A (agt_9), .Y (n_5));
  OAI21X1 g73(.A (n_6), .B (n_1), .C (n_5), .Y (a_gt_b));
  AOI21X1 g74(.A (e_13), .B (n_3), .C (agt), .Y (n_4));
  INVX1 g75(.A (n_0), .Y (n_3));
  AOI21X1 g76(.A (agt_16), .B (e_19), .C (agt_11), .Y (n_2));
  BUFX2 drc_bufs(.A (n_4), .Y (n_1));
  BUFX2 drc_bufs77(.A (n_2), .Y (n_0));
endmodule

module counter_WIDTH4_1(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [3:0] out;
  output overflow;
  wire clk, en, rst;
  wire [3:0] out;
  wire overflow;
  wire n_0, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_11, n_12, n_14, n_15, n_16, n_17, n_26, n_27;
  DFFSR \out_reg[3] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_27), .Q
       (n_17));
  DFFSR \out_reg[2] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_12), .Q
       (n_16));
  INVX1 g66(.A (n_11), .Y (n_12));
  MUX2X1 g67(.A (n_9), .B (out[2]), .S (en), .Y (n_11));
  DFFSR \out_reg[1] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_7), .Q
       (n_15));
  HAX1 g70(.A (out[2]), .B (n_4), .YC (n_8), .YS (n_9));
  INVX1 g71(.A (n_6), .Y (n_7));
  MUX2X1 g72(.A (n_5), .B (out[1]), .S (en), .Y (n_6));
  DFFSR \out_reg[0] (.R (n_3), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_14));
  HAX1 g74(.A (out[1]), .B (out[0]), .YC (n_4), .YS (n_5));
  INVX1 g79(.A (rst), .Y (n_3));
  BUFX2 drc_bufs95(.A (n_17), .Y (out[3]));
  BUFX2 drc_bufs96(.A (n_14), .Y (out[0]));
  BUFX2 drc_bufs97(.A (n_15), .Y (out[1]));
  BUFX2 drc_bufs98(.A (n_16), .Y (out[2]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
  XOR2X1 g103(.A (n_26), .B (out[3]), .Y (n_27));
  AND2X1 g3(.A (n_8), .B (en), .Y (n_26));
endmodule

module prg_4b_1(clk, rst, en, bin_in, sn_out, ctr_overflow);
  input clk, rst, en;
  input [3:0] bin_in;
  output sn_out, ctr_overflow;
  wire clk, rst, en;
  wire [3:0] bin_in;
  wire sn_out, ctr_overflow;
  wire [3:0] ctr4_out;
  wire n_1;
  comp_4b_1 comp4(.a_gt_b (sn_out), .a (bin_in), .b (ctr4_out));
  counter_WIDTH4_1 ctr4(.out (ctr4_out), .clk (clk), .en (en), .rst
       (rst), .overflow (n_1));
endmodule

module shift_reg_16b_eighth(clk, scan_in, wrap_mode, en, rst,
     shiftreg_out);
  input clk, scan_in, wrap_mode, en, rst;
  output [1:0] shiftreg_out;
  wire clk, scan_in, wrap_mode, en, rst;
  wire [1:0] shiftreg_out;
  wire [15:0] shiftreg;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_18;
  wire n_19, n_20, n_21, n_22, n_23, n_24, n_25, n_26;
  wire n_27, n_28, n_29, n_30, n_31, n_32, n_33, n_34;
  wire n_35, n_36, n_37, n_38, n_39, n_40, n_41, n_42;
  wire n_43, n_44, n_45, n_46, n_47, n_48, n_49, n_50;
  wire n_51, n_52;
  DFFSR \shiftreg_reg[0] (.R (n_18), .S (1'b1), .CLK (clk), .D (n_52),
       .Q (shiftreg[0]));
  OAI21X1 g43(.A (n_19), .B (n_21), .C (n_0), .Y (n_52));
  DFFSR \shiftreg_reg[12] (.R (n_18), .S (1'b1), .CLK (clk), .D (n_30),
       .Q (shiftreg[12]));
  DFFSR \shiftreg_reg[4] (.R (n_18), .S (1'b1), .CLK (clk), .D (n_29),
       .Q (shiftreg[4]));
  DFFSR \shiftreg_reg[5] (.R (n_18), .S (1'b1), .CLK (clk), .D (n_49),
       .Q (shiftreg[5]));
  DFFSR \shiftreg_reg[13] (.R (n_18), .S (1'b1), .CLK (clk), .D (n_50),
       .Q (shiftreg[13]));
  DFFSR \shiftreg_reg[6] (.R (n_18), .S (1'b1), .CLK (clk), .D (n_48),
       .Q (shiftreg[6]));
  DFFSR \shiftreg_reg[10] (.R (n_18), .S (1'b1), .CLK (clk), .D (n_51),
       .Q (shiftreg[10]));
  DFFSR \shiftreg_reg[14] (.R (n_18), .S (1'b1), .CLK (clk), .D (n_47),
       .Q (shiftreg[14]));
  DFFSR \shiftreg_reg[7] (.R (n_18), .S (1'b1), .CLK (clk), .D (n_46),
       .Q (shiftreg[7]));
  DFFSR \shiftreg_reg[8] (.R (n_18), .S (1'b1), .CLK (clk), .D (n_45),
       .Q (shiftreg[8]));
  DFFSR \shiftreg_reg[15] (.R (n_18), .S (1'b1), .CLK (clk), .D (n_44),
       .Q (shiftreg[15]));
  DFFSR \shiftreg_reg[9] (.R (n_18), .S (1'b1), .CLK (clk), .D (n_35),
       .Q (shiftreg[9]));
  DFFSR \shiftreg_reg[11] (.R (n_18), .S (1'b1), .CLK (clk), .D (n_34),
       .Q (shiftreg[11]));
  DFFSR \shiftreg_reg[1] (.R (n_18), .S (1'b1), .CLK (clk), .D (n_33),
       .Q (shiftreg[1]));
  DFFSR \shiftreg_reg[2] (.R (n_18), .S (1'b1), .CLK (clk), .D (n_32),
       .Q (shiftreg[2]));
  DFFSR \shiftreg_reg[3] (.R (n_18), .S (1'b1), .CLK (clk), .D (n_31),
       .Q (shiftreg[3]));
  INVX1 g59(.A (n_43), .Y (n_51));
  INVX1 g60(.A (n_42), .Y (n_50));
  INVX1 g61(.A (n_41), .Y (n_49));
  INVX1 g62(.A (n_40), .Y (n_48));
  INVX1 g63(.A (n_39), .Y (n_47));
  INVX1 g64(.A (n_38), .Y (n_46));
  INVX1 g65(.A (n_37), .Y (n_45));
  INVX1 g66(.A (n_36), .Y (n_44));
  MUX2X1 g67(.A (n_7), .B (n_5), .S (en), .Y (n_43));
  MUX2X1 g68(.A (n_14), .B (n_3), .S (en), .Y (n_42));
  MUX2X1 g69(.A (n_9), .B (n_4), .S (en), .Y (n_41));
  MUX2X1 g70(.A (n_4), .B (n_11), .S (en), .Y (n_40));
  MUX2X1 g71(.A (n_3), .B (shiftreg_out[0]), .S (en), .Y (n_39));
  MUX2X1 g72(.A (n_11), .B (n_12), .S (en), .Y (n_38));
  MUX2X1 g73(.A (n_12), .B (n_13), .S (en), .Y (n_37));
  MUX2X1 g74(.A (shiftreg_out[1]), .B (shiftreg_out[0]), .S (n_19), .Y
       (n_36));
  INVX1 g75(.A (n_28), .Y (n_35));
  INVX1 g76(.A (n_27), .Y (n_34));
  INVX1 g77(.A (n_26), .Y (n_33));
  INVX1 g78(.A (n_25), .Y (n_32));
  INVX1 g79(.A (n_24), .Y (n_31));
  INVX1 g80(.A (n_23), .Y (n_30));
  INVX1 g81(.A (n_22), .Y (n_29));
  MUX2X1 g82(.A (n_13), .B (n_7), .S (en), .Y (n_28));
  MUX2X1 g83(.A (n_5), .B (n_2), .S (en), .Y (n_27));
  MUX2X1 g84(.A (n_1), .B (n_10), .S (en), .Y (n_26));
  MUX2X1 g85(.A (n_10), .B (n_6), .S (en), .Y (n_25));
  MUX2X1 g86(.A (n_6), .B (n_8), .S (en), .Y (n_24));
  MUX2X1 g87(.A (n_2), .B (n_14), .S (en), .Y (n_23));
  MUX2X1 g88(.A (n_8), .B (n_9), .S (en), .Y (n_22));
  MUX2X1 g89(.A (shiftreg_out[1]), .B (scan_in), .S (wrap_mode), .Y
       (n_21));
  NAND2X1 g90(.A (n_19), .B (n_1), .Y (n_20));
  INVX1 g91(.A (en), .Y (n_19));
  INVX1 g92(.A (rst), .Y (n_18));
  BUFX2 drc_bufs156(.A (n_20), .Y (n_0));
  BUFX2 drc_bufs157(.A (shiftreg[0]), .Y (n_1));
  BUFX2 drc_bufs158(.A (shiftreg[10]), .Y (n_5));
  BUFX2 drc_bufs159(.A (shiftreg[12]), .Y (n_14));
  BUFX2 drc_bufs160(.A (shiftreg[8]), .Y (n_13));
  BUFX2 drc_bufs161(.A (shiftreg[7]), .Y (n_12));
  BUFX2 drc_bufs162(.A (shiftreg[6]), .Y (n_11));
  BUFX2 drc_bufs163(.A (shiftreg[5]), .Y (n_4));
  BUFX2 drc_bufs164(.A (shiftreg[4]), .Y (n_9));
  BUFX2 drc_bufs165(.A (shiftreg[3]), .Y (n_8));
  BUFX2 drc_bufs166(.A (shiftreg[2]), .Y (n_6));
  BUFX2 drc_bufs167(.A (shiftreg[1]), .Y (n_10));
  BUFX2 drc_bufs168(.A (shiftreg[15]), .Y (shiftreg_out[1]));
  BUFX2 drc_bufs169(.A (shiftreg[14]), .Y (shiftreg_out[0]));
  BUFX2 drc_bufs170(.A (shiftreg[13]), .Y (n_3));
  BUFX2 drc_bufs171(.A (shiftreg[9]), .Y (n_7));
  BUFX2 drc_bufs172(.A (shiftreg[11]), .Y (n_2));
endmodule

module shift_reg_16b_eighth_1(clk, scan_in, wrap_mode, en, rst,
     shiftreg_out);
  input clk, scan_in, wrap_mode, en, rst;
  output [1:0] shiftreg_out;
  wire clk, scan_in, wrap_mode, en, rst;
  wire [1:0] shiftreg_out;
  wire [15:0] shiftreg;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_18;
  wire n_19, n_20, n_21, n_22, n_23, n_24, n_25, n_26;
  wire n_27, n_28, n_29, n_30, n_31, n_32, n_33, n_34;
  wire n_35, n_36, n_37, n_38, n_39, n_40, n_41, n_42;
  wire n_43, n_44, n_45, n_46, n_47, n_48, n_49, n_50;
  wire n_51, n_52;
  DFFSR \shiftreg_reg[0] (.R (n_18), .S (1'b1), .CLK (clk), .D (n_52),
       .Q (shiftreg[0]));
  OAI21X1 g43(.A (n_19), .B (n_21), .C (n_0), .Y (n_52));
  DFFSR \shiftreg_reg[12] (.R (n_18), .S (1'b1), .CLK (clk), .D (n_30),
       .Q (shiftreg[12]));
  DFFSR \shiftreg_reg[4] (.R (n_18), .S (1'b1), .CLK (clk), .D (n_29),
       .Q (shiftreg[4]));
  DFFSR \shiftreg_reg[5] (.R (n_18), .S (1'b1), .CLK (clk), .D (n_49),
       .Q (shiftreg[5]));
  DFFSR \shiftreg_reg[13] (.R (n_18), .S (1'b1), .CLK (clk), .D (n_50),
       .Q (shiftreg[13]));
  DFFSR \shiftreg_reg[6] (.R (n_18), .S (1'b1), .CLK (clk), .D (n_48),
       .Q (shiftreg[6]));
  DFFSR \shiftreg_reg[10] (.R (n_18), .S (1'b1), .CLK (clk), .D (n_51),
       .Q (shiftreg[10]));
  DFFSR \shiftreg_reg[14] (.R (n_18), .S (1'b1), .CLK (clk), .D (n_47),
       .Q (shiftreg[14]));
  DFFSR \shiftreg_reg[7] (.R (n_18), .S (1'b1), .CLK (clk), .D (n_46),
       .Q (shiftreg[7]));
  DFFSR \shiftreg_reg[8] (.R (n_18), .S (1'b1), .CLK (clk), .D (n_45),
       .Q (shiftreg[8]));
  DFFSR \shiftreg_reg[15] (.R (n_18), .S (1'b1), .CLK (clk), .D (n_44),
       .Q (shiftreg[15]));
  DFFSR \shiftreg_reg[9] (.R (n_18), .S (1'b1), .CLK (clk), .D (n_35),
       .Q (shiftreg[9]));
  DFFSR \shiftreg_reg[11] (.R (n_18), .S (1'b1), .CLK (clk), .D (n_34),
       .Q (shiftreg[11]));
  DFFSR \shiftreg_reg[1] (.R (n_18), .S (1'b1), .CLK (clk), .D (n_33),
       .Q (shiftreg[1]));
  DFFSR \shiftreg_reg[2] (.R (n_18), .S (1'b1), .CLK (clk), .D (n_32),
       .Q (shiftreg[2]));
  DFFSR \shiftreg_reg[3] (.R (n_18), .S (1'b1), .CLK (clk), .D (n_31),
       .Q (shiftreg[3]));
  INVX1 g59(.A (n_43), .Y (n_51));
  INVX1 g60(.A (n_42), .Y (n_50));
  INVX1 g61(.A (n_41), .Y (n_49));
  INVX1 g62(.A (n_40), .Y (n_48));
  INVX1 g63(.A (n_39), .Y (n_47));
  INVX1 g64(.A (n_38), .Y (n_46));
  INVX1 g65(.A (n_37), .Y (n_45));
  INVX1 g66(.A (n_36), .Y (n_44));
  MUX2X1 g67(.A (n_7), .B (n_5), .S (en), .Y (n_43));
  MUX2X1 g68(.A (n_14), .B (n_3), .S (en), .Y (n_42));
  MUX2X1 g69(.A (n_9), .B (n_4), .S (en), .Y (n_41));
  MUX2X1 g70(.A (n_4), .B (n_11), .S (en), .Y (n_40));
  MUX2X1 g71(.A (n_3), .B (shiftreg_out[0]), .S (en), .Y (n_39));
  MUX2X1 g72(.A (n_11), .B (n_12), .S (en), .Y (n_38));
  MUX2X1 g73(.A (n_12), .B (n_13), .S (en), .Y (n_37));
  MUX2X1 g74(.A (shiftreg_out[1]), .B (shiftreg_out[0]), .S (n_19), .Y
       (n_36));
  INVX1 g75(.A (n_28), .Y (n_35));
  INVX1 g76(.A (n_27), .Y (n_34));
  INVX1 g77(.A (n_26), .Y (n_33));
  INVX1 g78(.A (n_25), .Y (n_32));
  INVX1 g79(.A (n_24), .Y (n_31));
  INVX1 g80(.A (n_23), .Y (n_30));
  INVX1 g81(.A (n_22), .Y (n_29));
  MUX2X1 g82(.A (n_13), .B (n_7), .S (en), .Y (n_28));
  MUX2X1 g83(.A (n_5), .B (n_2), .S (en), .Y (n_27));
  MUX2X1 g84(.A (n_1), .B (n_10), .S (en), .Y (n_26));
  MUX2X1 g85(.A (n_10), .B (n_6), .S (en), .Y (n_25));
  MUX2X1 g86(.A (n_6), .B (n_8), .S (en), .Y (n_24));
  MUX2X1 g87(.A (n_2), .B (n_14), .S (en), .Y (n_23));
  MUX2X1 g88(.A (n_8), .B (n_9), .S (en), .Y (n_22));
  MUX2X1 g89(.A (shiftreg_out[1]), .B (scan_in), .S (wrap_mode), .Y
       (n_21));
  NAND2X1 g90(.A (n_19), .B (n_1), .Y (n_20));
  INVX1 g91(.A (en), .Y (n_19));
  INVX1 g92(.A (rst), .Y (n_18));
  BUFX2 drc_bufs156(.A (n_20), .Y (n_0));
  BUFX2 drc_bufs157(.A (shiftreg[0]), .Y (n_1));
  BUFX2 drc_bufs158(.A (shiftreg[10]), .Y (n_5));
  BUFX2 drc_bufs159(.A (shiftreg[12]), .Y (n_14));
  BUFX2 drc_bufs160(.A (shiftreg[8]), .Y (n_13));
  BUFX2 drc_bufs161(.A (shiftreg[7]), .Y (n_12));
  BUFX2 drc_bufs162(.A (shiftreg[6]), .Y (n_11));
  BUFX2 drc_bufs163(.A (shiftreg[5]), .Y (n_4));
  BUFX2 drc_bufs164(.A (shiftreg[4]), .Y (n_9));
  BUFX2 drc_bufs165(.A (shiftreg[3]), .Y (n_8));
  BUFX2 drc_bufs166(.A (shiftreg[2]), .Y (n_6));
  BUFX2 drc_bufs167(.A (shiftreg[1]), .Y (n_10));
  BUFX2 drc_bufs168(.A (shiftreg[15]), .Y (shiftreg_out[1]));
  BUFX2 drc_bufs169(.A (shiftreg[14]), .Y (shiftreg_out[0]));
  BUFX2 drc_bufs170(.A (shiftreg[13]), .Y (n_3));
  BUFX2 drc_bufs171(.A (shiftreg[9]), .Y (n_7));
  BUFX2 drc_bufs172(.A (shiftreg[11]), .Y (n_2));
endmodule

module pipe_mul_eighth_top(clk, rst, en, output_gate, input_bin_a,
     input_bin_b, input_bin_c, wrap_mode_a, wrap_mode_b, en_sr_a,
     en_sr_b, rst_out, bin_out);
  input clk, rst, en, output_gate, wrap_mode_a, wrap_mode_b, en_sr_a,
       en_sr_b, rst_out;
  input [3:0] input_bin_a, input_bin_b;
  input [7:0] input_bin_c;
  output [7:0] bin_out;
  wire clk, rst, en, output_gate, wrap_mode_a, wrap_mode_b, en_sr_a,
       en_sr_b, rst_out;
  wire [3:0] input_bin_a, input_bin_b;
  wire [7:0] input_bin_c;
  wire [7:0] bin_out;
  wire [7:0] sr_mul_out;
  wire [7:0] bin_out_int;
  wire [7:0] sr_out_a;
  wire [7:0] sr_out_b;
  wire UNCONNECTED1, UNCONNECTED2, UNCONNECTED3, UNCONNECTED4,
       UNCONNECTED5, UNCONNECTED6, UNCONNECTED7, UNCONNECTED8;
  wire UNCONNECTED9, UNCONNECTED10, UNCONNECTED11, UNCONNECTED12,
       UNCONNECTED13, UNCONNECTED14, UNCONNECTED15, UNCONNECTED16;
  wire UNCONNECTED17, UNCONNECTED18, UNCONNECTED19, UNCONNECTED20,
       UNCONNECTED21, UNCONNECTED22, UNCONNECTED23, UNCONNECTED24;
  wire UNCONNECTED25, ctr4_overflow_a, ctr4_overflow_b, n_1, n_2, n_3,
       n_4, n_5;
  wire n_6, n_7, sn_out_a, sn_out_b;
  ctr_out_bank_eighth dut_ctr_out(.clk (clk), .rst (rst_out), .en
       (output_gate), .mul_in (sr_mul_out[1:0]), .bin_out
       ({UNCONNECTED24, UNCONNECTED23, UNCONNECTED22, UNCONNECTED21,
       UNCONNECTED20, UNCONNECTED19, UNCONNECTED18, UNCONNECTED17,
       UNCONNECTED16, UNCONNECTED15, UNCONNECTED14, UNCONNECTED13,
       UNCONNECTED12, UNCONNECTED11, UNCONNECTED10, UNCONNECTED9,
       UNCONNECTED8, UNCONNECTED7, UNCONNECTED6, UNCONNECTED5,
       UNCONNECTED4, UNCONNECTED3, UNCONNECTED2, UNCONNECTED1,
       bin_out_int}));
  pipe_mul_16b_eighth dut_pipe_mul(.a (sr_out_a[1:0]), .b
       (sr_out_b[1:0]), .y (sr_mul_out[1:0]));
  prg_4b dut_prg4b_a(.clk (clk), .rst (rst), .en (en), .bin_in
       (input_bin_a), .sn_out (sn_out_a), .ctr_overflow
       (ctr4_overflow_a));
  prg_4b_1 dut_prg4b_b(.clk (clk), .rst (rst), .en (en), .bin_in
       (input_bin_b), .sn_out (sn_out_b), .ctr_overflow
       (ctr4_overflow_b));
  shift_reg_16b_eighth dut_sr_a(.clk (clk), .scan_in (sn_out_a),
       .wrap_mode (wrap_mode_a), .en (en_sr_a), .rst (rst),
       .shiftreg_out (sr_out_a[1:0]));
  shift_reg_16b_eighth_1 dut_sr_b(.clk (clk), .scan_in (sn_out_b),
       .wrap_mode (wrap_mode_b), .en (en_sr_b), .rst (rst),
       .shiftreg_out (sr_out_b[1:0]));
  FAX1 g444(.A (input_bin_c[6]), .B (bin_out_int[6]), .C (n_6), .YC
       (n_7), .YS (bin_out[6]));
  FAX1 g445(.A (input_bin_c[5]), .B (bin_out_int[5]), .C (n_5), .YC
       (n_6), .YS (bin_out[5]));
  FAX1 g446(.A (input_bin_c[4]), .B (bin_out_int[4]), .C (n_4), .YC
       (n_5), .YS (bin_out[4]));
  FAX1 g447(.A (input_bin_c[3]), .B (bin_out_int[3]), .C (n_3), .YC
       (n_4), .YS (bin_out[3]));
  FAX1 g448(.A (input_bin_c[2]), .B (bin_out_int[2]), .C (n_2), .YC
       (n_3), .YS (bin_out[2]));
  FAX1 g449(.A (input_bin_c[1]), .B (bin_out_int[1]), .C (n_1), .YC
       (n_2), .YS (bin_out[1]));
  HAX1 g450(.A (input_bin_c[0]), .B (bin_out_int[0]), .YC (n_1), .YS
       (bin_out[0]));
  FAX1 g2(.A (n_7), .B (bin_out_int[7]), .C (input_bin_c[7]), .YC
       (UNCONNECTED25), .YS (bin_out[7]));
endmodule

