
// Generated by Cadence Encounter(R) RTL Compiler RC14.28 - v14.20-s067_1

// Verification Directory fv/top 

module csa_tree_add_757_28_group_80(in_0, in_1, in_2, in_3, out_0);
  input [5:0] in_0, in_1, in_2, in_3;
  output [7:0] out_0;
  wire [5:0] in_0, in_1, in_2, in_3;
  wire [7:0] out_0;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_26, n_28, n_30, n_32;
  FAX1 g415(.A (n_4), .B (n_20), .C (n_32), .YC (out_0[7]), .YS
       (out_0[6]));
  FAX1 g416(.A (n_22), .B (n_21), .C (n_30), .YC (n_32), .YS
       (out_0[5]));
  FAX1 g417(.A (n_18), .B (n_23), .C (n_28), .YC (n_30), .YS
       (out_0[4]));
  FAX1 g418(.A (n_16), .B (n_19), .C (n_26), .YC (n_28), .YS
       (out_0[3]));
  FAX1 g419(.A (n_10), .B (n_17), .C (n_24), .YC (n_26), .YS
       (out_0[2]));
  FAX1 g420(.A (n_2), .B (n_11), .C (n_14), .YC (n_24), .YS (out_0[1]));
  FAX1 g421(.A (in_2[4]), .B (n_12), .C (n_9), .YC (n_22), .YS (n_23));
  FAX1 g422(.A (in_2[5]), .B (n_5), .C (n_8), .YC (n_20), .YS (n_21));
  FAX1 g423(.A (in_2[3]), .B (n_13), .C (n_6), .YC (n_18), .YS (n_19));
  FAX1 g424(.A (in_2[2]), .B (n_0), .C (n_7), .YC (n_16), .YS (n_17));
  FAX1 g425(.A (in_1[0]), .B (in_2[0]), .C (n_3), .YC (n_14), .YS
       (out_0[0]));
  FAX1 g426(.A (in_0[3]), .B (in_1[3]), .C (in_3[3]), .YC (n_12), .YS
       (n_13));
  FAX1 g427(.A (in_2[1]), .B (in_3[1]), .C (n_1), .YC (n_10), .YS
       (n_11));
  FAX1 g428(.A (in_0[4]), .B (in_1[4]), .C (in_3[4]), .YC (n_8), .YS
       (n_9));
  FAX1 g429(.A (in_0[2]), .B (in_1[2]), .C (in_3[2]), .YC (n_6), .YS
       (n_7));
  FAX1 g430(.A (in_0[5]), .B (in_1[5]), .C (in_3[5]), .YC (n_4), .YS
       (n_5));
  HAX1 g431(.A (in_3[0]), .B (in_0[0]), .YC (n_2), .YS (n_3));
  HAX1 g432(.A (in_1[1]), .B (in_0[1]), .YC (n_0), .YS (n_1));
endmodule

module add4_6b(x1, x2, x3, x4, y);
  input [5:0] x1, x2, x3, x4;
  output [7:0] y;
  wire [5:0] x1, x2, x3, x4;
  wire [7:0] y;
  csa_tree_add_757_28_group_80 csa_tree_add_757_28_groupi(.in_0 (x4),
       .in_1 (x3), .in_2 (x1), .in_3 (x2), .out_0 (y));
endmodule

module csa_tree_add_723_48_group_78(in_0, in_1, in_2, in_3, in_4, in_5,
     in_6, in_7, out_0);
  input [2:0] in_0, in_1, in_2, in_3, in_4, in_5, in_6, in_7;
  output [5:0] out_0;
  wire [2:0] in_0, in_1, in_2, in_3, in_4, in_5, in_6, in_7;
  wire [5:0] out_0;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_28, n_29, n_30, n_31, n_32;
  wire n_34, n_35, n_36, n_38;
  FAX1 g469(.A (n_28), .B (n_34), .C (n_38), .YC (out_0[5]), .YS
       (out_0[4]));
  FAX1 g470(.A (n_30), .B (n_35), .C (n_36), .YC (n_38), .YS
       (out_0[3]));
  FAX1 g471(.A (n_25), .B (n_31), .C (n_32), .YC (n_36), .YS
       (out_0[2]));
  FAX1 g472(.A (n_20), .B (n_29), .C (n_24), .YC (n_34), .YS (n_35));
  FAX1 g473(.A (n_19), .B (n_26), .C (n_23), .YC (n_32), .YS
       (out_0[1]));
  FAX1 g474(.A (n_18), .B (n_21), .C (n_22), .YC (n_30), .YS (n_31));
  FAX1 g475(.A (n_4), .B (n_10), .C (n_14), .YC (n_28), .YS (n_29));
  FAX1 g476(.A (n_1), .B (n_13), .C (n_7), .YC (n_26), .YS (out_0[0]));
  FAX1 g477(.A (n_8), .B (n_15), .C (n_11), .YC (n_24), .YS (n_25));
  FAX1 g478(.A (n_6), .B (n_17), .C (n_9), .YC (n_22), .YS (n_23));
  FAX1 g479(.A (n_2), .B (n_5), .C (n_16), .YC (n_20), .YS (n_21));
  FAX1 g480(.A (n_0), .B (n_3), .C (n_12), .YC (n_18), .YS (n_19));
  FAX1 g481(.A (in_2[1]), .B (in_5[1]), .C (in_6[1]), .YC (n_16), .YS
       (n_17));
  FAX1 g482(.A (in_2[2]), .B (in_5[2]), .C (in_6[2]), .YC (n_14), .YS
       (n_15));
  FAX1 g483(.A (in_1[0]), .B (in_5[0]), .C (in_6[0]), .YC (n_12), .YS
       (n_13));
  FAX1 g484(.A (in_3[2]), .B (in_4[2]), .C (in_7[2]), .YC (n_10), .YS
       (n_11));
  FAX1 g485(.A (in_3[1]), .B (in_4[1]), .C (in_7[1]), .YC (n_8), .YS
       (n_9));
  FAX1 g486(.A (in_2[0]), .B (in_3[0]), .C (in_4[0]), .YC (n_6), .YS
       (n_7));
  HAX1 g487(.A (in_1[2]), .B (in_0[2]), .YC (n_4), .YS (n_5));
  HAX1 g488(.A (in_1[1]), .B (in_0[1]), .YC (n_2), .YS (n_3));
  HAX1 g489(.A (in_7[0]), .B (in_0[0]), .YC (n_0), .YS (n_1));
endmodule

module add8_3b(x1, x2, x3, x4, x5, x6, x7, x8, y);
  input [2:0] x1, x2, x3, x4, x5, x6, x7, x8;
  output [5:0] y;
  wire [2:0] x1, x2, x3, x4, x5, x6, x7, x8;
  wire [5:0] y;
  csa_tree_add_723_48_group_78 csa_tree_add_723_48_groupi(.in_0 (x8),
       .in_1 (x7), .in_2 (x6), .in_3 (x5), .in_4 (x4), .in_5 (x3),
       .in_6 (x1), .in_7 (x2), .out_0 (y));
endmodule

module csa_tree_add_742_48_group_76(in_0, in_1, in_2, in_3, in_4, in_5,
     in_6, in_7, out_0);
  input [4:0] in_0, in_1, in_2, in_3, in_4, in_5, in_6, in_7;
  output [7:0] out_0;
  wire [4:0] in_0, in_1, in_2, in_3, in_4, in_5, in_6, in_7;
  wire [7:0] out_0;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51, n_52, n_54, n_55, n_56, n_57;
  wire n_58, n_59, n_60, n_62, n_64, n_66;
  FAX1 g825(.A (n_44), .B (n_56), .C (n_66), .YC (out_0[7]), .YS
       (out_0[6]));
  FAX1 g826(.A (n_57), .B (n_58), .C (n_64), .YC (n_66), .YS
       (out_0[5]));
  FAX1 g827(.A (n_54), .B (n_59), .C (n_62), .YC (n_64), .YS
       (out_0[4]));
  FAX1 g828(.A (n_48), .B (n_55), .C (n_60), .YC (n_62), .YS
       (out_0[3]));
  FAX1 g829(.A (n_39), .B (n_49), .C (n_52), .YC (n_60), .YS
       (out_0[2]));
  FAX1 g830(.A (n_41), .B (n_46), .C (n_51), .YC (n_58), .YS (n_59));
  FAX1 g831(.A (n_40), .B (n_45), .C (n_50), .YC (n_56), .YS (n_57));
  FAX1 g832(.A (n_43), .B (n_38), .C (n_47), .YC (n_54), .YS (n_55));
  FAX1 g833(.A (n_31), .B (n_34), .C (n_37), .YC (n_52), .YS
       (out_0[1]));
  FAX1 g834(.A (n_26), .B (n_33), .C (n_42), .YC (n_50), .YS (n_51));
  FAX1 g835(.A (n_30), .B (n_29), .C (n_36), .YC (n_48), .YS (n_49));
  FAX1 g836(.A (n_7), .B (n_27), .C (n_28), .YC (n_46), .YS (n_47));
  FAX1 g837(.A (n_24), .B (n_16), .C (n_32), .YC (n_44), .YS (n_45));
  FAX1 g838(.A (n_12), .B (n_22), .C (n_19), .YC (n_42), .YS (n_43));
  FAX1 g839(.A (n_6), .B (n_25), .C (n_17), .YC (n_40), .YS (n_41));
  FAX1 g840(.A (n_14), .B (n_23), .C (n_13), .YC (n_38), .YS (n_39));
  FAX1 g841(.A (n_10), .B (n_21), .C (n_15), .YC (n_36), .YS (n_37));
  FAX1 g842(.A (n_3), .B (n_9), .C (n_11), .YC (n_34), .YS (out_0[0]));
  FAX1 g843(.A (in_5[4]), .B (in_6[4]), .C (n_18), .YC (n_32), .YS
       (n_33));
  FAX1 g844(.A (n_2), .B (n_1), .C (n_8), .YC (n_30), .YS (n_31));
  FAX1 g845(.A (n_0), .B (n_5), .C (n_20), .YC (n_28), .YS (n_29));
  FAX1 g846(.A (in_5[3]), .B (in_6[3]), .C (n_4), .YC (n_26), .YS
       (n_27));
  FAX1 g847(.A (in_0[4]), .B (in_1[4]), .C (in_3[4]), .YC (n_24), .YS
       (n_25));
  FAX1 g848(.A (in_2[2]), .B (in_5[2]), .C (in_6[2]), .YC (n_22), .YS
       (n_23));
  FAX1 g849(.A (in_2[1]), .B (in_5[1]), .C (in_6[1]), .YC (n_20), .YS
       (n_21));
  FAX1 g850(.A (in_0[3]), .B (in_1[3]), .C (in_3[3]), .YC (n_18), .YS
       (n_19));
  FAX1 g851(.A (in_2[4]), .B (in_4[4]), .C (in_7[4]), .YC (n_16), .YS
       (n_17));
  FAX1 g852(.A (in_3[1]), .B (in_4[1]), .C (in_7[1]), .YC (n_14), .YS
       (n_15));
  FAX1 g853(.A (in_3[2]), .B (in_4[2]), .C (in_7[2]), .YC (n_12), .YS
       (n_13));
  FAX1 g854(.A (in_2[0]), .B (in_3[0]), .C (in_4[0]), .YC (n_10), .YS
       (n_11));
  FAX1 g855(.A (in_1[0]), .B (in_5[0]), .C (in_6[0]), .YC (n_8), .YS
       (n_9));
  FAX1 g856(.A (in_2[3]), .B (in_4[3]), .C (in_7[3]), .YC (n_6), .YS
       (n_7));
  HAX1 g857(.A (in_1[2]), .B (in_0[2]), .YC (n_4), .YS (n_5));
  HAX1 g858(.A (in_7[0]), .B (in_0[0]), .YC (n_2), .YS (n_3));
  HAX1 g859(.A (in_1[1]), .B (in_0[1]), .YC (n_0), .YS (n_1));
endmodule

module add8_5b(x1, x2, x3, x4, x5, x6, x7, x8, y);
  input [4:0] x1, x2, x3, x4, x5, x6, x7, x8;
  output [7:0] y;
  wire [4:0] x1, x2, x3, x4, x5, x6, x7, x8;
  wire [7:0] y;
  csa_tree_add_742_48_group_76 csa_tree_add_742_48_groupi(.in_0 (x8),
       .in_1 (x7), .in_2 (x6), .in_3 (x5), .in_4 (x4), .in_5 (x3),
       .in_6 (x1), .in_7 (x2), .out_0 (y));
endmodule

module comp_1b(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_1;
  AND2X1 g14(.A (n_1), .B (a), .Y (a_larger));
  INVX1 g15(.A (b), .Y (n_1));
endmodule

module comp_1b_1(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g25(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g26(.A (b), .Y (n_0));
endmodule

module comp_1b_2(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g25(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g26(.A (b), .Y (n_0));
endmodule

module comp_3b(a_gt_b, a, b);
  input [2:0] a, b;
  output a_gt_b;
  wire [2:0] a, b;
  wire a_gt_b;
  wire UNCONNECTED, agt, agt_7, agt_9, e, e_11, n_0, n_1;
  wire n_2, n_3;
  comp_1b comp0(.a (a[0]), .b (b[0]), .equal (UNCONNECTED), .a_larger
       (agt_9));
  comp_1b_1 comp1(.a (a[1]), .b (b[1]), .equal (e_11), .a_larger (agt));
  comp_1b_2 comp2(.a (a[2]), .b (b[2]), .equal (e), .a_larger (agt_7));
  INVX1 g6(.A (e), .Y (n_3));
  INVX1 g7(.A (agt_7), .Y (n_2));
  OAI21X1 g37(.A (n_3), .B (n_0), .C (n_2), .Y (a_gt_b));
  AOI21X1 g38(.A (agt_9), .B (e_11), .C (agt), .Y (n_1));
  BUFX2 drc_bufs(.A (n_1), .Y (n_0));
endmodule

module counter_WIDTH10(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [9:0] out;
  output overflow;
  wire clk, en, rst;
  wire [9:0] out;
  wire overflow;
  wire n_0, n_12, n_13, n_14, n_15, n_16, n_17, n_18;
  wire n_19, n_20, n_21, n_22, n_23, n_24, n_25, n_26;
  wire n_27, n_28, n_29, n_30, n_31, n_32, n_33, n_34;
  wire n_35, n_36, n_37, n_38, n_39, n_40, n_41, n_42;
  wire n_43, n_44, n_45, n_46, n_47, n_48, n_49, n_50;
  wire n_51, n_52, n_53, n_54, n_55, n_56, n_57, n_58;
  wire n_59, n_60, n_61, n_62, n_63, n_64;
  DFFSR \out_reg[9] (.R (n_12), .S (1'b1), .CLK (clk), .D (n_53), .Q
       (n_55));
  DFFSR overflow_reg(.R (n_12), .S (1'b1), .CLK (clk), .D (n_51), .Q
       (n_54));
  INVX1 g173(.A (n_52), .Y (n_53));
  MUX2X1 g174(.A (n_49), .B (out[9]), .S (en), .Y (n_52));
  INVX1 g175(.A (n_50), .Y (n_51));
  MUX2X1 g176(.A (n_48), .B (overflow), .S (en), .Y (n_50));
  DFFSR \out_reg[8] (.R (n_12), .S (1'b1), .CLK (clk), .D (n_47), .Q
       (n_56));
  HAX1 g178(.A (out[9]), .B (n_44), .YC (n_48), .YS (n_49));
  INVX1 g179(.A (n_46), .Y (n_47));
  MUX2X1 g180(.A (n_45), .B (out[8]), .S (en), .Y (n_46));
  DFFSR \out_reg[7] (.R (n_12), .S (1'b1), .CLK (clk), .D (n_43), .Q
       (n_57));
  HAX1 g182(.A (out[8]), .B (n_40), .YC (n_44), .YS (n_45));
  INVX1 g183(.A (n_42), .Y (n_43));
  MUX2X1 g184(.A (n_41), .B (out[7]), .S (en), .Y (n_42));
  DFFSR \out_reg[6] (.R (n_12), .S (1'b1), .CLK (clk), .D (n_39), .Q
       (n_58));
  HAX1 g186(.A (out[7]), .B (n_36), .YC (n_40), .YS (n_41));
  INVX1 g187(.A (n_38), .Y (n_39));
  MUX2X1 g188(.A (n_37), .B (out[6]), .S (en), .Y (n_38));
  DFFSR \out_reg[5] (.R (n_12), .S (1'b1), .CLK (clk), .D (n_35), .Q
       (n_59));
  HAX1 g190(.A (out[6]), .B (n_32), .YC (n_36), .YS (n_37));
  INVX1 g191(.A (n_34), .Y (n_35));
  MUX2X1 g192(.A (n_33), .B (out[5]), .S (en), .Y (n_34));
  DFFSR \out_reg[4] (.R (n_12), .S (1'b1), .CLK (clk), .D (n_31), .Q
       (n_60));
  HAX1 g194(.A (out[5]), .B (n_28), .YC (n_32), .YS (n_33));
  INVX1 g195(.A (n_30), .Y (n_31));
  MUX2X1 g196(.A (n_29), .B (out[4]), .S (en), .Y (n_30));
  DFFSR \out_reg[3] (.R (n_12), .S (1'b1), .CLK (clk), .D (n_27), .Q
       (n_61));
  HAX1 g198(.A (out[4]), .B (n_24), .YC (n_28), .YS (n_29));
  INVX1 g199(.A (n_26), .Y (n_27));
  MUX2X1 g200(.A (n_25), .B (out[3]), .S (en), .Y (n_26));
  DFFSR \out_reg[2] (.R (n_12), .S (1'b1), .CLK (clk), .D (n_23), .Q
       (n_62));
  HAX1 g202(.A (out[3]), .B (n_20), .YC (n_24), .YS (n_25));
  INVX1 g203(.A (n_22), .Y (n_23));
  MUX2X1 g204(.A (n_21), .B (out[2]), .S (en), .Y (n_22));
  DFFSR \out_reg[1] (.R (n_12), .S (1'b1), .CLK (clk), .D (n_19), .Q
       (n_63));
  HAX1 g206(.A (out[2]), .B (n_16), .YC (n_20), .YS (n_21));
  INVX1 g207(.A (n_18), .Y (n_19));
  MUX2X1 g208(.A (n_17), .B (out[1]), .S (en), .Y (n_18));
  DFFSR \out_reg[0] (.R (n_12), .S (1'b1), .CLK (clk), .D (n_15), .Q
       (n_64));
  HAX1 g210(.A (out[1]), .B (out[0]), .YC (n_16), .YS (n_17));
  OAI21X1 g211(.A (out[0]), .B (n_13), .C (n_0), .Y (n_15));
  NAND2X1 g212(.A (out[0]), .B (n_13), .Y (n_14));
  INVX1 g213(.A (en), .Y (n_13));
  INVX1 g214(.A (rst), .Y (n_12));
  BUFX2 drc_bufs271(.A (n_14), .Y (n_0));
  BUFX2 drc_bufs273(.A (n_64), .Y (out[0]));
  BUFX2 drc_bufs274(.A (n_59), .Y (out[5]));
  BUFX2 drc_bufs275(.A (n_58), .Y (out[6]));
  BUFX2 drc_bufs276(.A (n_57), .Y (out[7]));
  BUFX2 drc_bufs277(.A (n_56), .Y (out[8]));
  BUFX2 drc_bufs278(.A (n_55), .Y (out[9]));
  BUFX2 drc_bufs279(.A (n_54), .Y (overflow));
  BUFX2 drc_bufs280(.A (n_60), .Y (out[4]));
  BUFX2 drc_bufs281(.A (n_63), .Y (out[1]));
  BUFX2 drc_bufs282(.A (n_62), .Y (out[2]));
  BUFX2 drc_bufs283(.A (n_61), .Y (out[3]));
endmodule

module counter_WIDTH11(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [10:0] out;
  output overflow;
  wire clk, en, rst;
  wire [10:0] out;
  wire overflow;
  wire n_0, n_13, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_33, n_34, n_35;
  wire n_36, n_37, n_38, n_39, n_40, n_41, n_42, n_43;
  wire n_44, n_45, n_46, n_47, n_48, n_49, n_50, n_51;
  wire n_52, n_53, n_54, n_55, n_56, n_57, n_58, n_59;
  wire n_60, n_61, n_62, n_63, n_64, n_65, n_66, n_67;
  wire n_68, n_69, n_70;
  DFFSR \out_reg[10] (.R (n_13), .S (1'b1), .CLK (clk), .D (n_58), .Q
       (n_69));
  DFFSR overflow_reg(.R (n_13), .S (1'b1), .CLK (clk), .D (n_56), .Q
       (n_59));
  INVX1 g185(.A (n_57), .Y (n_58));
  MUX2X1 g186(.A (n_54), .B (out[10]), .S (en), .Y (n_57));
  INVX1 g187(.A (n_55), .Y (n_56));
  MUX2X1 g188(.A (n_53), .B (overflow), .S (en), .Y (n_55));
  DFFSR \out_reg[9] (.R (n_13), .S (1'b1), .CLK (clk), .D (n_52), .Q
       (n_60));
  HAX1 g190(.A (out[10]), .B (n_49), .YC (n_53), .YS (n_54));
  INVX1 g191(.A (n_51), .Y (n_52));
  MUX2X1 g192(.A (n_50), .B (out[9]), .S (en), .Y (n_51));
  DFFSR \out_reg[8] (.R (n_13), .S (1'b1), .CLK (clk), .D (n_48), .Q
       (n_61));
  HAX1 g194(.A (out[9]), .B (n_45), .YC (n_49), .YS (n_50));
  INVX1 g195(.A (n_47), .Y (n_48));
  MUX2X1 g196(.A (n_46), .B (out[8]), .S (en), .Y (n_47));
  DFFSR \out_reg[7] (.R (n_13), .S (1'b1), .CLK (clk), .D (n_44), .Q
       (n_62));
  HAX1 g198(.A (out[8]), .B (n_41), .YC (n_45), .YS (n_46));
  INVX1 g199(.A (n_43), .Y (n_44));
  MUX2X1 g200(.A (n_42), .B (out[7]), .S (en), .Y (n_43));
  DFFSR \out_reg[6] (.R (n_13), .S (1'b1), .CLK (clk), .D (n_40), .Q
       (n_63));
  HAX1 g202(.A (out[7]), .B (n_37), .YC (n_41), .YS (n_42));
  INVX1 g203(.A (n_39), .Y (n_40));
  MUX2X1 g204(.A (n_38), .B (out[6]), .S (en), .Y (n_39));
  DFFSR \out_reg[5] (.R (n_13), .S (1'b1), .CLK (clk), .D (n_36), .Q
       (n_64));
  HAX1 g206(.A (out[6]), .B (n_33), .YC (n_37), .YS (n_38));
  INVX1 g207(.A (n_35), .Y (n_36));
  MUX2X1 g208(.A (n_34), .B (out[5]), .S (en), .Y (n_35));
  DFFSR \out_reg[4] (.R (n_13), .S (1'b1), .CLK (clk), .D (n_32), .Q
       (n_65));
  HAX1 g210(.A (out[5]), .B (n_29), .YC (n_33), .YS (n_34));
  INVX1 g211(.A (n_31), .Y (n_32));
  MUX2X1 g212(.A (n_30), .B (out[4]), .S (en), .Y (n_31));
  DFFSR \out_reg[3] (.R (n_13), .S (1'b1), .CLK (clk), .D (n_28), .Q
       (n_66));
  HAX1 g214(.A (out[4]), .B (n_25), .YC (n_29), .YS (n_30));
  INVX1 g215(.A (n_27), .Y (n_28));
  MUX2X1 g216(.A (n_26), .B (out[3]), .S (en), .Y (n_27));
  DFFSR \out_reg[2] (.R (n_13), .S (1'b1), .CLK (clk), .D (n_24), .Q
       (n_67));
  HAX1 g218(.A (out[3]), .B (n_21), .YC (n_25), .YS (n_26));
  INVX1 g219(.A (n_23), .Y (n_24));
  MUX2X1 g220(.A (n_22), .B (out[2]), .S (en), .Y (n_23));
  DFFSR \out_reg[1] (.R (n_13), .S (1'b1), .CLK (clk), .D (n_20), .Q
       (n_68));
  HAX1 g222(.A (out[2]), .B (n_17), .YC (n_21), .YS (n_22));
  INVX1 g223(.A (n_19), .Y (n_20));
  MUX2X1 g224(.A (n_18), .B (out[1]), .S (en), .Y (n_19));
  DFFSR \out_reg[0] (.R (n_13), .S (1'b1), .CLK (clk), .D (n_16), .Q
       (n_70));
  HAX1 g226(.A (out[1]), .B (out[0]), .YC (n_17), .YS (n_18));
  OAI21X1 g227(.A (out[0]), .B (n_14), .C (n_0), .Y (n_16));
  NAND2X1 g228(.A (out[0]), .B (n_14), .Y (n_15));
  INVX1 g229(.A (en), .Y (n_14));
  INVX1 g230(.A (rst), .Y (n_13));
  BUFX2 drc_bufs292(.A (n_15), .Y (n_0));
  BUFX2 drc_bufs294(.A (n_66), .Y (out[3]));
  BUFX2 drc_bufs295(.A (n_59), .Y (overflow));
  BUFX2 drc_bufs296(.A (n_65), .Y (out[4]));
  BUFX2 drc_bufs297(.A (n_64), .Y (out[5]));
  BUFX2 drc_bufs298(.A (n_63), .Y (out[6]));
  BUFX2 drc_bufs299(.A (n_62), .Y (out[7]));
  BUFX2 drc_bufs300(.A (n_61), .Y (out[8]));
  BUFX2 drc_bufs301(.A (n_60), .Y (out[9]));
  BUFX2 drc_bufs302(.A (n_70), .Y (out[0]));
  BUFX2 drc_bufs303(.A (n_67), .Y (out[2]));
  BUFX2 drc_bufs304(.A (n_69), .Y (out[10]));
  BUFX2 drc_bufs305(.A (n_68), .Y (out[1]));
endmodule

module counter_WIDTH12(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [11:0] out;
  output overflow;
  wire clk, en, rst;
  wire [11:0] out;
  wire overflow;
  wire n_0, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_14, n_15, n_16, n_17, n_18;
  wire n_19, n_20, n_21, n_22, n_23, n_24, n_25, n_26;
  wire n_27, n_28, n_29, n_30, n_31, n_32, n_33, n_34;
  wire n_35, n_36, n_37, n_38, n_39, n_40, n_41, n_42;
  wire n_43, n_44, n_45, n_46, n_47, n_48, n_49, n_50;
  wire n_51, n_52, n_53, n_54, n_55, n_56, n_57, n_58;
  wire n_59, n_60, n_61, n_62, n_63, n_64, n_65, n_66;
  wire n_67, n_68, n_69, n_70, n_71, n_72, n_73, n_74;
  wire n_75, n_76;
  DFFSR \out_reg[11] (.R (n_14), .S (1'b1), .CLK (clk), .D (n_63), .Q
       (n_64));
  DFFSR overflow_reg(.R (n_14), .S (1'b1), .CLK (clk), .D (n_61), .Q
       (n_73));
  INVX1 g198(.A (n_62), .Y (n_63));
  MUX2X1 g199(.A (n_59), .B (n_12), .S (en), .Y (n_62));
  INVX1 g200(.A (n_60), .Y (n_61));
  MUX2X1 g201(.A (n_58), .B (overflow), .S (en), .Y (n_60));
  DFFSR \out_reg[10] (.R (n_14), .S (1'b1), .CLK (clk), .D (n_57), .Q
       (n_65));
  HAX1 g203(.A (n_12), .B (n_54), .YC (n_58), .YS (n_59));
  INVX1 g204(.A (n_56), .Y (n_57));
  MUX2X1 g205(.A (n_55), .B (n_4), .S (en), .Y (n_56));
  DFFSR \out_reg[9] (.R (n_14), .S (1'b1), .CLK (clk), .D (n_53), .Q
       (n_66));
  HAX1 g207(.A (n_4), .B (n_50), .YC (n_54), .YS (n_55));
  INVX1 g208(.A (n_52), .Y (n_53));
  MUX2X1 g209(.A (n_51), .B (n_10), .S (en), .Y (n_52));
  DFFSR \out_reg[8] (.R (n_14), .S (1'b1), .CLK (clk), .D (n_49), .Q
       (n_67));
  HAX1 g211(.A (n_10), .B (n_46), .YC (n_50), .YS (n_51));
  INVX1 g212(.A (n_48), .Y (n_49));
  MUX2X1 g213(.A (n_47), .B (n_3), .S (en), .Y (n_48));
  DFFSR \out_reg[7] (.R (n_14), .S (1'b1), .CLK (clk), .D (n_45), .Q
       (n_68));
  HAX1 g215(.A (n_3), .B (n_42), .YC (n_46), .YS (n_47));
  INVX1 g216(.A (n_44), .Y (n_45));
  MUX2X1 g217(.A (n_43), .B (n_8), .S (en), .Y (n_44));
  DFFSR \out_reg[6] (.R (n_14), .S (1'b1), .CLK (clk), .D (n_41), .Q
       (n_69));
  HAX1 g219(.A (n_8), .B (n_38), .YC (n_42), .YS (n_43));
  INVX1 g220(.A (n_40), .Y (n_41));
  MUX2X1 g221(.A (n_39), .B (n_6), .S (en), .Y (n_40));
  DFFSR \out_reg[5] (.R (n_14), .S (1'b1), .CLK (clk), .D (n_37), .Q
       (n_70));
  HAX1 g223(.A (n_6), .B (n_34), .YC (n_38), .YS (n_39));
  INVX1 g224(.A (n_36), .Y (n_37));
  MUX2X1 g225(.A (n_35), .B (n_9), .S (en), .Y (n_36));
  DFFSR \out_reg[4] (.R (n_14), .S (1'b1), .CLK (clk), .D (n_33), .Q
       (n_71));
  HAX1 g227(.A (n_9), .B (n_30), .YC (n_34), .YS (n_35));
  INVX1 g228(.A (n_32), .Y (n_33));
  MUX2X1 g229(.A (n_31), .B (n_11), .S (en), .Y (n_32));
  DFFSR \out_reg[3] (.R (n_14), .S (1'b1), .CLK (clk), .D (n_29), .Q
       (n_72));
  HAX1 g231(.A (n_11), .B (n_26), .YC (n_30), .YS (n_31));
  INVX1 g232(.A (n_28), .Y (n_29));
  MUX2X1 g233(.A (n_27), .B (n_5), .S (en), .Y (n_28));
  DFFSR \out_reg[2] (.R (n_14), .S (1'b1), .CLK (clk), .D (n_25), .Q
       (n_76));
  HAX1 g235(.A (n_5), .B (n_22), .YC (n_26), .YS (n_27));
  INVX1 g236(.A (n_24), .Y (n_25));
  MUX2X1 g237(.A (n_23), .B (n_7), .S (en), .Y (n_24));
  DFFSR \out_reg[1] (.R (n_14), .S (1'b1), .CLK (clk), .D (n_21), .Q
       (n_74));
  HAX1 g239(.A (n_7), .B (n_18), .YC (n_22), .YS (n_23));
  INVX1 g240(.A (n_20), .Y (n_21));
  MUX2X1 g241(.A (n_19), .B (out[1]), .S (en), .Y (n_20));
  DFFSR \out_reg[0] (.R (n_14), .S (1'b1), .CLK (clk), .D (n_17), .Q
       (n_75));
  HAX1 g243(.A (out[1]), .B (out[0]), .YC (n_18), .YS (n_19));
  OAI21X1 g244(.A (out[0]), .B (n_15), .C (n_0), .Y (n_17));
  NAND2X1 g245(.A (out[0]), .B (n_15), .Y (n_16));
  INVX1 g246(.A (en), .Y (n_15));
  INVX1 g247(.A (rst), .Y (n_14));
  BUFX2 drc_bufs304(.A (n_16), .Y (n_0));
  BUFX2 drc_bufs306(.A (n_75), .Y (out[0]));
  BUFX2 drc_bufs307(.A (n_64), .Y (n_12));
  BUFX2 drc_bufs308(.A (n_65), .Y (n_4));
  BUFX2 drc_bufs309(.A (n_66), .Y (n_10));
  BUFX2 drc_bufs310(.A (n_67), .Y (n_3));
  BUFX2 drc_bufs311(.A (n_68), .Y (n_8));
  BUFX2 drc_bufs312(.A (n_69), .Y (n_6));
  BUFX2 drc_bufs313(.A (n_71), .Y (n_11));
  BUFX2 drc_bufs314(.A (n_70), .Y (n_9));
  BUFX2 drc_bufs315(.A (n_72), .Y (n_5));
  BUFX2 drc_bufs316(.A (n_73), .Y (overflow));
  BUFX2 drc_bufs317(.A (n_74), .Y (out[1]));
  BUFX2 drc_bufs318(.A (n_76), .Y (n_7));
endmodule

module counter_WIDTH13(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [12:0] out;
  output overflow;
  wire clk, en, rst;
  wire [12:0] out;
  wire overflow;
  wire n_0, n_15, n_16, n_17, n_18, n_19, n_20, n_21;
  wire n_22, n_23, n_24, n_25, n_26, n_27, n_28, n_29;
  wire n_30, n_31, n_32, n_33, n_34, n_35, n_36, n_37;
  wire n_38, n_39, n_40, n_41, n_42, n_43, n_44, n_45;
  wire n_46, n_47, n_48, n_49, n_50, n_51, n_52, n_53;
  wire n_54, n_55, n_56, n_57, n_58, n_59, n_60, n_61;
  wire n_62, n_63, n_64, n_65, n_66, n_67, n_68, n_69;
  wire n_70, n_71, n_72, n_73, n_74, n_75, n_76, n_77;
  wire n_78, n_79, n_80, n_81, n_82;
  DFFSR \out_reg[12] (.R (n_15), .S (1'b1), .CLK (clk), .D (n_68), .Q
       (n_79));
  DFFSR overflow_reg(.R (n_15), .S (1'b1), .CLK (clk), .D (n_66), .Q
       (n_69));
  INVX1 g227(.A (n_67), .Y (n_68));
  MUX2X1 g228(.A (n_64), .B (out[12]), .S (en), .Y (n_67));
  INVX1 g229(.A (n_65), .Y (n_66));
  MUX2X1 g230(.A (n_63), .B (overflow), .S (en), .Y (n_65));
  DFFSR \out_reg[11] (.R (n_15), .S (1'b1), .CLK (clk), .D (n_62), .Q
       (n_80));
  HAX1 g232(.A (out[12]), .B (n_59), .YC (n_63), .YS (n_64));
  INVX1 g233(.A (n_61), .Y (n_62));
  MUX2X1 g234(.A (n_60), .B (out[11]), .S (en), .Y (n_61));
  DFFSR \out_reg[10] (.R (n_15), .S (1'b1), .CLK (clk), .D (n_58), .Q
       (n_81));
  HAX1 g236(.A (out[11]), .B (n_55), .YC (n_59), .YS (n_60));
  INVX1 g237(.A (n_57), .Y (n_58));
  MUX2X1 g238(.A (n_56), .B (out[10]), .S (en), .Y (n_57));
  DFFSR \out_reg[9] (.R (n_15), .S (1'b1), .CLK (clk), .D (n_54), .Q
       (n_70));
  HAX1 g240(.A (out[10]), .B (n_51), .YC (n_55), .YS (n_56));
  INVX1 g241(.A (n_53), .Y (n_54));
  MUX2X1 g242(.A (n_52), .B (out[9]), .S (en), .Y (n_53));
  DFFSR \out_reg[8] (.R (n_15), .S (1'b1), .CLK (clk), .D (n_50), .Q
       (n_71));
  HAX1 g244(.A (out[9]), .B (n_47), .YC (n_51), .YS (n_52));
  INVX1 g245(.A (n_49), .Y (n_50));
  MUX2X1 g246(.A (n_48), .B (out[8]), .S (en), .Y (n_49));
  DFFSR \out_reg[7] (.R (n_15), .S (1'b1), .CLK (clk), .D (n_46), .Q
       (n_72));
  HAX1 g248(.A (out[8]), .B (n_43), .YC (n_47), .YS (n_48));
  INVX1 g249(.A (n_45), .Y (n_46));
  MUX2X1 g250(.A (n_44), .B (out[7]), .S (en), .Y (n_45));
  DFFSR \out_reg[6] (.R (n_15), .S (1'b1), .CLK (clk), .D (n_42), .Q
       (n_73));
  HAX1 g252(.A (out[7]), .B (n_39), .YC (n_43), .YS (n_44));
  INVX1 g253(.A (n_41), .Y (n_42));
  MUX2X1 g254(.A (n_40), .B (out[6]), .S (en), .Y (n_41));
  DFFSR \out_reg[5] (.R (n_15), .S (1'b1), .CLK (clk), .D (n_38), .Q
       (n_74));
  HAX1 g256(.A (out[6]), .B (n_35), .YC (n_39), .YS (n_40));
  INVX1 g257(.A (n_37), .Y (n_38));
  MUX2X1 g258(.A (n_36), .B (out[5]), .S (en), .Y (n_37));
  DFFSR \out_reg[4] (.R (n_15), .S (1'b1), .CLK (clk), .D (n_34), .Q
       (n_75));
  HAX1 g260(.A (out[5]), .B (n_31), .YC (n_35), .YS (n_36));
  INVX1 g261(.A (n_33), .Y (n_34));
  MUX2X1 g262(.A (n_32), .B (out[4]), .S (en), .Y (n_33));
  DFFSR \out_reg[3] (.R (n_15), .S (1'b1), .CLK (clk), .D (n_30), .Q
       (n_76));
  HAX1 g264(.A (out[4]), .B (n_27), .YC (n_31), .YS (n_32));
  INVX1 g265(.A (n_29), .Y (n_30));
  MUX2X1 g266(.A (n_28), .B (out[3]), .S (en), .Y (n_29));
  DFFSR \out_reg[2] (.R (n_15), .S (1'b1), .CLK (clk), .D (n_26), .Q
       (n_77));
  HAX1 g268(.A (out[3]), .B (n_23), .YC (n_27), .YS (n_28));
  INVX1 g269(.A (n_25), .Y (n_26));
  MUX2X1 g270(.A (n_24), .B (out[2]), .S (en), .Y (n_25));
  DFFSR \out_reg[1] (.R (n_15), .S (1'b1), .CLK (clk), .D (n_22), .Q
       (n_78));
  HAX1 g272(.A (out[2]), .B (n_19), .YC (n_23), .YS (n_24));
  INVX1 g273(.A (n_21), .Y (n_22));
  MUX2X1 g274(.A (n_20), .B (out[1]), .S (en), .Y (n_21));
  DFFSR \out_reg[0] (.R (n_15), .S (1'b1), .CLK (clk), .D (n_18), .Q
       (n_82));
  HAX1 g276(.A (out[1]), .B (out[0]), .YC (n_19), .YS (n_20));
  OAI21X1 g277(.A (out[0]), .B (n_16), .C (n_0), .Y (n_18));
  NAND2X1 g278(.A (out[0]), .B (n_16), .Y (n_17));
  INVX1 g279(.A (en), .Y (n_16));
  INVX1 g280(.A (rst), .Y (n_15));
  BUFX2 drc_bufs352(.A (n_17), .Y (n_0));
  BUFX2 drc_bufs354(.A (n_80), .Y (out[11]));
  BUFX2 drc_bufs355(.A (n_69), .Y (overflow));
  BUFX2 drc_bufs356(.A (n_79), .Y (out[12]));
  BUFX2 drc_bufs357(.A (n_78), .Y (out[1]));
  BUFX2 drc_bufs358(.A (n_77), .Y (out[2]));
  BUFX2 drc_bufs359(.A (n_73), .Y (out[6]));
  BUFX2 drc_bufs360(.A (n_76), .Y (out[3]));
  BUFX2 drc_bufs361(.A (n_75), .Y (out[4]));
  BUFX2 drc_bufs362(.A (n_74), .Y (out[5]));
  BUFX2 drc_bufs363(.A (n_82), .Y (out[0]));
  BUFX2 drc_bufs364(.A (n_72), .Y (out[7]));
  BUFX2 drc_bufs365(.A (n_71), .Y (out[8]));
  BUFX2 drc_bufs366(.A (n_70), .Y (out[9]));
  BUFX2 drc_bufs367(.A (n_81), .Y (out[10]));
endmodule

module counter_WIDTH14(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [13:0] out;
  output overflow;
  wire clk, en, rst;
  wire [13:0] out;
  wire overflow;
  wire n_0, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30;
  wire n_31, n_32, n_33, n_34, n_35, n_36, n_37, n_38;
  wire n_39, n_40, n_41, n_42, n_43, n_44, n_45, n_46;
  wire n_47, n_48, n_49, n_50, n_51, n_52, n_53, n_54;
  wire n_55, n_56, n_57, n_58, n_59, n_60, n_61, n_62;
  wire n_63, n_64, n_65, n_66, n_67, n_68, n_69, n_70;
  wire n_71, n_72, n_73, n_74, n_75, n_76, n_77, n_78;
  wire n_79, n_80, n_81, n_82, n_83, n_84, n_85, n_86;
  wire n_87, n_88;
  DFFSR \out_reg[13] (.R (n_17), .S (1'b1), .CLK (clk), .D (n_73), .Q
       (n_84));
  DFFSR overflow_reg(.R (n_17), .S (1'b1), .CLK (clk), .D (n_71), .Q
       (n_74));
  INVX1 g249(.A (n_72), .Y (n_73));
  MUX2X1 g250(.A (n_69), .B (out[13]), .S (en), .Y (n_72));
  INVX1 g251(.A (n_70), .Y (n_71));
  MUX2X1 g252(.A (n_68), .B (overflow), .S (en), .Y (n_70));
  DFFSR \out_reg[12] (.R (n_17), .S (1'b1), .CLK (clk), .D (n_67), .Q
       (n_85));
  HAX1 g254(.A (out[13]), .B (n_64), .YC (n_68), .YS (n_69));
  INVX1 g255(.A (n_66), .Y (n_67));
  MUX2X1 g256(.A (n_65), .B (out[12]), .S (en), .Y (n_66));
  DFFSR \out_reg[11] (.R (n_17), .S (1'b1), .CLK (clk), .D (n_63), .Q
       (n_86));
  HAX1 g258(.A (out[12]), .B (n_60), .YC (n_64), .YS (n_65));
  INVX1 g259(.A (n_62), .Y (n_63));
  MUX2X1 g260(.A (n_61), .B (out[11]), .S (en), .Y (n_62));
  DFFSR \out_reg[10] (.R (n_17), .S (1'b1), .CLK (clk), .D (n_59), .Q
       (n_87));
  HAX1 g262(.A (out[11]), .B (n_56), .YC (n_60), .YS (n_61));
  INVX1 g263(.A (n_58), .Y (n_59));
  MUX2X1 g264(.A (n_57), .B (out[10]), .S (en), .Y (n_58));
  DFFSR \out_reg[9] (.R (n_17), .S (1'b1), .CLK (clk), .D (n_55), .Q
       (n_75));
  HAX1 g266(.A (out[10]), .B (n_52), .YC (n_56), .YS (n_57));
  INVX1 g267(.A (n_54), .Y (n_55));
  MUX2X1 g268(.A (n_53), .B (out[9]), .S (en), .Y (n_54));
  DFFSR \out_reg[8] (.R (n_17), .S (1'b1), .CLK (clk), .D (n_51), .Q
       (n_76));
  HAX1 g270(.A (out[9]), .B (n_48), .YC (n_52), .YS (n_53));
  INVX1 g271(.A (n_50), .Y (n_51));
  MUX2X1 g272(.A (n_49), .B (out[8]), .S (en), .Y (n_50));
  DFFSR \out_reg[7] (.R (n_17), .S (1'b1), .CLK (clk), .D (n_47), .Q
       (n_77));
  HAX1 g274(.A (out[8]), .B (n_44), .YC (n_48), .YS (n_49));
  INVX1 g275(.A (n_46), .Y (n_47));
  MUX2X1 g276(.A (n_45), .B (out[7]), .S (en), .Y (n_46));
  DFFSR \out_reg[6] (.R (n_17), .S (1'b1), .CLK (clk), .D (n_43), .Q
       (n_78));
  HAX1 g278(.A (out[7]), .B (n_40), .YC (n_44), .YS (n_45));
  INVX1 g279(.A (n_42), .Y (n_43));
  MUX2X1 g280(.A (n_41), .B (out[6]), .S (en), .Y (n_42));
  DFFSR \out_reg[5] (.R (n_17), .S (1'b1), .CLK (clk), .D (n_39), .Q
       (n_79));
  HAX1 g282(.A (out[6]), .B (n_36), .YC (n_40), .YS (n_41));
  INVX1 g283(.A (n_38), .Y (n_39));
  MUX2X1 g284(.A (n_37), .B (out[5]), .S (en), .Y (n_38));
  DFFSR \out_reg[4] (.R (n_17), .S (1'b1), .CLK (clk), .D (n_35), .Q
       (n_80));
  HAX1 g286(.A (out[5]), .B (n_32), .YC (n_36), .YS (n_37));
  INVX1 g287(.A (n_34), .Y (n_35));
  MUX2X1 g288(.A (n_33), .B (out[4]), .S (en), .Y (n_34));
  DFFSR \out_reg[3] (.R (n_17), .S (1'b1), .CLK (clk), .D (n_31), .Q
       (n_81));
  HAX1 g290(.A (out[4]), .B (n_28), .YC (n_32), .YS (n_33));
  INVX1 g291(.A (n_30), .Y (n_31));
  MUX2X1 g292(.A (n_29), .B (out[3]), .S (en), .Y (n_30));
  DFFSR \out_reg[2] (.R (n_17), .S (1'b1), .CLK (clk), .D (n_27), .Q
       (n_82));
  HAX1 g294(.A (out[3]), .B (n_24), .YC (n_28), .YS (n_29));
  INVX1 g295(.A (n_26), .Y (n_27));
  MUX2X1 g296(.A (n_25), .B (out[2]), .S (en), .Y (n_26));
  DFFSR \out_reg[1] (.R (n_17), .S (1'b1), .CLK (clk), .D (n_23), .Q
       (n_83));
  HAX1 g298(.A (out[2]), .B (n_20), .YC (n_24), .YS (n_25));
  INVX1 g299(.A (n_22), .Y (n_23));
  MUX2X1 g300(.A (n_21), .B (out[1]), .S (en), .Y (n_22));
  DFFSR \out_reg[0] (.R (n_17), .S (1'b1), .CLK (clk), .D (n_19), .Q
       (n_88));
  HAX1 g302(.A (out[1]), .B (out[0]), .YC (n_20), .YS (n_21));
  OAI21X1 g303(.A (out[0]), .B (n_16), .C (n_0), .Y (n_19));
  NAND2X1 g304(.A (out[0]), .B (n_16), .Y (n_18));
  INVX1 g305(.A (rst), .Y (n_17));
  INVX1 g306(.A (en), .Y (n_16));
  BUFX2 drc_bufs383(.A (n_18), .Y (n_0));
  BUFX2 drc_bufs385(.A (n_87), .Y (out[10]));
  BUFX2 drc_bufs386(.A (n_86), .Y (out[11]));
  BUFX2 drc_bufs387(.A (n_85), .Y (out[12]));
  BUFX2 drc_bufs388(.A (n_76), .Y (out[8]));
  BUFX2 drc_bufs389(.A (n_84), .Y (out[13]));
  BUFX2 drc_bufs390(.A (n_83), .Y (out[1]));
  BUFX2 drc_bufs391(.A (n_82), .Y (out[2]));
  BUFX2 drc_bufs392(.A (n_81), .Y (out[3]));
  BUFX2 drc_bufs393(.A (n_80), .Y (out[4]));
  BUFX2 drc_bufs394(.A (n_88), .Y (out[0]));
  BUFX2 drc_bufs395(.A (n_79), .Y (out[5]));
  BUFX2 drc_bufs396(.A (n_78), .Y (out[6]));
  BUFX2 drc_bufs397(.A (n_77), .Y (out[7]));
  BUFX2 drc_bufs398(.A (n_75), .Y (out[9]));
  BUFX2 drc_bufs399(.A (n_74), .Y (overflow));
endmodule

module counter_WIDTH15(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [14:0] out;
  output overflow;
  wire clk, en, rst;
  wire [14:0] out;
  wire overflow;
  wire n_0, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_84, n_85, n_86, n_87;
  wire n_88, n_89, n_90, n_91, n_92, n_93, n_94;
  DFFSR \out_reg[14] (.R (n_17), .S (1'b1), .CLK (clk), .D (n_78), .Q
       (n_89));
  DFFSR overflow_reg(.R (n_17), .S (1'b1), .CLK (clk), .D (n_76), .Q
       (n_79));
  INVX1 g486(.A (n_77), .Y (n_78));
  MUX2X1 g487(.A (n_74), .B (out[14]), .S (en), .Y (n_77));
  INVX1 g488(.A (n_75), .Y (n_76));
  MUX2X1 g489(.A (n_73), .B (overflow), .S (en), .Y (n_75));
  DFFSR \out_reg[13] (.R (n_17), .S (1'b1), .CLK (clk), .D (n_72), .Q
       (n_90));
  HAX1 g491(.A (out[14]), .B (n_69), .YC (n_73), .YS (n_74));
  INVX1 g492(.A (n_71), .Y (n_72));
  MUX2X1 g493(.A (n_70), .B (out[13]), .S (en), .Y (n_71));
  DFFSR \out_reg[12] (.R (n_17), .S (1'b1), .CLK (clk), .D (n_68), .Q
       (n_91));
  HAX1 g495(.A (out[13]), .B (n_65), .YC (n_69), .YS (n_70));
  INVX1 g496(.A (n_67), .Y (n_68));
  MUX2X1 g497(.A (n_66), .B (out[12]), .S (en), .Y (n_67));
  DFFSR \out_reg[11] (.R (n_17), .S (1'b1), .CLK (clk), .D (n_64), .Q
       (n_92));
  HAX1 g499(.A (out[12]), .B (n_61), .YC (n_65), .YS (n_66));
  INVX1 g500(.A (n_63), .Y (n_64));
  MUX2X1 g501(.A (n_62), .B (out[11]), .S (en), .Y (n_63));
  DFFSR \out_reg[10] (.R (n_17), .S (1'b1), .CLK (clk), .D (n_60), .Q
       (n_93));
  HAX1 g503(.A (out[11]), .B (n_57), .YC (n_61), .YS (n_62));
  INVX1 g504(.A (n_59), .Y (n_60));
  MUX2X1 g505(.A (n_58), .B (out[10]), .S (en), .Y (n_59));
  DFFSR \out_reg[9] (.R (n_17), .S (1'b1), .CLK (clk), .D (n_56), .Q
       (n_80));
  HAX1 g507(.A (out[10]), .B (n_53), .YC (n_57), .YS (n_58));
  INVX1 g508(.A (n_55), .Y (n_56));
  MUX2X1 g509(.A (n_54), .B (out[9]), .S (en), .Y (n_55));
  DFFSR \out_reg[8] (.R (n_17), .S (1'b1), .CLK (clk), .D (n_52), .Q
       (n_81));
  HAX1 g511(.A (out[9]), .B (n_49), .YC (n_53), .YS (n_54));
  INVX1 g512(.A (n_51), .Y (n_52));
  MUX2X1 g513(.A (n_50), .B (out[8]), .S (en), .Y (n_51));
  DFFSR \out_reg[7] (.R (n_17), .S (1'b1), .CLK (clk), .D (n_48), .Q
       (n_82));
  HAX1 g515(.A (out[8]), .B (n_45), .YC (n_49), .YS (n_50));
  INVX1 g516(.A (n_47), .Y (n_48));
  MUX2X1 g517(.A (n_46), .B (out[7]), .S (en), .Y (n_47));
  DFFSR \out_reg[6] (.R (n_17), .S (1'b1), .CLK (clk), .D (n_44), .Q
       (n_83));
  HAX1 g519(.A (out[7]), .B (n_41), .YC (n_45), .YS (n_46));
  INVX1 g520(.A (n_43), .Y (n_44));
  MUX2X1 g521(.A (n_42), .B (out[6]), .S (en), .Y (n_43));
  DFFSR \out_reg[5] (.R (n_17), .S (1'b1), .CLK (clk), .D (n_40), .Q
       (n_84));
  HAX1 g523(.A (out[6]), .B (n_37), .YC (n_41), .YS (n_42));
  INVX1 g524(.A (n_39), .Y (n_40));
  MUX2X1 g525(.A (n_38), .B (out[5]), .S (en), .Y (n_39));
  DFFSR \out_reg[4] (.R (n_17), .S (1'b1), .CLK (clk), .D (n_36), .Q
       (n_85));
  HAX1 g527(.A (out[5]), .B (n_33), .YC (n_37), .YS (n_38));
  INVX1 g528(.A (n_35), .Y (n_36));
  MUX2X1 g529(.A (n_34), .B (out[4]), .S (en), .Y (n_35));
  DFFSR \out_reg[3] (.R (n_17), .S (1'b1), .CLK (clk), .D (n_32), .Q
       (n_86));
  HAX1 g531(.A (out[4]), .B (n_29), .YC (n_33), .YS (n_34));
  INVX1 g532(.A (n_31), .Y (n_32));
  MUX2X1 g533(.A (n_30), .B (out[3]), .S (en), .Y (n_31));
  DFFSR \out_reg[2] (.R (n_17), .S (1'b1), .CLK (clk), .D (n_28), .Q
       (n_87));
  HAX1 g535(.A (out[3]), .B (n_25), .YC (n_29), .YS (n_30));
  INVX1 g536(.A (n_27), .Y (n_28));
  MUX2X1 g537(.A (n_26), .B (out[2]), .S (en), .Y (n_27));
  DFFSR \out_reg[1] (.R (n_17), .S (1'b1), .CLK (clk), .D (n_24), .Q
       (n_88));
  HAX1 g539(.A (out[2]), .B (n_21), .YC (n_25), .YS (n_26));
  INVX1 g540(.A (n_23), .Y (n_24));
  MUX2X1 g541(.A (n_22), .B (out[1]), .S (en), .Y (n_23));
  DFFSR \out_reg[0] (.R (n_17), .S (1'b1), .CLK (clk), .D (n_20), .Q
       (n_94));
  HAX1 g543(.A (out[1]), .B (out[0]), .YC (n_21), .YS (n_22));
  OAI21X1 g544(.A (out[0]), .B (n_18), .C (n_0), .Y (n_20));
  NAND2X1 g545(.A (out[0]), .B (n_18), .Y (n_19));
  INVX1 g546(.A (en), .Y (n_18));
  INVX1 g547(.A (rst), .Y (n_17));
  BUFX2 drc_bufs629(.A (n_19), .Y (n_0));
  BUFX2 drc_bufs631(.A (n_94), .Y (out[0]));
  BUFX2 drc_bufs632(.A (n_79), .Y (overflow));
  BUFX2 drc_bufs633(.A (n_93), .Y (out[10]));
  BUFX2 drc_bufs634(.A (n_92), .Y (out[11]));
  BUFX2 drc_bufs635(.A (n_91), .Y (out[12]));
  BUFX2 drc_bufs636(.A (n_83), .Y (out[6]));
  BUFX2 drc_bufs637(.A (n_90), .Y (out[13]));
  BUFX2 drc_bufs638(.A (n_89), .Y (out[14]));
  BUFX2 drc_bufs639(.A (n_88), .Y (out[1]));
  BUFX2 drc_bufs640(.A (n_87), .Y (out[2]));
  BUFX2 drc_bufs641(.A (n_86), .Y (out[3]));
  BUFX2 drc_bufs642(.A (n_85), .Y (out[4]));
  BUFX2 drc_bufs643(.A (n_84), .Y (out[5]));
  BUFX2 drc_bufs644(.A (n_82), .Y (out[7]));
  BUFX2 drc_bufs645(.A (n_81), .Y (out[8]));
  BUFX2 drc_bufs646(.A (n_80), .Y (out[9]));
endmodule

module counter_WIDTH16(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [15:0] out;
  output overflow;
  wire clk, en, rst;
  wire [15:0] out;
  wire overflow;
  wire n_0, n_16, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_84, n_85, n_86, n_87;
  wire n_88, n_89, n_90, n_91, n_92, n_93, n_94, n_95;
  wire n_96, n_97, n_98, n_99, n_100;
  DFFSR \out_reg[15] (.R (n_18), .S (1'b1), .CLK (clk), .D (n_81), .Q
       (n_84));
  DFFSR overflow_reg(.R (n_18), .S (1'b1), .CLK (clk), .D (n_83), .Q
       (n_85));
  INVX1 g293(.A (n_82), .Y (n_83));
  MUX2X1 g294(.A (n_78), .B (overflow), .S (en), .Y (n_82));
  INVX1 g295(.A (n_80), .Y (n_81));
  MUX2X1 g296(.A (n_79), .B (n_16), .S (en), .Y (n_80));
  DFFSR \out_reg[14] (.R (n_18), .S (1'b1), .CLK (clk), .D (n_77), .Q
       (n_95));
  HAX1 g298(.A (n_16), .B (n_74), .YC (n_78), .YS (n_79));
  INVX1 g299(.A (n_76), .Y (n_77));
  MUX2X1 g300(.A (n_75), .B (out[14]), .S (en), .Y (n_76));
  DFFSR \out_reg[13] (.R (n_18), .S (1'b1), .CLK (clk), .D (n_73), .Q
       (n_96));
  HAX1 g302(.A (out[14]), .B (n_70), .YC (n_74), .YS (n_75));
  INVX1 g303(.A (n_72), .Y (n_73));
  MUX2X1 g304(.A (n_71), .B (out[13]), .S (en), .Y (n_72));
  DFFSR \out_reg[12] (.R (n_18), .S (1'b1), .CLK (clk), .D (n_69), .Q
       (n_97));
  HAX1 g306(.A (out[13]), .B (n_66), .YC (n_70), .YS (n_71));
  INVX1 g307(.A (n_68), .Y (n_69));
  MUX2X1 g308(.A (n_67), .B (out[12]), .S (en), .Y (n_68));
  DFFSR \out_reg[11] (.R (n_18), .S (1'b1), .CLK (clk), .D (n_65), .Q
       (n_98));
  HAX1 g310(.A (out[12]), .B (n_62), .YC (n_66), .YS (n_67));
  INVX1 g311(.A (n_64), .Y (n_65));
  MUX2X1 g312(.A (n_63), .B (out[11]), .S (en), .Y (n_64));
  DFFSR \out_reg[10] (.R (n_18), .S (1'b1), .CLK (clk), .D (n_61), .Q
       (n_99));
  HAX1 g314(.A (out[11]), .B (n_58), .YC (n_62), .YS (n_63));
  INVX1 g315(.A (n_60), .Y (n_61));
  MUX2X1 g316(.A (n_59), .B (out[10]), .S (en), .Y (n_60));
  DFFSR \out_reg[9] (.R (n_18), .S (1'b1), .CLK (clk), .D (n_57), .Q
       (n_86));
  HAX1 g318(.A (out[10]), .B (n_54), .YC (n_58), .YS (n_59));
  INVX1 g319(.A (n_56), .Y (n_57));
  MUX2X1 g320(.A (n_55), .B (out[9]), .S (en), .Y (n_56));
  DFFSR \out_reg[8] (.R (n_18), .S (1'b1), .CLK (clk), .D (n_53), .Q
       (n_87));
  HAX1 g322(.A (out[9]), .B (n_50), .YC (n_54), .YS (n_55));
  INVX1 g323(.A (n_52), .Y (n_53));
  MUX2X1 g324(.A (n_51), .B (out[8]), .S (en), .Y (n_52));
  DFFSR \out_reg[7] (.R (n_18), .S (1'b1), .CLK (clk), .D (n_49), .Q
       (n_88));
  HAX1 g326(.A (out[8]), .B (n_46), .YC (n_50), .YS (n_51));
  INVX1 g327(.A (n_48), .Y (n_49));
  MUX2X1 g328(.A (n_47), .B (out[7]), .S (en), .Y (n_48));
  DFFSR \out_reg[6] (.R (n_18), .S (1'b1), .CLK (clk), .D (n_45), .Q
       (n_89));
  HAX1 g330(.A (out[7]), .B (n_42), .YC (n_46), .YS (n_47));
  INVX1 g331(.A (n_44), .Y (n_45));
  MUX2X1 g332(.A (n_43), .B (out[6]), .S (en), .Y (n_44));
  DFFSR \out_reg[5] (.R (n_18), .S (1'b1), .CLK (clk), .D (n_41), .Q
       (n_90));
  HAX1 g334(.A (out[6]), .B (n_38), .YC (n_42), .YS (n_43));
  INVX1 g335(.A (n_40), .Y (n_41));
  MUX2X1 g336(.A (n_39), .B (out[5]), .S (en), .Y (n_40));
  DFFSR \out_reg[4] (.R (n_18), .S (1'b1), .CLK (clk), .D (n_37), .Q
       (n_91));
  HAX1 g338(.A (out[5]), .B (n_34), .YC (n_38), .YS (n_39));
  INVX1 g339(.A (n_36), .Y (n_37));
  MUX2X1 g340(.A (n_35), .B (out[4]), .S (en), .Y (n_36));
  DFFSR \out_reg[3] (.R (n_18), .S (1'b1), .CLK (clk), .D (n_33), .Q
       (n_92));
  HAX1 g342(.A (out[4]), .B (n_30), .YC (n_34), .YS (n_35));
  INVX1 g343(.A (n_32), .Y (n_33));
  MUX2X1 g344(.A (n_31), .B (out[3]), .S (en), .Y (n_32));
  DFFSR \out_reg[2] (.R (n_18), .S (1'b1), .CLK (clk), .D (n_29), .Q
       (n_93));
  HAX1 g346(.A (out[3]), .B (n_26), .YC (n_30), .YS (n_31));
  INVX1 g347(.A (n_28), .Y (n_29));
  MUX2X1 g348(.A (n_27), .B (out[2]), .S (en), .Y (n_28));
  DFFSR \out_reg[1] (.R (n_18), .S (1'b1), .CLK (clk), .D (n_25), .Q
       (n_94));
  HAX1 g350(.A (out[2]), .B (n_22), .YC (n_26), .YS (n_27));
  INVX1 g351(.A (n_24), .Y (n_25));
  MUX2X1 g352(.A (n_23), .B (out[1]), .S (en), .Y (n_24));
  DFFSR \out_reg[0] (.R (n_18), .S (1'b1), .CLK (clk), .D (n_21), .Q
       (n_100));
  HAX1 g354(.A (out[1]), .B (out[0]), .YC (n_22), .YS (n_23));
  OAI21X1 g355(.A (out[0]), .B (n_19), .C (n_0), .Y (n_21));
  NAND2X1 g356(.A (out[0]), .B (n_19), .Y (n_20));
  INVX1 g357(.A (en), .Y (n_19));
  INVX1 g358(.A (rst), .Y (n_18));
  BUFX2 drc_bufs444(.A (n_20), .Y (n_0));
  BUFX2 drc_bufs446(.A (n_100), .Y (out[0]));
  BUFX2 drc_bufs447(.A (n_99), .Y (out[10]));
  BUFX2 drc_bufs448(.A (n_85), .Y (overflow));
  BUFX2 drc_bufs449(.A (n_84), .Y (n_16));
  BUFX2 drc_bufs450(.A (n_98), .Y (out[11]));
  BUFX2 drc_bufs451(.A (n_97), .Y (out[12]));
  BUFX2 drc_bufs452(.A (n_89), .Y (out[6]));
  BUFX2 drc_bufs453(.A (n_96), .Y (out[13]));
  BUFX2 drc_bufs454(.A (n_95), .Y (out[14]));
  BUFX2 drc_bufs455(.A (n_94), .Y (out[1]));
  BUFX2 drc_bufs456(.A (n_93), .Y (out[2]));
  BUFX2 drc_bufs457(.A (n_92), .Y (out[3]));
  BUFX2 drc_bufs458(.A (n_91), .Y (out[4]));
  BUFX2 drc_bufs459(.A (n_90), .Y (out[5]));
  BUFX2 drc_bufs460(.A (n_88), .Y (out[7]));
  BUFX2 drc_bufs461(.A (n_87), .Y (out[8]));
  BUFX2 drc_bufs462(.A (n_86), .Y (out[9]));
endmodule

module counter_WIDTH3(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [2:0] out;
  output overflow;
  wire clk, en, rst;
  wire [2:0] out;
  wire overflow;
  wire n_5, n_7, n_8, n_9, n_10, n_11, n_12, n_13;
  wire n_14, n_15, n_16, n_17, n_18, n_19, n_20, n_48;
  DFFSR \out_reg[2] (.R (n_5), .S (1'b1), .CLK (clk), .D (n_16), .Q
       (n_18));
  DFFSR overflow_reg(.R (n_5), .S (1'b1), .CLK (clk), .D (n_14), .Q
       (n_17));
  INVX1 g53(.A (n_15), .Y (n_16));
  MUX2X1 g54(.A (n_12), .B (out[2]), .S (en), .Y (n_15));
  INVX1 g55(.A (n_13), .Y (n_14));
  MUX2X1 g56(.A (n_11), .B (overflow), .S (en), .Y (n_13));
  DFFSR \out_reg[1] (.R (n_5), .S (1'b1), .CLK (clk), .D (n_10), .Q
       (n_19));
  HAX1 g58(.A (out[2]), .B (n_7), .YC (n_11), .YS (n_12));
  INVX1 g59(.A (n_9), .Y (n_10));
  MUX2X1 g60(.A (n_8), .B (out[1]), .S (en), .Y (n_9));
  DFFSR \out_reg[0] (.R (n_5), .S (1'b1), .CLK (clk), .D (n_48), .Q
       (n_20));
  HAX1 g62(.A (out[1]), .B (out[0]), .YC (n_7), .YS (n_8));
  INVX1 g65(.A (rst), .Y (n_5));
  BUFX2 drc_bufs88(.A (n_17), .Y (overflow));
  BUFX2 drc_bufs89(.A (n_20), .Y (out[0]));
  BUFX2 drc_bufs90(.A (n_19), .Y (out[1]));
  BUFX2 drc_bufs91(.A (n_18), .Y (out[2]));
  XOR2X1 g2(.A (out[0]), .B (en), .Y (n_48));
endmodule

module counter_WIDTH4(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [3:0] out;
  output overflow;
  wire clk, en, rst;
  wire [3:0] out;
  wire overflow;
  wire n_6, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_60;
  DFFSR \out_reg[3] (.R (n_6), .S (1'b1), .CLK (clk), .D (n_21), .Q
       (n_23));
  DFFSR overflow_reg(.R (n_6), .S (1'b1), .CLK (clk), .D (n_19), .Q
       (n_22));
  INVX1 g67(.A (n_20), .Y (n_21));
  MUX2X1 g68(.A (n_17), .B (out[3]), .S (en), .Y (n_20));
  INVX1 g69(.A (n_18), .Y (n_19));
  MUX2X1 g70(.A (n_16), .B (overflow), .S (en), .Y (n_18));
  DFFSR \out_reg[2] (.R (n_6), .S (1'b1), .CLK (clk), .D (n_15), .Q
       (n_24));
  HAX1 g72(.A (out[3]), .B (n_12), .YC (n_16), .YS (n_17));
  INVX1 g73(.A (n_14), .Y (n_15));
  MUX2X1 g74(.A (n_13), .B (out[2]), .S (en), .Y (n_14));
  DFFSR \out_reg[1] (.R (n_6), .S (1'b1), .CLK (clk), .D (n_11), .Q
       (n_25));
  HAX1 g76(.A (n_8), .B (out[2]), .YC (n_12), .YS (n_13));
  INVX1 g77(.A (n_10), .Y (n_11));
  MUX2X1 g78(.A (n_9), .B (out[1]), .S (en), .Y (n_10));
  DFFSR \out_reg[0] (.R (n_6), .S (1'b1), .CLK (clk), .D (n_60), .Q
       (n_26));
  HAX1 g80(.A (out[1]), .B (out[0]), .YC (n_8), .YS (n_9));
  INVX1 g83(.A (rst), .Y (n_6));
  BUFX2 drc_bufs111(.A (n_22), .Y (overflow));
  BUFX2 drc_bufs112(.A (n_26), .Y (out[0]));
  BUFX2 drc_bufs113(.A (n_24), .Y (out[2]));
  BUFX2 drc_bufs114(.A (n_23), .Y (out[3]));
  BUFX2 drc_bufs115(.A (n_25), .Y (out[1]));
  XOR2X1 g2(.A (out[0]), .B (en), .Y (n_60));
endmodule

module counter_WIDTH5(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [4:0] out;
  output overflow;
  wire clk, en, rst;
  wire [4:0] out;
  wire overflow;
  wire n_7, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_72;
  DFFSR \out_reg[4] (.R (n_7), .S (1'b1), .CLK (clk), .D (n_26), .Q
       (n_28));
  DFFSR overflow_reg(.R (n_7), .S (1'b1), .CLK (clk), .D (n_24), .Q
       (n_27));
  INVX1 g80(.A (n_25), .Y (n_26));
  MUX2X1 g81(.A (n_22), .B (out[4]), .S (en), .Y (n_25));
  INVX1 g82(.A (n_23), .Y (n_24));
  MUX2X1 g83(.A (n_21), .B (overflow), .S (en), .Y (n_23));
  DFFSR \out_reg[3] (.R (n_7), .S (1'b1), .CLK (clk), .D (n_20), .Q
       (n_29));
  HAX1 g85(.A (out[4]), .B (n_17), .YC (n_21), .YS (n_22));
  INVX1 g86(.A (n_19), .Y (n_20));
  MUX2X1 g87(.A (n_18), .B (out[3]), .S (en), .Y (n_19));
  DFFSR \out_reg[2] (.R (n_7), .S (1'b1), .CLK (clk), .D (n_16), .Q
       (n_30));
  HAX1 g89(.A (out[3]), .B (n_13), .YC (n_17), .YS (n_18));
  INVX1 g90(.A (n_15), .Y (n_16));
  MUX2X1 g91(.A (n_14), .B (out[2]), .S (en), .Y (n_15));
  DFFSR \out_reg[1] (.R (n_7), .S (1'b1), .CLK (clk), .D (n_12), .Q
       (n_31));
  HAX1 g93(.A (out[2]), .B (n_9), .YC (n_13), .YS (n_14));
  INVX1 g94(.A (n_11), .Y (n_12));
  MUX2X1 g95(.A (n_10), .B (out[1]), .S (en), .Y (n_11));
  DFFSR \out_reg[0] (.R (n_7), .S (1'b1), .CLK (clk), .D (n_72), .Q
       (n_32));
  HAX1 g97(.A (out[1]), .B (out[0]), .YC (n_9), .YS (n_10));
  INVX1 g100(.A (rst), .Y (n_7));
  BUFX2 drc_bufs133(.A (n_27), .Y (overflow));
  BUFX2 drc_bufs134(.A (n_30), .Y (out[2]));
  BUFX2 drc_bufs135(.A (n_29), .Y (out[3]));
  BUFX2 drc_bufs136(.A (n_28), .Y (out[4]));
  BUFX2 drc_bufs137(.A (n_31), .Y (out[1]));
  BUFX2 drc_bufs138(.A (n_32), .Y (out[0]));
  XOR2X1 g2(.A (out[0]), .B (en), .Y (n_72));
endmodule

module counter_WIDTH6(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [5:0] out;
  output overflow;
  wire clk, en, rst;
  wire [5:0] out;
  wire overflow;
  wire n_8, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_84;
  DFFSR \out_reg[5] (.R (n_8), .S (1'b1), .CLK (clk), .D (n_31), .Q
       (n_33));
  DFFSR overflow_reg(.R (n_8), .S (1'b1), .CLK (clk), .D (n_29), .Q
       (n_32));
  INVX1 g96(.A (n_30), .Y (n_31));
  MUX2X1 g97(.A (n_27), .B (out[5]), .S (en), .Y (n_30));
  INVX1 g98(.A (n_28), .Y (n_29));
  MUX2X1 g99(.A (n_26), .B (overflow), .S (en), .Y (n_28));
  DFFSR \out_reg[4] (.R (n_8), .S (1'b1), .CLK (clk), .D (n_25), .Q
       (n_34));
  HAX1 g101(.A (out[5]), .B (n_22), .YC (n_26), .YS (n_27));
  INVX1 g102(.A (n_24), .Y (n_25));
  MUX2X1 g103(.A (n_23), .B (out[4]), .S (en), .Y (n_24));
  DFFSR \out_reg[3] (.R (n_8), .S (1'b1), .CLK (clk), .D (n_21), .Q
       (n_35));
  HAX1 g105(.A (out[4]), .B (n_18), .YC (n_22), .YS (n_23));
  INVX1 g106(.A (n_20), .Y (n_21));
  MUX2X1 g107(.A (n_19), .B (out[3]), .S (en), .Y (n_20));
  DFFSR \out_reg[2] (.R (n_8), .S (1'b1), .CLK (clk), .D (n_17), .Q
       (n_36));
  HAX1 g109(.A (out[3]), .B (n_14), .YC (n_18), .YS (n_19));
  INVX1 g110(.A (n_16), .Y (n_17));
  MUX2X1 g111(.A (n_15), .B (out[2]), .S (en), .Y (n_16));
  DFFSR \out_reg[1] (.R (n_8), .S (1'b1), .CLK (clk), .D (n_13), .Q
       (n_37));
  HAX1 g113(.A (out[2]), .B (n_10), .YC (n_14), .YS (n_15));
  INVX1 g114(.A (n_12), .Y (n_13));
  MUX2X1 g115(.A (n_11), .B (out[1]), .S (en), .Y (n_12));
  DFFSR \out_reg[0] (.R (n_8), .S (1'b1), .CLK (clk), .D (n_84), .Q
       (n_38));
  HAX1 g117(.A (out[1]), .B (out[0]), .YC (n_10), .YS (n_11));
  INVX1 g120(.A (rst), .Y (n_8));
  BUFX2 drc_bufs158(.A (n_32), .Y (overflow));
  BUFX2 drc_bufs159(.A (n_37), .Y (out[1]));
  BUFX2 drc_bufs160(.A (n_34), .Y (out[4]));
  BUFX2 drc_bufs161(.A (n_36), .Y (out[2]));
  BUFX2 drc_bufs162(.A (n_35), .Y (out[3]));
  BUFX2 drc_bufs163(.A (n_38), .Y (out[0]));
  BUFX2 drc_bufs164(.A (n_33), .Y (out[5]));
  XOR2X1 g2(.A (out[0]), .B (en), .Y (n_84));
endmodule

module counter_WIDTH7(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [6:0] out;
  output overflow;
  wire clk, en, rst;
  wire [6:0] out;
  wire overflow;
  wire n_9, n_11, n_12, n_13, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_34, n_35, n_36, n_37, n_38, n_39, n_40, n_41;
  wire n_42, n_43, n_44, n_96;
  DFFSR \out_reg[6] (.R (n_9), .S (1'b1), .CLK (clk), .D (n_36), .Q
       (n_38));
  DFFSR overflow_reg(.R (n_9), .S (1'b1), .CLK (clk), .D (n_34), .Q
       (n_37));
  INVX1 g115(.A (n_35), .Y (n_36));
  MUX2X1 g116(.A (n_32), .B (out[6]), .S (en), .Y (n_35));
  INVX1 g117(.A (n_33), .Y (n_34));
  MUX2X1 g118(.A (n_31), .B (overflow), .S (en), .Y (n_33));
  DFFSR \out_reg[5] (.R (n_9), .S (1'b1), .CLK (clk), .D (n_30), .Q
       (n_39));
  HAX1 g120(.A (out[6]), .B (n_27), .YC (n_31), .YS (n_32));
  INVX1 g121(.A (n_29), .Y (n_30));
  MUX2X1 g122(.A (n_28), .B (out[5]), .S (en), .Y (n_29));
  DFFSR \out_reg[4] (.R (n_9), .S (1'b1), .CLK (clk), .D (n_26), .Q
       (n_40));
  HAX1 g124(.A (out[5]), .B (n_23), .YC (n_27), .YS (n_28));
  INVX1 g125(.A (n_25), .Y (n_26));
  MUX2X1 g126(.A (n_24), .B (out[4]), .S (en), .Y (n_25));
  DFFSR \out_reg[3] (.R (n_9), .S (1'b1), .CLK (clk), .D (n_22), .Q
       (n_41));
  HAX1 g128(.A (out[4]), .B (n_19), .YC (n_23), .YS (n_24));
  INVX1 g129(.A (n_21), .Y (n_22));
  MUX2X1 g130(.A (n_20), .B (out[3]), .S (en), .Y (n_21));
  DFFSR \out_reg[2] (.R (n_9), .S (1'b1), .CLK (clk), .D (n_18), .Q
       (n_42));
  HAX1 g132(.A (out[3]), .B (n_15), .YC (n_19), .YS (n_20));
  INVX1 g133(.A (n_17), .Y (n_18));
  MUX2X1 g134(.A (n_16), .B (out[2]), .S (en), .Y (n_17));
  DFFSR \out_reg[1] (.R (n_9), .S (1'b1), .CLK (clk), .D (n_14), .Q
       (n_43));
  HAX1 g136(.A (out[2]), .B (n_11), .YC (n_15), .YS (n_16));
  INVX1 g137(.A (n_13), .Y (n_14));
  MUX2X1 g138(.A (n_12), .B (out[1]), .S (en), .Y (n_13));
  DFFSR \out_reg[0] (.R (n_9), .S (1'b1), .CLK (clk), .D (n_96), .Q
       (n_44));
  HAX1 g140(.A (out[1]), .B (out[0]), .YC (n_11), .YS (n_12));
  INVX1 g143(.A (rst), .Y (n_9));
  BUFX2 drc_bufs186(.A (n_37), .Y (overflow));
  BUFX2 drc_bufs187(.A (n_44), .Y (out[0]));
  BUFX2 drc_bufs188(.A (n_43), .Y (out[1]));
  BUFX2 drc_bufs189(.A (n_42), .Y (out[2]));
  BUFX2 drc_bufs190(.A (n_41), .Y (out[3]));
  BUFX2 drc_bufs191(.A (n_40), .Y (out[4]));
  BUFX2 drc_bufs192(.A (n_39), .Y (out[5]));
  BUFX2 drc_bufs193(.A (n_38), .Y (out[6]));
  XOR2X1 g2(.A (out[0]), .B (en), .Y (n_96));
endmodule

module counter_WIDTH8(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [7:0] out;
  output overflow;
  wire clk, en, rst;
  wire [7:0] out;
  wire overflow;
  wire n_10, n_12, n_13, n_14, n_15, n_16, n_17, n_18;
  wire n_19, n_20, n_21, n_22, n_23, n_24, n_25, n_26;
  wire n_27, n_28, n_29, n_30, n_31, n_32, n_33, n_34;
  wire n_35, n_36, n_37, n_38, n_39, n_40, n_41, n_42;
  wire n_43, n_44, n_45, n_46, n_47, n_48, n_49, n_50;
  wire n_108;
  DFFSR \out_reg[7] (.R (n_10), .S (1'b1), .CLK (clk), .D (n_41), .Q
       (n_43));
  DFFSR overflow_reg(.R (n_10), .S (1'b1), .CLK (clk), .D (n_39), .Q
       (n_42));
  INVX1 g128(.A (n_40), .Y (n_41));
  MUX2X1 g129(.A (n_37), .B (out[7]), .S (en), .Y (n_40));
  INVX1 g130(.A (n_38), .Y (n_39));
  MUX2X1 g131(.A (n_36), .B (overflow), .S (en), .Y (n_38));
  DFFSR \out_reg[6] (.R (n_10), .S (1'b1), .CLK (clk), .D (n_35), .Q
       (n_44));
  HAX1 g133(.A (out[7]), .B (n_32), .YC (n_36), .YS (n_37));
  INVX1 g134(.A (n_34), .Y (n_35));
  MUX2X1 g135(.A (n_33), .B (out[6]), .S (en), .Y (n_34));
  DFFSR \out_reg[5] (.R (n_10), .S (1'b1), .CLK (clk), .D (n_31), .Q
       (n_45));
  HAX1 g137(.A (out[6]), .B (n_28), .YC (n_32), .YS (n_33));
  INVX1 g138(.A (n_30), .Y (n_31));
  MUX2X1 g139(.A (n_29), .B (out[5]), .S (en), .Y (n_30));
  DFFSR \out_reg[4] (.R (n_10), .S (1'b1), .CLK (clk), .D (n_27), .Q
       (n_46));
  HAX1 g141(.A (out[5]), .B (n_24), .YC (n_28), .YS (n_29));
  INVX1 g142(.A (n_26), .Y (n_27));
  MUX2X1 g143(.A (n_25), .B (out[4]), .S (en), .Y (n_26));
  DFFSR \out_reg[3] (.R (n_10), .S (1'b1), .CLK (clk), .D (n_23), .Q
       (n_47));
  HAX1 g145(.A (out[4]), .B (n_20), .YC (n_24), .YS (n_25));
  INVX1 g146(.A (n_22), .Y (n_23));
  MUX2X1 g147(.A (n_21), .B (out[3]), .S (en), .Y (n_22));
  DFFSR \out_reg[2] (.R (n_10), .S (1'b1), .CLK (clk), .D (n_19), .Q
       (n_48));
  HAX1 g149(.A (out[3]), .B (n_16), .YC (n_20), .YS (n_21));
  INVX1 g150(.A (n_18), .Y (n_19));
  MUX2X1 g151(.A (n_17), .B (out[2]), .S (en), .Y (n_18));
  DFFSR \out_reg[1] (.R (n_10), .S (1'b1), .CLK (clk), .D (n_15), .Q
       (n_49));
  HAX1 g153(.A (out[2]), .B (n_12), .YC (n_16), .YS (n_17));
  INVX1 g154(.A (n_14), .Y (n_15));
  MUX2X1 g155(.A (n_13), .B (out[1]), .S (en), .Y (n_14));
  DFFSR \out_reg[0] (.R (n_10), .S (1'b1), .CLK (clk), .D (n_108), .Q
       (n_50));
  HAX1 g157(.A (out[1]), .B (out[0]), .YC (n_12), .YS (n_13));
  INVX1 g160(.A (rst), .Y (n_10));
  BUFX2 drc_bufs208(.A (n_50), .Y (out[0]));
  BUFX2 drc_bufs209(.A (n_43), .Y (out[7]));
  BUFX2 drc_bufs210(.A (n_44), .Y (out[6]));
  BUFX2 drc_bufs211(.A (n_42), .Y (overflow));
  BUFX2 drc_bufs212(.A (n_49), .Y (out[1]));
  BUFX2 drc_bufs213(.A (n_48), .Y (out[2]));
  BUFX2 drc_bufs214(.A (n_47), .Y (out[3]));
  BUFX2 drc_bufs215(.A (n_46), .Y (out[4]));
  BUFX2 drc_bufs216(.A (n_45), .Y (out[5]));
  XOR2X1 g2(.A (out[0]), .B (en), .Y (n_108));
endmodule

module counter_WIDTH9(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [8:0] out;
  output overflow;
  wire clk, en, rst;
  wire [8:0] out;
  wire overflow;
  wire n_11, n_13, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_33, n_34, n_35;
  wire n_36, n_37, n_38, n_39, n_40, n_41, n_42, n_43;
  wire n_44, n_45, n_46, n_47, n_48, n_49, n_50, n_51;
  wire n_52, n_53, n_54, n_55, n_56, n_120;
  DFFSR \out_reg[8] (.R (n_11), .S (1'b1), .CLK (clk), .D (n_46), .Q
       (n_48));
  DFFSR overflow_reg(.R (n_11), .S (1'b1), .CLK (clk), .D (n_44), .Q
       (n_47));
  INVX1 g154(.A (n_45), .Y (n_46));
  MUX2X1 g155(.A (n_42), .B (out[8]), .S (en), .Y (n_45));
  INVX1 g156(.A (n_43), .Y (n_44));
  MUX2X1 g157(.A (n_41), .B (overflow), .S (en), .Y (n_43));
  DFFSR \out_reg[7] (.R (n_11), .S (1'b1), .CLK (clk), .D (n_40), .Q
       (n_49));
  HAX1 g159(.A (out[8]), .B (n_37), .YC (n_41), .YS (n_42));
  INVX1 g160(.A (n_39), .Y (n_40));
  MUX2X1 g161(.A (n_38), .B (out[7]), .S (en), .Y (n_39));
  DFFSR \out_reg[6] (.R (n_11), .S (1'b1), .CLK (clk), .D (n_36), .Q
       (n_50));
  HAX1 g163(.A (out[7]), .B (n_33), .YC (n_37), .YS (n_38));
  INVX1 g164(.A (n_35), .Y (n_36));
  MUX2X1 g165(.A (n_34), .B (out[6]), .S (en), .Y (n_35));
  DFFSR \out_reg[5] (.R (n_11), .S (1'b1), .CLK (clk), .D (n_32), .Q
       (n_51));
  HAX1 g167(.A (out[6]), .B (n_29), .YC (n_33), .YS (n_34));
  INVX1 g168(.A (n_31), .Y (n_32));
  MUX2X1 g169(.A (n_30), .B (out[5]), .S (en), .Y (n_31));
  DFFSR \out_reg[4] (.R (n_11), .S (1'b1), .CLK (clk), .D (n_28), .Q
       (n_52));
  HAX1 g171(.A (out[5]), .B (n_25), .YC (n_29), .YS (n_30));
  INVX1 g172(.A (n_27), .Y (n_28));
  MUX2X1 g173(.A (n_26), .B (out[4]), .S (en), .Y (n_27));
  DFFSR \out_reg[3] (.R (n_11), .S (1'b1), .CLK (clk), .D (n_24), .Q
       (n_53));
  HAX1 g175(.A (out[4]), .B (n_21), .YC (n_25), .YS (n_26));
  INVX1 g176(.A (n_23), .Y (n_24));
  MUX2X1 g177(.A (n_22), .B (out[3]), .S (en), .Y (n_23));
  DFFSR \out_reg[2] (.R (n_11), .S (1'b1), .CLK (clk), .D (n_20), .Q
       (n_54));
  HAX1 g179(.A (out[3]), .B (n_17), .YC (n_21), .YS (n_22));
  INVX1 g180(.A (n_19), .Y (n_20));
  MUX2X1 g181(.A (n_18), .B (out[2]), .S (en), .Y (n_19));
  DFFSR \out_reg[1] (.R (n_11), .S (1'b1), .CLK (clk), .D (n_16), .Q
       (n_55));
  HAX1 g183(.A (out[2]), .B (n_13), .YC (n_17), .YS (n_18));
  INVX1 g184(.A (n_15), .Y (n_16));
  MUX2X1 g185(.A (n_14), .B (out[1]), .S (en), .Y (n_15));
  DFFSR \out_reg[0] (.R (n_11), .S (1'b1), .CLK (clk), .D (n_120), .Q
       (n_56));
  HAX1 g187(.A (out[1]), .B (out[0]), .YC (n_13), .YS (n_14));
  INVX1 g190(.A (rst), .Y (n_11));
  BUFX2 drc_bufs243(.A (n_47), .Y (overflow));
  BUFX2 drc_bufs244(.A (n_56), .Y (out[0]));
  BUFX2 drc_bufs245(.A (n_50), .Y (out[6]));
  BUFX2 drc_bufs246(.A (n_49), .Y (out[7]));
  BUFX2 drc_bufs247(.A (n_51), .Y (out[5]));
  BUFX2 drc_bufs248(.A (n_48), .Y (out[8]));
  BUFX2 drc_bufs249(.A (n_55), .Y (out[1]));
  BUFX2 drc_bufs250(.A (n_54), .Y (out[2]));
  BUFX2 drc_bufs251(.A (n_53), .Y (out[3]));
  BUFX2 drc_bufs252(.A (n_52), .Y (out[4]));
  XOR2X1 g2(.A (out[0]), .B (en), .Y (n_120));
endmodule

module top(a, x1, xx1, xx2, xx3, xx4, xx5, xx6, xx7, xx8, xx9, zz1,
     zz2, zz3, zz4, zz5, zz6, zz7, zz8, zz9, ww1, ww2, ww3, ww4, ww,
     zz, y, y1);
  input a;
  input [2:0] x1, xx1, xx2, xx3, xx4, xx5, xx6, xx7, xx8, xx9;
  input [4:0] zz1, zz2, zz3, zz4, zz5, zz6, zz7, zz8, zz9;
  input [5:0] ww1, ww2, ww3, ww4;
  output [7:0] ww, zz;
  output y;
  output [5:0] y1;
  wire a;
  wire [2:0] x1, xx1, xx2, xx3, xx4, xx5, xx6, xx7, xx8, xx9;
  wire [4:0] zz1, zz2, zz3, zz4, zz5, zz6, zz7, zz8, zz9;
  wire [5:0] ww1, ww2, ww3, ww4;
  wire [7:0] ww, zz;
  wire y;
  wire [5:0] y1;
  wire [15:0] ctr_out;
  wire UNCONNECTED0, UNCONNECTED1, UNCONNECTED2, UNCONNECTED3,
       UNCONNECTED4, UNCONNECTED5, UNCONNECTED6, UNCONNECTED7;
  wire UNCONNECTED8, UNCONNECTED9, rst;
  assign y = a;
  add4_6b add4_6b(.x1 (ww1), .x2 (ww2), .x3 (ww3), .x4 (ww4), .y (ww));
  add8_3b add8_3b(.x1 (x1), .x2 (xx3), .x3 (xx4), .x4 (xx5), .x5 (xx6),
       .x6 (xx7), .x7 (xx8), .x8 (xx9), .y (y1));
  add8_5b add8_5b(.x1 (zz1), .x2 (zz2), .x3 (zz3), .x4 (zz4), .x5
       (zz5), .x6 (zz6), .x7 (zz7), .x8 (zz8), .y (zz));
  comp_3b comp_3b(.a_gt_b (a), .a (x1), .b (xx1));
  counter_WIDTH10 counter_10b(.out (ctr_out[9:0]), .clk (a), .en (a),
       .rst (rst), .overflow (a));
  counter_WIDTH11 counter_11b(.out (ctr_out[10:0]), .clk (a), .en (a),
       .rst (rst), .overflow (a));
  counter_WIDTH12 counter_12b(.out ({UNCONNECTED9, UNCONNECTED8,
       UNCONNECTED7, UNCONNECTED6, UNCONNECTED5, UNCONNECTED4,
       UNCONNECTED3, UNCONNECTED2, UNCONNECTED1, UNCONNECTED0,
       ctr_out[1:0]}), .clk (a), .en (a), .rst (rst), .overflow (a));
  counter_WIDTH13 counter_13b(.out (ctr_out[12:0]), .clk (a), .en (a),
       .rst (rst), .overflow (a));
  counter_WIDTH14 counter_14b(.out (ctr_out[13:0]), .clk (a), .en (a),
       .rst (rst), .overflow (a));
  counter_WIDTH15 counter_15b(.out (ctr_out[14:0]), .clk (a), .en (a),
       .rst (rst), .overflow (a));
  counter_WIDTH16 counter_16b(.out (ctr_out), .clk (a), .en (a), .rst
       (rst), .overflow (a));
  counter_WIDTH3 counter_3b(.out (ctr_out[2:0]), .clk (a), .en (a),
       .rst (rst), .overflow (a));
  counter_WIDTH4 counter_4b(.out (ctr_out[3:0]), .clk (a), .en (a),
       .rst (rst), .overflow (a));
  counter_WIDTH5 counter_5b(.out (ctr_out[4:0]), .clk (a), .en (a),
       .rst (rst), .overflow (a));
  counter_WIDTH6 counter_6b(.out (ctr_out[5:0]), .clk (a), .en (a),
       .rst (rst), .overflow (a));
  counter_WIDTH7 counter_7b(.out (ctr_out[6:0]), .clk (a), .en (a),
       .rst (rst), .overflow (a));
  counter_WIDTH8 counter_8b(.out (ctr_out[7:0]), .clk (a), .en (a),
       .rst (rst), .overflow (a));
  counter_WIDTH9 counter_9b(.out (ctr_out[8:0]), .clk (a), .en (a),
       .rst (rst), .overflow (a));
endmodule

